#!/usr/bin/env python3
"""
Extract personalization data from Webflow CMS for GTM register page personalization.

Reads 76 slugs from sem_landing_pages.csv, fetches CMS items from Webflow,
extracts hero/testimonial/benefit fields, and outputs:
  - app/data/personalization_data.json (raw reference)
  - app/data/gtm_personalization_variable.js (ready to paste into GTM Custom JS variable)
"""
import csv
import json
import os
import re
import requests
import time

API_KEY = "87be5982f1938a9143a7368af984a9863971dd55314fd5a60f482cc02425a0c7"
LANDING_PAGES_COLLECTION = "6981a714e199bac70776d880"

HEADERS = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
APP_DIR = os.path.dirname(SCRIPT_DIR)
CSV_PATH = os.path.join(APP_DIR, "sem_landing_pages.csv")
DATA_DIR = os.path.join(APP_DIR, "data")
JSON_OUTPUT = os.path.join(DATA_DIR, "personalization_data.json")
JS_OUTPUT = os.path.join(DATA_DIR, "gtm_personalization_variable.js")


def strip_html(html_text):
    """Remove HTML tags and decode entities."""
    if not html_text:
        return ""
    text = re.sub(r'<[^>]+>', '', html_text)
    text = text.replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>')
    text = text.replace('&#39;', "'").replace('&quot;', '"')
    text = text.replace('\u2014', ' - ').replace('\u2013', ' - ')
    return text.strip()


def load_slugs_from_csv():
    """Read valid slugs from sem_landing_pages.csv."""
    slugs = []
    with open(CSV_PATH, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            slug = row.get('Slug', '').strip()
            if slug:
                slugs.append(slug)
    print(f"Loaded {len(slugs)} slugs from CSV")
    return slugs


def fetch_all_items():
    """Fetch all items from the landing pages collection (paginated)."""
    all_items = []
    offset = 0
    while True:
        url = f"https://api.webflow.com/v2/collections/{LANDING_PAGES_COLLECTION}/items?limit=100&offset={offset}"
        response = requests.get(url, headers=HEADERS)
        response.raise_for_status()
        data = response.json()
        items = data.get('items', [])
        all_items.extend(items)
        print(f"  Fetched {len(items)} items (offset={offset}, total so far: {len(all_items)})")
        if len(items) < 100:
            break
        offset += 100
        time.sleep(0.3)
    print(f"Total CMS items fetched: {len(all_items)}")
    return all_items


def extract_personalization(item):
    """Extract personalization fields from a single CMS item."""
    fd = item.get('fieldData', {})
    return {
        "headline": fd.get("hero-headline", ""),
        "ctaText": fd.get("hero-cta-text", ""),
        "testimonialQuote": strip_html(fd.get("featured-testimonial-quote", "")),
        "testimonialName": fd.get("featured-testimonial-name", ""),
        "testimonialResult": fd.get("featured-testimonial-result", ""),
        "benefit1": fd.get("membership-benefit-1", ""),
        "benefit2": fd.get("membership-benefit-2", ""),
        "benefit3": fd.get("membership-benefit-3", ""),
        "benefit4": fd.get("membership-benefit-4", ""),
        "stat1Number": fd.get("stat-1-number", ""),
        "stat1Text": fd.get("stat-1-text", ""),
    }


def generate_gtm_js(personalization_map):
    """Generate a GTM Custom JavaScript variable that returns the lookup map."""
    json_str = json.dumps(personalization_map, indent=2)
    return f"""function() {{
  // Auto-generated by extract_personalization_data.py
  // {len(personalization_map)} landing page variants for /register personalization
  return {json_str};
}}"""


def main():
    print("=== Extract Personalization Data for GTM ===\n")

    # 1. Load target slugs
    target_slugs = set(load_slugs_from_csv())

    # 2. Fetch all CMS items
    print("\nFetching all CMS items...")
    all_items = fetch_all_items()

    # 3. Build slug -> item lookup
    slug_to_item = {}
    for item in all_items:
        slug = item.get('fieldData', {}).get('slug', '')
        if slug:
            slug_to_item[slug] = item

    # 4. Filter to CSV slugs and extract personalization data
    personalization_map = {}
    found = 0
    missing = []

    for slug in sorted(target_slugs):
        if slug in slug_to_item:
            personalization_map[slug] = extract_personalization(slug_to_item[slug])
            found += 1
        else:
            missing.append(slug)

    print(f"\nMatched {found}/{len(target_slugs)} slugs")
    if missing:
        print(f"Missing slugs ({len(missing)}): {', '.join(missing)}")

    # 5. Write JSON output
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(JSON_OUTPUT, 'w') as f:
        json.dump(personalization_map, f, indent=2)
    json_size = os.path.getsize(JSON_OUTPUT)
    print(f"\nWrote {JSON_OUTPUT} ({json_size:,} bytes)")

    # 6. Write GTM JS variable output
    gtm_js = generate_gtm_js(personalization_map)
    with open(JS_OUTPUT, 'w') as f:
        f.write(gtm_js)
    js_size = os.path.getsize(JS_OUTPUT)
    print(f"Wrote {JS_OUTPUT} ({js_size:,} bytes)")

    # 7. Summary
    print(f"\n=== Done ===")
    print(f"Pages extracted: {found}")
    print(f"JSON size: {json_size:,} bytes")
    print(f"GTM JS size: {js_size:,} bytes (~{js_size/1024:.1f} KB)")
    if js_size > 200_000:
        print("WARNING: JS output exceeds 200 KB GTM container limit!")
    else:
        print(f"GTM container budget: {js_size/200_000*100:.1f}% of 200 KB limit")


if __name__ == "__main__":
    main()
