#!/usr/bin/env python3
"""Batch 4: Rewrite first 13 Tier 2 biomarker-test pages.
CKD, heart failure, anemia of chronic disease, atherosclerosis, PAD,
obesity, sleep apnea, chronic stress, cirrhosis, hepatitis, IBD,
prostate cancer, chronic infection."""
import requests
import time
import json

API_KEY = "87be5982f1938a9143a7368af984a9863971dd55314fd5a60f482cc02425a0c7"
LP_COLLECTION = "6981a714e199bac70776d880"
HEADERS = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}

REWRITES = {
    "chronic-kidney-disease-biomarker-test": {
        "name": "Chronic Kidney Disease Biomarker Test",
        "hero-headline": "37 Million Americans Have Kidney Disease. 90% Don't Know It.",
        "hero-subheadline": "<p>Chronic kidney disease destroys kidney function silently for years before symptoms appear. eGFR, creatinine, and BUN screen for declining filtration - catching damage early enough to slow or stop progression. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen Your Kidney Function",
        "primary-keyword": "chronic kidney disease blood test",
        "secondary-keywords": "CKD blood test, kidney function test, eGFR test, creatinine kidney test",
        "symptom-headline": "Risk factors that warrant kidney screening",
        "symptom-1": "Diabetes or high blood pressure - the two leading causes of CKD",
        "symptom-2": "Family history of kidney disease or kidney failure",
        "symptom-3": "Swelling in ankles, feet, or puffiness around eyes",
        "symptom-4": "Foamy urine or changes in urination patterns",
        "symptom-5": "Long-term use of NSAIDs or other nephrotoxic medications",
        "symptom-cta": "Check your kidney function before symptoms start ->",
        "stat-1-number": "37M",
        "stat-1-text": "Americans have chronic kidney disease - 90% are undiagnosed because kidneys compensate until they can't",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Routine blood work showed my eGFR was 58 - stage 3 CKD. No symptoms at all. Creatinine was 1.4 and trending up over two years. Caught it early enough that blood pressure control and dietary changes stabilized my kidney function. Without that test, I wouldn't have known until it was too late.</p>",
        "featured-testimonial-name": "Robert K.",
        "featured-testimonial-result": "Stage 3 CKD caught before symptoms - kidney function stabilized",
        "membership-subheadline": "Monitor kidney function and catch decline early",
        "membership-benefit-1": "eGFR, creatinine, and BUN tracked annually",
        "membership-benefit-2": "100+ biomarkers including metabolic panel",
        "membership-benefit-3": "AI flags kidney function trends over time",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests eGFR (estimated glomerular filtration rate), creatinine, BUN, complete metabolic panel, electrolytes, uric acid, CRP, CBC, and lipid panel - the key kidney screening biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "eGFR is the gold standard for kidney function screening. It estimates how well your kidneys filter waste from blood. An eGFR below 60 for three months indicates chronic kidney disease. Creatinine and BUN provide additional context about kidney filtration capacity.",
        "how-it-works-3-subheading": "This panel provides screening markers for kidney health - not a full nephrology workup. eGFR, creatinine, and BUN detect declining filtration. Electrolytes and metabolic markers flag kidney-related imbalances. If screening shows concern, a nephrologist can order urine albumin and imaging.",
        "how-it-works-4-subheading": "Our clinical team explains your kidney biomarkers in context, identifies risk factors like diabetes and hypertension that accelerate CKD, and recommends nephrology referral if eGFR is declining. Results in about 10 days.",
        "condition-name": "Chronic Kidney Disease Screening",
        "condition-overview": "<p>Chronic kidney disease (CKD) affects 37 million Americans - roughly 15% of the adult population. 90% are undiagnosed because kidney disease produces no symptoms until late stages. CKD is most commonly caused by diabetes and hypertension. Blood biomarkers like eGFR, creatinine, and BUN screen for declining kidney filtration before irreversible damage occurs.</p>",
        "why-test": "<p>Kidneys can lose up to 75% of function before symptoms appear. Blood screening with eGFR, creatinine, and BUN catches declining filtration during the silent phase when intervention can slow or stop progression. This is especially critical for anyone with diabetes, hypertension, or family history of kidney disease.</p>",
        "what-is-included": "<p>Your panel includes eGFR, creatinine, BUN, complete metabolic panel, electrolytes (sodium, potassium, calcium, phosphorus), uric acid, CRP, CBC, lipid panel, and fasting glucose - 100+ biomarkers total.</p>",
        "next-steps": "<p>If eGFR is below 60 or trending downward, our care team recommends nephrology referral for further evaluation including urine testing and imaging. For early-stage CKD, they guide blood pressure optimization, dietary modifications, and medication review to protect remaining kidney function.</p>",
        "meta-title": "Kidney Disease Blood Test | eGFR + CKD Screen | Superpower",
        "meta-description": "Screen for chronic kidney disease - eGFR, creatinine, BUN. 37M Americans affected, 90% undiagnosed. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Kidney Disease Blood Test | eGFR + CKD Screen | Superpower",
        "og-description": "90% of kidney disease is undiagnosed. Screen eGFR + creatinine + 100+ biomarkers. ~10 day results.",
    },
    "heart-failure-biomarker-test": {
        "name": "Heart Failure Biomarker Test",
        "hero-headline": "Heart Failure Doesn't Start With a Heart Attack. It Starts With Risk Factors You Can Test.",
        "hero-subheadline": "<p>Heart failure develops gradually as the heart weakens from uncontrolled hypertension, metabolic dysfunction, and vascular inflammation. While BNP is not included in a standard blood panel, lipids, hsCRP, kidney markers, and metabolic biomarkers assess the risk factors that lead to heart failure. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen Heart Failure Risk Factors",
        "primary-keyword": "heart failure blood test",
        "secondary-keywords": "heart failure biomarkers, cardiac risk blood test, heart failure screening",
        "symptom-headline": "Warning signs that heart failure risk factors need testing",
        "symptom-1": "Shortness of breath during activities that used to be easy",
        "symptom-2": "Swelling in legs, ankles, or feet that worsens by evening",
        "symptom-3": "Waking up at night gasping for air",
        "symptom-4": "Persistent fatigue with declining exercise tolerance",
        "symptom-5": "High blood pressure, diabetes, or previous heart attack",
        "symptom-cta": "Assess your heart failure risk factors now ->",
        "stat-1-number": "6.7M",
        "stat-1-text": "Americans have heart failure - hypertension, diabetes, and high cholesterol are the leading modifiable causes",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Dad had heart failure at 62. I wanted to catch my risk early. Superpower showed hsCRP at 4.2, LDL at 168, fasting insulin at 24, and eGFR trending down at 72. Four modifiable risk factors - all connected. Aggressive prevention started that week. Knowledge is everything when heart failure runs in your family.</p>",
        "featured-testimonial-name": "Brian T.",
        "featured-testimonial-result": "4 modifiable heart failure risk factors identified and addressed",
        "membership-subheadline": "Monitor cardiac risk factors before damage begins",
        "membership-benefit-1": "Lipids, CRP, and metabolic markers annually",
        "membership-benefit-2": "100+ biomarkers including kidney function",
        "membership-benefit-3": "AI tracks cardiac risk factor trends",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests hsCRP, ApoB, complete lipid panel, fasting insulin, HbA1c, eGFR, creatinine, BUN, thyroid panel, and CBC - the biomarkers that assess heart failure risk factors - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Heart failure is the end result of years of damage from hypertension, atherosclerosis, metabolic dysfunction, and kidney decline. Our panel tests the modifiable risk factors - lipids, inflammation, insulin resistance, and kidney function - that drive heart failure development. Note: BNP (the direct heart failure marker) requires a separate cardiology order.",
        "how-it-works-3-subheading": "Kidney dysfunction and heart failure are closely linked - declining eGFR independently predicts heart failure risk. Thyroid disease (both hyper and hypothyroid) weakens the heart. We test these alongside cardiac markers because treating root causes prevents heart failure better than treating symptoms.",
        "how-it-works-4-subheading": "Our clinical team explains which risk factors are elevated and recommends targeted interventions - lipid management, insulin resistance treatment, blood pressure optimization, or cardiology referral for further evaluation. Results in about 10 days.",
        "condition-name": "Heart Failure Risk Factor Screening",
        "condition-overview": "<p>Heart failure affects 6.7 million Americans and occurs when the heart can no longer pump blood efficiently. It develops gradually from years of damage caused by hypertension, coronary artery disease, diabetes, and metabolic dysfunction. Blood biomarkers assess the modifiable risk factors that lead to heart failure - allowing prevention before irreversible cardiac damage occurs.</p>",
        "why-test": "<p>Heart failure is preventable when its root causes are identified and treated early. Lipids and ApoB assess atherosclerotic risk. hsCRP measures vascular inflammation. Fasting insulin and HbA1c detect metabolic dysfunction. eGFR screens kidney function - a major heart failure risk factor. Testing these biomarkers gives you a comprehensive cardiac risk profile. Note: BNP, which directly measures heart wall stress, requires a cardiology-ordered test.</p>",
        "what-is-included": "<p>Your panel includes hsCRP, ApoB, Lp(a), complete lipid panel, fasting insulin, HbA1c, fasting glucose, eGFR, creatinine, BUN, thyroid panel, liver enzymes, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If cardiac risk factors are elevated, our care team recommends targeted prevention - lipid management, metabolic optimization, and cardiology referral for further evaluation including BNP testing and cardiac imaging when appropriate.</p>",
        "meta-title": "Heart Failure Risk Test | Cardiac Biomarkers | Superpower",
        "meta-description": "Screen heart failure risk factors - lipids, CRP, kidney, metabolic markers. 6.7M Americans affected. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Heart Failure Risk Test | Cardiac Biomarkers | Superpower",
        "og-description": "Heart failure starts with risk factors you can test. Lipids + CRP + kidney + 100+ biomarkers. ~10 day results.",
    },
    "anemia-of-chronic-disease-biomarker-test": {
        "name": "Anemia of Chronic Disease Biomarker Test",
        "hero-headline": "Your Iron Supplements Aren't Working? The Problem May Not Be Iron.",
        "hero-subheadline": "<p>Anemia of chronic disease is the second most common form of anemia - and iron supplements make it worse, not better. CBC, iron studies, ferritin, and CRP distinguish it from iron deficiency so you get the right treatment. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Anemia Biomarkers",
        "primary-keyword": "anemia of chronic disease blood test",
        "secondary-keywords": "ACD blood test, chronic disease anemia biomarkers, anemia screening blood test",
        "symptom-headline": "Signs that point to anemia of chronic disease",
        "symptom-1": "Fatigue and weakness despite taking iron supplements",
        "symptom-2": "Existing autoimmune condition, chronic infection, or cancer",
        "symptom-3": "Pale skin and shortness of breath with mild activity",
        "symptom-4": "Low hemoglobin but ferritin is normal or high",
        "symptom-5": "Anemia that doesn't respond to iron supplementation",
        "symptom-cta": "Find the real cause of your anemia ->",
        "stat-1-number": "#2",
        "stat-1-text": "most common anemia worldwide - yet frequently misdiagnosed as iron deficiency, leading to wrong treatment",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Hemoglobin was 10.2 and my doctor put me on iron. Six months later, still 10.1. Superpower showed ferritin was actually 180 (not low at all) and CRP was 8.4 - chronic inflammation was trapping my iron. Completely different diagnosis, completely different treatment. Wish I'd tested sooner.</p>",
        "featured-testimonial-name": "Linda P.",
        "featured-testimonial-result": "Anemia of chronic disease identified after 6 months of wrong treatment",
        "membership-subheadline": "Distinguish anemia types and track treatment response",
        "membership-benefit-1": "CBC, iron studies, and CRP tested annually",
        "membership-benefit-2": "100+ biomarkers including kidney and thyroid",
        "membership-benefit-3": "AI distinguishes iron deficiency from ACD",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests CBC with differential, ferritin, iron, TIBC, transferrin saturation, CRP, ESR, complete metabolic panel, kidney function, and thyroid panel - the full anemia diagnostic panel - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Anemia of chronic disease (ACD) and iron deficiency anemia look similar on CBC - both cause low hemoglobin. The difference is in iron studies: iron deficiency shows low ferritin, while ACD shows normal or high ferritin with low iron and low TIBC. CRP confirms the underlying inflammation driving ACD.",
        "how-it-works-3-subheading": "CRP and inflammatory markers identify the chronic disease causing ACD - autoimmune conditions, chronic infections, kidney disease, or malignancy. Treating the underlying condition is the only effective approach. Iron supplementation in ACD can actually be harmful.",
        "how-it-works-4-subheading": "Our clinical team explains which type of anemia your biomarkers indicate, identifies the likely underlying cause, and recommends targeted treatment or specialist referral. Results in about 10 days.",
        "condition-name": "Anemia of Chronic Disease Screening",
        "condition-overview": "<p>Anemia of chronic disease (ACD) is the second most common form of anemia worldwide. It occurs when chronic inflammation - from autoimmune disease, infection, kidney disease, or cancer - disrupts iron metabolism, trapping iron in storage and reducing red blood cell production. Unlike iron deficiency, ferritin is typically normal or elevated in ACD.</p>",
        "why-test": "<p>ACD is frequently misdiagnosed as iron deficiency anemia because both cause low hemoglobin. The distinction matters because iron supplements - the standard treatment for iron deficiency - don't help ACD and can cause harm. CBC with iron studies, ferritin, and CRP together differentiate the two conditions so you receive the correct treatment.</p>",
        "what-is-included": "<p>Your panel includes CBC with differential, ferritin, serum iron, TIBC, transferrin saturation, CRP, complete metabolic panel, eGFR, creatinine, liver enzymes, thyroid panel, and B12 - 100+ biomarkers total.</p>",
        "next-steps": "<p>If biomarkers indicate anemia of chronic disease, our care team identifies the likely underlying inflammatory condition and recommends specialist referral. For confirmed iron deficiency, they guide supplementation type and dosing. Annual monitoring tracks treatment response.</p>",
        "meta-title": "Anemia of Chronic Disease Test | CBC + Iron | Superpower",
        "meta-description": "Distinguish anemia of chronic disease from iron deficiency - CBC, ferritin, iron, CRP. #2 most common anemia. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Anemia of Chronic Disease Test | CBC + Iron | Superpower",
        "og-description": "Iron supplements not working? It may not be iron deficiency. CBC + iron + CRP + 100+ biomarkers. ~10 day results.",
    },
    "atherosclerosis-biomarker-test": {
        "name": "Atherosclerosis Biomarker Test",
        "hero-headline": "Plaque Builds in Your Arteries for 20 Years Before a Heart Attack. These Biomarkers Catch It.",
        "hero-subheadline": "<p>Atherosclerosis - arterial plaque buildup - is driven by ApoB particles, Lp(a), hsCRP inflammation, and metabolic dysfunction. Blood biomarkers identify plaque risk factors decades before an event. Don't wait for a stress test to tell you something is wrong. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen for Atherosclerosis Risk",
        "primary-keyword": "atherosclerosis blood test",
        "secondary-keywords": "atherosclerosis biomarkers, plaque buildup blood test, arterial plaque screening",
        "symptom-headline": "Risk factors for arterial plaque buildup",
        "symptom-1": "Family history of heart attacks or strokes before age 60",
        "symptom-2": "High cholesterol that persists despite treatment",
        "symptom-3": "Diabetes, metabolic syndrome, or insulin resistance",
        "symptom-4": "History of smoking or chronic high blood pressure",
        "symptom-5": "Elevated Lp(a) or family history of elevated Lp(a)",
        "symptom-cta": "Get the biomarkers that predict plaque buildup ->",
        "stat-1-number": "50%",
        "stat-1-text": "of heart attacks occur in people with 'normal' cholesterol - ApoB and Lp(a) catch the risk standard panels miss",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>LDL was 112 - 'optimal.' But ApoB was 142 and Lp(a) was 188 nmol/L. hsCRP was 3.8 - active vascular inflammation. Three independent risk factors for plaque buildup that a standard lipid panel completely missed. Cardiologist ordered a calcium score - it was 180. Aggressive treatment started immediately.</p>",
        "featured-testimonial-name": "Greg S.",
        "featured-testimonial-result": "Triple atherosclerosis risk caught despite normal LDL",
        "membership-subheadline": "Track plaque risk biomarkers and prevent arterial disease",
        "membership-benefit-1": "ApoB, Lp(a), and hsCRP tested annually",
        "membership-benefit-2": "100+ biomarkers including metabolic markers",
        "membership-benefit-3": "AI calculates composite atherosclerosis risk",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ApoB, Lp(a), hsCRP, complete lipid panel (LDL, HDL, triglycerides, VLDL), homocysteine, fasting insulin, HbA1c, and liver enzymes - the atherosclerosis risk biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Atherosclerosis is caused by ApoB-containing particles penetrating artery walls and triggering plaque formation. ApoB counts these particles directly - more predictive than LDL concentration. Lp(a) is a genetic risk factor in 20% of people that accelerates plaque growth. hsCRP measures the vascular inflammation that destabilizes plaque.",
        "how-it-works-3-subheading": "Insulin resistance drives atherosclerosis by increasing small, dense LDL particles and triglycerides. We test metabolic markers alongside lipids because treating the metabolic root cause - not just prescribing statins - provides better long-term arterial protection.",
        "how-it-works-4-subheading": "Our clinical team explains your atherosclerosis risk profile and recommends next steps - aggressive lipid management, metabolic optimization, or cardiology referral for calcium scoring to directly assess existing plaque burden. Results in about 10 days.",
        "condition-name": "Atherosclerosis Biomarker Screening",
        "condition-overview": "<p>Atherosclerosis is the progressive buildup of plaque in artery walls - the underlying cause of most heart attacks and strokes. It develops silently over decades, driven by ApoB particles, genetic risk factors like Lp(a), chronic inflammation, and metabolic dysfunction. Blood biomarkers identify these risk factors long before plaque causes symptoms or events.</p>",
        "why-test": "<p>Standard cholesterol panels miss half the picture. ApoB is a better predictor of atherosclerosis than LDL. Lp(a) is a genetic risk factor that diet and exercise can't change - but knowing you have it enables aggressive prevention. hsCRP detects the inflammation that accelerates plaque growth. Together, these biomarkers assess atherosclerosis risk far more accurately than cholesterol alone.</p>",
        "what-is-included": "<p>Your panel includes ApoB, Lp(a), hsCRP, total cholesterol, LDL, HDL, triglycerides, VLDL, homocysteine, fasting insulin, HbA1c, fasting glucose, liver enzymes, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If atherosclerosis risk markers are elevated, our care team recommends targeted interventions - lipid management, anti-inflammatory strategies, metabolic optimization, and cardiology referral for coronary calcium scoring when appropriate.</p>",
        "meta-title": "Atherosclerosis Blood Test | ApoB + Lp(a) + CRP | Superpower",
        "meta-description": "Screen for atherosclerosis risk - ApoB, Lp(a), hsCRP, lipids. 50% of heart attacks have 'normal' cholesterol. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Atherosclerosis Blood Test | ApoB + Lp(a) + CRP | Superpower",
        "og-description": "Plaque builds for decades before symptoms. ApoB + Lp(a) + hsCRP + 100+ biomarkers. ~10 day results.",
    },
    "peripheral-artery-disease-biomarker-test": {
        "name": "Peripheral Artery Disease Biomarker Test",
        "hero-headline": "Leg Pain When Walking Could Be More Than 'Getting Older.' Your Blood Knows.",
        "hero-subheadline": "<p>Peripheral artery disease (PAD) narrows arteries in the legs, causing pain and increasing heart attack risk 4-6x. While PAD diagnosis requires ABI testing, blood biomarkers screen the lipid, inflammatory, and metabolic risk factors that drive it. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen PAD Risk Factors",
        "primary-keyword": "peripheral artery disease blood test",
        "secondary-keywords": "PAD blood test, peripheral artery disease biomarkers, PAD screening",
        "symptom-headline": "Signs that PAD risk factor testing is warranted",
        "symptom-1": "Leg pain or cramping when walking that stops with rest",
        "symptom-2": "Numbness or weakness in legs that's been getting worse",
        "symptom-3": "Wounds on feet or legs that heal slowly",
        "symptom-4": "One leg noticeably cooler or paler than the other",
        "symptom-5": "Smoking history, diabetes, or high cholesterol",
        "symptom-cta": "Screen the risk factors that drive PAD ->",
        "stat-1-number": "8.5M",
        "stat-1-text": "Americans have PAD - people with PAD are 4-6x more likely to have a heart attack or stroke",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Legs cramped every time I walked more than two blocks. Figured it was age. Superpower showed ApoB was 148, hsCRP was 5.1, HbA1c was 6.3 (prediabetes), and triglycerides were 240. Four risk factors for PAD. Vascular specialist confirmed it with ABI testing. Early treatment saved my legs.</p>",
        "featured-testimonial-name": "Frank M.",
        "featured-testimonial-result": "4 PAD risk factors identified - early vascular treatment started",
        "membership-subheadline": "Monitor vascular risk factors and prevent PAD progression",
        "membership-benefit-1": "Lipids, CRP, and metabolic markers annually",
        "membership-benefit-2": "100+ biomarkers including kidney function",
        "membership-benefit-3": "AI connects vascular risk factor patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ApoB, Lp(a), hsCRP, complete lipid panel, HbA1c, fasting glucose, fasting insulin, homocysteine, eGFR, creatinine, and CBC - the biomarkers that assess PAD risk factors - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "PAD is caused by the same atherosclerosis that causes heart attacks - just in the leg arteries instead of coronary arteries. Blood biomarkers assess the lipid, inflammatory, and metabolic drivers of this plaque buildup. While ABI (ankle-brachial index) testing directly diagnoses PAD, blood work identifies and quantifies the modifiable risk factors.",
        "how-it-works-3-subheading": "Diabetes, smoking, and dyslipidemia are the strongest PAD risk factors. HbA1c and fasting insulin screen for metabolic dysfunction. ApoB and lipids assess atherogenic burden. hsCRP and homocysteine measure vascular inflammation. Addressing these factors slows PAD progression and reduces heart attack risk.",
        "how-it-works-4-subheading": "Our clinical team explains your vascular risk profile, recommends lifestyle and medication interventions, and refers to vascular medicine for ABI testing and PAD-specific evaluation when indicated. Results in about 10 days.",
        "condition-name": "Peripheral Artery Disease Risk Screening",
        "condition-overview": "<p>Peripheral artery disease (PAD) affects 8.5 million Americans when atherosclerotic plaque narrows arteries supplying the legs. It causes leg pain when walking (claudication), poor wound healing, and dramatically increases heart attack and stroke risk. PAD shares the same risk factors as coronary artery disease - dyslipidemia, diabetes, inflammation, and smoking.</p>",
        "why-test": "<p>Blood biomarkers screen the modifiable risk factors that cause PAD - elevated ApoB, Lp(a), chronic inflammation (hsCRP), and metabolic dysfunction (insulin resistance, diabetes). While blood tests don't directly diagnose PAD (that requires ABI testing), they identify and quantify the drivers you can treat to prevent progression and reduce cardiovascular event risk.</p>",
        "what-is-included": "<p>Your panel includes ApoB, Lp(a), hsCRP, complete lipid panel, HbA1c, fasting glucose, fasting insulin, homocysteine, eGFR, creatinine, CBC, and liver enzymes - 100+ biomarkers total.</p>",
        "next-steps": "<p>If vascular risk factors are elevated, our care team recommends targeted treatment - lipid management, metabolic optimization, smoking cessation support - and refers to vascular medicine for ABI testing and PAD-specific evaluation.</p>",
        "meta-title": "PAD Blood Test | Vascular Risk Biomarkers | Superpower",
        "meta-description": "Screen PAD risk factors - lipids, ApoB, CRP, HbA1c. 8.5M Americans affected. 4-6x heart attack risk. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "PAD Blood Test | Vascular Risk Biomarkers | Superpower",
        "og-description": "Leg pain when walking? Screen vascular risk factors. Lipids + CRP + 100+ biomarkers. ~10 day results.",
    },
    "obesity-biomarker-test": {
        "name": "Obesity Biomarker Test",
        "hero-headline": "The Scale Shows Your Weight. Biomarkers Show What It's Doing to Your Body.",
        "hero-subheadline": "<p>Obesity drives insulin resistance, fatty liver, inflammation, thyroid dysfunction, and cardiovascular disease - often silently. Biomarkers reveal the metabolic damage happening beneath the surface so you can treat the consequences, not just the number on the scale. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Metabolic Health",
        "primary-keyword": "obesity blood test",
        "secondary-keywords": "obesity biomarkers, metabolic health blood test, weight-related blood test",
        "symptom-headline": "When metabolic testing is critical for weight management",
        "symptom-1": "Weight that won't budge despite diet and exercise efforts",
        "symptom-2": "Fatigue and brain fog that worsened with weight gain",
        "symptom-3": "Blood pressure or blood sugar creeping up over time",
        "symptom-4": "Family history of diabetes, heart disease, or fatty liver",
        "symptom-5": "Central obesity - weight concentrated around the midsection",
        "symptom-cta": "Find out what your weight is doing metabolically ->",
        "stat-1-number": "42%",
        "stat-1-text": "of American adults have obesity - but metabolic damage varies enormously and biomarkers reveal what the scale can't",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>BMI said obese. Doctor said lose weight. Superpower showed fasting insulin at 28, ALT at 54 (fatty liver), HbA1c at 5.9 (prediabetes), and thyroid antibodies at 340. Four metabolic problems driving my weight gain and making it almost impossible to lose. Treating the thyroid and insulin resistance first made everything else work.</p>",
        "featured-testimonial-name": "Denise W.",
        "featured-testimonial-result": "4 metabolic drivers of weight gain identified and treated",
        "membership-subheadline": "Track the metabolic impact of weight over time",
        "membership-benefit-1": "Insulin, glucose, liver, and thyroid annually",
        "membership-benefit-2": "100+ biomarkers including hormones and lipids",
        "membership-benefit-3": "AI tracks metabolic syndrome markers",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests fasting insulin, fasting glucose, HbA1c, liver enzymes (ALT, AST), complete lipid panel, thyroid panel with antibodies, CRP, uric acid, and CBC - the metabolic impact biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Obesity affects every organ system differently. Fasting insulin reveals insulin resistance years before diabetes develops. ALT and AST detect fatty liver disease. Thyroid dysfunction both causes and worsens weight gain. CRP measures the chronic inflammation that accelerates metabolic decline. Testing all of these paints the full metabolic picture.",
        "how-it-works-3-subheading": "Not all obesity carries the same metabolic risk. Some people with BMI over 30 have normal metabolic markers. Others with BMI of 28 have severe insulin resistance and fatty liver. Biomarkers reveal YOUR metabolic reality - not what the BMI chart predicts.",
        "how-it-works-4-subheading": "Our clinical team explains your metabolic profile, identifies which conditions are driving or resulting from weight gain, and recommends a targeted treatment plan - addressing insulin resistance, thyroid dysfunction, or fatty liver as the foundation for effective weight management. Results in about 10 days.",
        "condition-name": "Obesity Metabolic Screening",
        "condition-overview": "<p>Obesity affects 42% of American adults and significantly increases risk for type 2 diabetes, cardiovascular disease, fatty liver, and certain cancers. But the metabolic impact varies enormously - blood biomarkers reveal whether obesity has caused insulin resistance, liver damage, chronic inflammation, thyroid dysfunction, or lipid abnormalities in each individual.</p>",
        "why-test": "<p>The scale measures weight but not metabolic health. Fasting insulin detects insulin resistance years before HbA1c rises. Liver enzymes catch fatty liver before it progresses. Thyroid testing reveals whether dysfunction is driving weight gain. Lipids and CRP assess cardiovascular risk. Biomarker-guided treatment targets the root metabolic issues - making weight management more effective.</p>",
        "what-is-included": "<p>Your panel includes fasting insulin, fasting glucose, HbA1c, ALT, AST, GGT, complete lipid panel, thyroid panel with antibodies, CRP, uric acid, vitamin D, CBC, and complete metabolic panel - 100+ biomarkers total.</p>",
        "next-steps": "<p>If metabolic biomarkers are abnormal, our care team prioritizes treatment by impact - addressing insulin resistance, thyroid dysfunction, or fatty liver first. They recommend dietary strategies, medication discussion, and specialist referral as needed. Annual monitoring tracks metabolic improvement.</p>",
        "meta-title": "Obesity Blood Test | Metabolic Biomarkers | Superpower",
        "meta-description": "Test obesity's metabolic impact - insulin, liver, thyroid, lipids, CRP. 42% of adults affected. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Obesity Blood Test | Metabolic Biomarkers | Superpower",
        "og-description": "The scale shows weight. Biomarkers show metabolic damage. Insulin + liver + thyroid + 100+ markers. ~10 day results.",
    },
    "sleep-apnea-biomarker-test": {
        "name": "Sleep Apnea Biomarker Test",
        "hero-headline": "Exhausted, Gaining Weight, Blood Pressure Rising? It Might Not Be Aging.",
        "hero-subheadline": "<p>Sleep apnea can't be diagnosed by a blood test - it requires a sleep study. But blood biomarkers detect the metabolic consequences of untreated sleep apnea: polycythemia on CBC, insulin resistance, thyroid dysfunction, and elevated inflammation. These findings can be the red flag that leads to diagnosis. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Sleep Apnea-Related Biomarkers",
        "primary-keyword": "sleep apnea blood test",
        "secondary-keywords": "sleep apnea biomarkers, sleep apnea screening, OSA blood test",
        "symptom-headline": "Signs that sleep apnea may be affecting your health",
        "symptom-1": "Waking up exhausted no matter how long you sleep",
        "symptom-2": "Partner reports loud snoring or breathing pauses at night",
        "symptom-3": "Morning headaches and excessive daytime sleepiness",
        "symptom-4": "Weight gain and high blood pressure that won't respond to treatment",
        "symptom-5": "Brain fog and difficulty concentrating throughout the day",
        "symptom-cta": "Check the biomarkers sleep apnea affects ->",
        "stat-1-number": "30M",
        "stat-1-text": "Americans have obstructive sleep apnea - 80% are undiagnosed, and untreated OSA doubles cardiovascular risk",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Tired for years. Figured it was stress. Superpower showed hemoglobin at 18.2 (high - polycythemia), fasting insulin at 19, HbA1c at 5.8, and CRP at 4.6. Care team said these together are classic signs of untreated sleep apnea. Sleep study confirmed severe OSA. CPAP changed my life.</p>",
        "featured-testimonial-name": "Tony R.",
        "featured-testimonial-result": "Blood biomarkers flagged sleep apnea - confirmed by sleep study",
        "membership-subheadline": "Track the metabolic effects of sleep-related conditions",
        "membership-benefit-1": "CBC, insulin, and metabolic markers annually",
        "membership-benefit-2": "100+ biomarkers including thyroid and CRP",
        "membership-benefit-3": "AI flags sleep apnea-related patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests CBC with differential (hemoglobin, hematocrit, red blood cell count), fasting insulin, fasting glucose, HbA1c, thyroid panel, CRP, complete lipid panel, and liver enzymes - biomarkers that sleep apnea affects - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "A blood test cannot diagnose sleep apnea - only a sleep study can. However, untreated sleep apnea leaves metabolic fingerprints in your blood: elevated hemoglobin and hematocrit (the body compensating for low oxygen), insulin resistance, elevated CRP from chronic inflammation, and sometimes abnormal thyroid markers. These biomarkers can prompt the sleep study that leads to diagnosis.",
        "how-it-works-3-subheading": "Sleep apnea accelerates metabolic syndrome, hypertension, and cardiovascular disease. Testing insulin, glucose, lipids, and inflammatory markers alongside CBC reveals the cumulative metabolic damage from poor sleep. Treating sleep apnea often improves these markers significantly.",
        "how-it-works-4-subheading": "Our clinical team identifies patterns consistent with untreated sleep apnea and recommends a sleep study referral when appropriate. They also address any metabolic consequences detected on the panel. Results in about 10 days.",
        "condition-name": "Sleep Apnea-Related Biomarker Screening",
        "condition-overview": "<p>Obstructive sleep apnea (OSA) affects an estimated 30 million Americans, with 80% undiagnosed. While a blood test cannot diagnose sleep apnea (a sleep study is required), blood biomarkers detect the metabolic consequences of untreated OSA - polycythemia (elevated hemoglobin/hematocrit), insulin resistance, chronic inflammation, and metabolic syndrome. These findings often prompt the sleep study that leads to diagnosis.</p>",
        "why-test": "<p>Untreated sleep apnea causes measurable metabolic changes: elevated red blood cell counts (the body compensating for intermittent hypoxia), insulin resistance, chronic inflammation, and worsening lipid profiles. Blood biomarkers detect these changes and serve as evidence to pursue a sleep study. For those already diagnosed, annual testing tracks whether treatment is reversing metabolic damage.</p>",
        "what-is-included": "<p>Your panel includes CBC with differential (hemoglobin, hematocrit, RBC), fasting insulin, fasting glucose, HbA1c, CRP, thyroid panel, complete lipid panel, liver enzymes, and complete metabolic panel - 100+ biomarkers total.</p>",
        "next-steps": "<p>If biomarkers suggest untreated sleep apnea, our care team recommends a sleep study referral for definitive diagnosis. If already on CPAP or oral appliance therapy, annual biomarker monitoring tracks metabolic improvement and treatment effectiveness.</p>",
        "meta-title": "Sleep Apnea Blood Test | Metabolic Screening | Superpower",
        "meta-description": "Test biomarkers sleep apnea affects - CBC, insulin, CRP, thyroid. 30M Americans have OSA, 80% undiagnosed. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Sleep Apnea Blood Test | Metabolic Screening | Superpower",
        "og-description": "Sleep apnea leaves metabolic fingerprints. CBC + insulin + CRP + 100+ biomarkers. ~10 day results.",
    },
    "chronic-stress-biomarker-test": {
        "name": "Chronic Stress Biomarker Test",
        "hero-headline": "Stress Isn't Just in Your Head. It's Measurable in Your Blood.",
        "hero-subheadline": "<p>Chronic stress elevates cortisol, depletes DHEA, disrupts thyroid function, spikes glucose, and drives inflammation. These aren't feelings - they're measurable biomarkers. Testing reveals how stress is actually damaging your body. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Measure Your Stress Biomarkers",
        "primary-keyword": "chronic stress blood test",
        "secondary-keywords": "stress biomarkers, cortisol blood test, chronic stress screening",
        "symptom-headline": "Signs chronic stress is affecting your health",
        "symptom-1": "Exhaustion that no amount of rest seems to fix",
        "symptom-2": "Weight gain around the midsection despite eating well",
        "symptom-3": "Anxiety, irritability, or feeling on edge constantly",
        "symptom-4": "Getting sick more often than you used to",
        "symptom-5": "Brain fog, poor memory, and difficulty focusing",
        "symptom-cta": "Find out what stress is doing to your body ->",
        "stat-1-number": "75%",
        "stat-1-text": "of adults report moderate to high stress - chronic stress measurably disrupts cortisol, thyroid, glucose, and immune function",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Couldn't sleep, gaining weight, felt wired but exhausted. Cortisol was 24.8 (high), DHEA was tanked at 112, fasting glucose was 104, and thyroid was starting to struggle. Four years of chronic work stress - measurable in my blood. Addressing cortisol and DHEA first changed everything.</p>",
        "featured-testimonial-name": "Jessica N.",
        "featured-testimonial-result": "4 stress-affected biomarkers identified and addressed",
        "membership-subheadline": "Track how stress affects your body over time",
        "membership-benefit-1": "Cortisol, DHEA, and thyroid tested annually",
        "membership-benefit-2": "100+ biomarkers including glucose and CRP",
        "membership-benefit-3": "AI flags stress-related biomarker patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests cortisol, DHEA-S, complete thyroid panel, fasting glucose, fasting insulin, HbA1c, CRP, CBC with differential, vitamin D, B12, and iron studies - the biomarkers chronic stress disrupts - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Chronic stress measurably alters your blood chemistry. Sustained cortisol elevation drives insulin resistance, belly fat accumulation, and immune suppression. DHEA depletion (cortisol's counterbalance) worsens fatigue and recovery. Thyroid function slows under chronic stress, compounding weight gain and brain fog.",
        "how-it-works-3-subheading": "Stress also depletes nutrients - B12, vitamin D, and iron are commonly affected. Immune markers on CBC can show stress-related immune suppression. CRP rises from stress-driven inflammation. We test the complete picture because stress affects every system.",
        "how-it-works-4-subheading": "Our clinical team explains which biomarkers stress has impacted and recommends targeted interventions - cortisol management, DHEA support, thyroid optimization, and nutrient repletion. Results in about 10 days.",
        "condition-name": "Chronic Stress Biomarker Screening",
        "condition-overview": "<p>Chronic stress affects 75% of adults and produces measurable changes in blood biomarkers. Sustained cortisol elevation drives insulin resistance, immune suppression, thyroid dysfunction, and nutrient depletion. DHEA - cortisol's counterbalance - becomes depleted over time. Blood testing quantifies how stress is affecting your body rather than relying on subjective assessment.</p>",
        "why-test": "<p>Stress symptoms overlap with thyroid disease, depression, hormonal deficiency, and adrenal dysfunction. Blood biomarkers distinguish between these conditions and reveal the specific ways chronic stress is impacting your metabolism. Cortisol, DHEA, thyroid, glucose, and inflammatory markers together show the objective biological toll of stress - and guide targeted treatment.</p>",
        "what-is-included": "<p>Your panel includes cortisol, DHEA-S, complete thyroid panel with antibodies, fasting glucose, fasting insulin, HbA1c, CRP, CBC with differential, vitamin D, B12, ferritin, iron, and complete metabolic panel - 100+ biomarkers total.</p>",
        "next-steps": "<p>If stress-related biomarkers are disrupted, our care team recommends targeted interventions - cortisol management strategies, DHEA supplementation consideration, thyroid support, nutrient repletion, and referral for further evaluation when patterns suggest adrenal or endocrine disorders.</p>",
        "meta-title": "Chronic Stress Blood Test | Cortisol + DHEA | Superpower",
        "meta-description": "Measure how stress affects your body - cortisol, DHEA, thyroid, glucose, CRP. 75% of adults report high stress. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Chronic Stress Blood Test | Cortisol + DHEA | Superpower",
        "og-description": "Stress is measurable in your blood. Cortisol + DHEA + thyroid + 100+ biomarkers. ~10 day results.",
    },
    "cirrhosis-biomarker-test": {
        "name": "Cirrhosis Biomarker Test",
        "hero-headline": "Your Liver Can Be Scarring for Years Without a Single Symptom. Blood Tests Catch It.",
        "hero-subheadline": "<p>Cirrhosis - permanent liver scarring - develops silently from fatty liver, alcohol use, or hepatitis. Liver enzymes, albumin, platelets, and metabolic markers screen for liver damage before it becomes irreversible. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen Your Liver Health",
        "primary-keyword": "cirrhosis blood test",
        "secondary-keywords": "cirrhosis biomarkers, liver cirrhosis screening, liver scarring blood test",
        "symptom-headline": "Risk factors that warrant liver screening",
        "symptom-1": "History of heavy alcohol use - even if you've cut back",
        "symptom-2": "Non-alcoholic fatty liver disease or elevated liver enzymes",
        "symptom-3": "Chronic hepatitis B or C infection",
        "symptom-4": "Unexplained fatigue, easy bruising, or abdominal swelling",
        "symptom-5": "Obesity or diabetes - both increase fatty liver and cirrhosis risk",
        "symptom-cta": "Check your liver for signs of damage ->",
        "stat-1-number": "4.5M",
        "stat-1-text": "Americans have liver cirrhosis - most don't know it until complications develop because the liver compensates until it can't",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Social drinker for 20 years, never thought much of it. Superpower showed ALT at 68, AST at 72, albumin low at 3.2, and platelets dropping at 132. Classic early cirrhosis pattern. Ultrasound confirmed scarring. Stopped drinking completely and started monitoring. Blood tests caught it before I ever had a symptom.</p>",
        "featured-testimonial-name": "Kevin B.",
        "featured-testimonial-result": "Early cirrhosis caught on routine blood work - no symptoms",
        "membership-subheadline": "Monitor liver health and catch damage early",
        "membership-benefit-1": "Liver enzymes, albumin, and platelets annually",
        "membership-benefit-2": "100+ biomarkers including metabolic panel",
        "membership-benefit-3": "AI flags liver damage patterns early",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ALT, AST, ALP, GGT, albumin, total protein, bilirubin, CBC with platelets, complete metabolic panel, CRP, and lipid panel - the liver screening biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Cirrhosis develops in stages. Early on, ALT and AST are elevated from ongoing liver inflammation. As scarring progresses, albumin drops (the liver can't produce enough protein), platelets fall (the scarred liver traps them), and bilirubin rises. We test all of these to assess liver health comprehensively.",
        "how-it-works-3-subheading": "The AST-to-platelet ratio (APRI) and FIB-4 score - calculated from your blood results - estimate liver fibrosis without a biopsy. These validated scores help determine whether imaging or specialist referral is needed. Our panel provides all the inputs for these calculations.",
        "how-it-works-4-subheading": "Our clinical team explains your liver biomarkers, calculates fibrosis risk scores, and recommends hepatology referral for imaging or further evaluation when indicated. Results in about 10 days.",
        "condition-name": "Cirrhosis Biomarker Screening",
        "condition-overview": "<p>Cirrhosis is permanent scarring of the liver that develops over years from fatty liver disease, chronic alcohol use, or hepatitis. It affects 4.5 million Americans, and most are undiagnosed because the liver compensates for damage until late stages. Blood biomarkers - liver enzymes, albumin, platelets, and bilirubin - screen for liver damage and estimate fibrosis severity.</p>",
        "why-test": "<p>The liver compensates for extraordinary damage before symptoms appear. Blood biomarkers detect the progressive changes of cirrhosis: rising AST and ALT from inflammation, falling albumin from reduced protein production, dropping platelets from portal hypertension, and rising bilirubin from impaired bile processing. Early detection allows intervention before irreversible complications develop.</p>",
        "what-is-included": "<p>Your panel includes ALT, AST, ALP, GGT, albumin, total protein, bilirubin (total and direct), CBC with platelets, complete metabolic panel, CRP, lipid panel, and fasting glucose - 100+ biomarkers total.</p>",
        "next-steps": "<p>If liver biomarkers suggest fibrosis or cirrhosis, our care team calculates APRI and FIB-4 scores and recommends hepatology referral for imaging (FibroScan or ultrasound). They guide lifestyle modifications, alcohol cessation, and metabolic optimization to slow or halt progression.</p>",
        "meta-title": "Cirrhosis Blood Test | Liver Screening | Superpower",
        "meta-description": "Screen for liver cirrhosis - ALT, AST, albumin, platelets, bilirubin. 4.5M Americans affected. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Cirrhosis Blood Test | Liver Screening | Superpower",
        "og-description": "Liver scarring is silent for years. Screen with liver enzymes + albumin + 100+ biomarkers. ~10 day results.",
    },
    "hepatitis-biomarker-test": {
        "name": "Hepatitis Biomarker Test",
        "hero-headline": "Hepatitis Can Hide in Your Liver for Decades. Your Liver Enzymes Sound the Alarm.",
        "hero-subheadline": "<p>Chronic hepatitis silently damages your liver for years before symptoms appear. Liver enzymes (ALT, AST) are often the first indication something is wrong. While hepatitis-specific serologies (HBsAg, HCV antibody) may require a separate order, our panel flags the liver damage that prompts testing. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen Your Liver Enzymes",
        "primary-keyword": "hepatitis blood test",
        "secondary-keywords": "hepatitis biomarkers, liver enzyme test hepatitis, hepatitis screening",
        "symptom-headline": "When hepatitis screening matters",
        "symptom-1": "Unexplained fatigue that's persisted for months",
        "symptom-2": "Yellowing of skin or eyes - even slightly",
        "symptom-3": "Dark urine or pale stools you can't explain",
        "symptom-4": "Born between 1945-1965 - the hepatitis C generation",
        "symptom-5": "History of blood transfusion before 1992 or IV drug use",
        "symptom-cta": "Check your liver enzymes for signs of hepatitis ->",
        "stat-1-number": "3.3M",
        "stat-1-text": "Americans live with chronic hepatitis B or C - over half don't know it because the liver compensates for years",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>No symptoms at all. Superpower flagged ALT at 78 and AST at 64 - both elevated. Care team recommended hepatitis screening. Turns out I had chronic hepatitis C - probably from a blood transfusion in the 80s. Cured in 12 weeks with antivirals. Would never have known without that blood test.</p>",
        "featured-testimonial-name": "Richard A.",
        "featured-testimonial-result": "Chronic hepatitis C discovered via elevated liver enzymes - cured",
        "membership-subheadline": "Monitor liver health and catch hepatitis early",
        "membership-benefit-1": "Liver enzymes and function markers annually",
        "membership-benefit-2": "100+ biomarkers including CBC and metabolic",
        "membership-benefit-3": "AI flags liver inflammation patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ALT, AST, ALP, GGT, albumin, bilirubin, total protein, CBC with differential, complete metabolic panel, CRP, and iron studies - the liver health biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Chronic hepatitis B and C cause persistent liver inflammation that elevates ALT and AST - often the first detectable sign. Our panel tests these liver enzymes along with albumin, bilirubin, and platelets that assess overall liver function. Important: hepatitis-specific antibody tests (HBsAg, anti-HCV) may not be included in the standard panel. If liver enzymes are elevated, our care team recommends hepatitis-specific serologies.",
        "how-it-works-3-subheading": "Iron overload (elevated ferritin and iron saturation) can accompany chronic hepatitis and worsen liver damage. CBC may show low platelets in advancing liver disease. CRP measures the inflammatory burden. We test these alongside liver enzymes to assess the complete liver health picture.",
        "how-it-works-4-subheading": "Our clinical team reviews your liver enzyme results and recommends hepatitis-specific testing if patterns suggest viral hepatitis. They also assess liver function severity and refer to hepatology when indicated. Results in about 10 days.",
        "condition-name": "Hepatitis-Related Biomarker Screening",
        "condition-overview": "<p>Chronic hepatitis (B and C) affects over 3.3 million Americans, with more than half undiagnosed. The viruses silently damage the liver for decades, causing cirrhosis and liver cancer if untreated. Elevated liver enzymes (ALT, AST) are often the first blood test abnormality that prompts hepatitis-specific screening. Hepatitis C is now curable in over 95% of cases with antiviral treatment.</p>",
        "why-test": "<p>Liver enzymes (ALT, AST) are often the first signal of chronic hepatitis - elevated long before symptoms appear. Our panel screens liver function comprehensively. If results suggest hepatitis, specific serological testing (HBsAg for hepatitis B, anti-HCV for hepatitis C) confirms the diagnosis. Early detection of hepatitis C is especially critical because it's now curable with short-course antiviral therapy.</p>",
        "what-is-included": "<p>Your panel includes ALT, AST, ALP, GGT, albumin, total protein, bilirubin, CBC with differential and platelets, complete metabolic panel, CRP, ferritin, iron, and TIBC - 100+ biomarkers total. Note: Hepatitis-specific serologies (HBsAg, anti-HCV) may require a separate order if liver enzymes are elevated.</p>",
        "next-steps": "<p>If liver enzymes are elevated, our care team recommends hepatitis-specific serological testing and hepatology referral. If hepatitis is confirmed, modern treatments - especially for hepatitis C - cure over 95% of cases. Annual monitoring tracks liver health for those with chronic hepatitis B.</p>",
        "meta-title": "Hepatitis Blood Test | Liver Enzyme Screening | Superpower",
        "meta-description": "Screen for hepatitis - liver enzymes, albumin, bilirubin, CBC. 3.3M Americans have chronic hepatitis. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Hepatitis Blood Test | Liver Enzyme Screening | Superpower",
        "og-description": "Hepatitis hides for decades. Liver enzymes catch it first. ALT + AST + 100+ biomarkers. ~10 day results.",
    },
    "ibd-biomarker-test": {
        "name": "IBD Biomarker Test",
        "hero-headline": "Cramps, Bloody Stool, and Fatigue for Months? It Could Be More Than IBS.",
        "hero-subheadline": "<p>Inflammatory bowel disease (Crohn's and ulcerative colitis) causes chronic intestinal inflammation that blood biomarkers can detect. CRP, CBC, iron studies, and albumin screen for the inflammation and nutrient deficiencies that distinguish IBD from IBS. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen for IBD Biomarkers",
        "primary-keyword": "IBD blood test",
        "secondary-keywords": "inflammatory bowel disease blood test, Crohn's disease biomarkers, ulcerative colitis blood test",
        "symptom-headline": "Signs that warrant IBD biomarker screening",
        "symptom-1": "Persistent diarrhea lasting more than 4 weeks",
        "symptom-2": "Blood in stool or rectal bleeding",
        "symptom-3": "Abdominal pain and cramping that comes in flares",
        "symptom-4": "Unexplained weight loss and declining appetite",
        "symptom-5": "Fatigue and anemia that iron supplements don't fix",
        "symptom-cta": "Find out if it's IBD or something else ->",
        "stat-1-number": "3M",
        "stat-1-text": "Americans have IBD - diagnosis takes an average of 2+ years because symptoms overlap with IBS and other conditions",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Two years of cramps and diarrhea. Doctor said IBS, eat more fiber. Superpower showed CRP at 12.4, ferritin at 8, hemoglobin at 10.8, and albumin at 3.1. Classic IBD pattern. Gastroenterologist confirmed Crohn's with colonoscopy within 3 weeks. Two years of misdiagnosis ended with one blood test.</p>",
        "featured-testimonial-name": "Megan F.",
        "featured-testimonial-result": "Crohn's disease diagnosed after 2 years of IBS misdiagnosis",
        "membership-subheadline": "Screen for IBD and track inflammation over time",
        "membership-benefit-1": "CRP, CBC, and iron studies tested annually",
        "membership-benefit-2": "100+ biomarkers including albumin and liver",
        "membership-benefit-3": "AI flags IBD-related inflammatory patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests CRP, CBC with differential, ferritin, iron, TIBC, albumin, total protein, complete metabolic panel, B12, folate, and vitamin D - the biomarkers IBD affects - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "IBD causes systemic inflammation that elevates CRP - a key differentiator from IBS (which typically has normal CRP). CBC often shows anemia from chronic blood loss and iron deficiency. Low albumin indicates protein loss from inflamed intestines. These biomarkers together create a pattern that strongly suggests IBD and warrants colonoscopy.",
        "how-it-works-3-subheading": "IBD causes significant nutrient deficiencies through malabsorption and chronic bleeding. Iron, B12, folate, and vitamin D are commonly depleted. We test these alongside inflammatory markers because treating deficiencies is critical for symptom management and preventing complications like osteoporosis and severe anemia.",
        "how-it-works-4-subheading": "Our clinical team identifies IBD-suggestive biomarker patterns and recommends gastroenterology referral for colonoscopy when appropriate. They also address any nutrient deficiencies detected on the panel. Results in about 10 days.",
        "condition-name": "IBD Biomarker Screening",
        "condition-overview": "<p>Inflammatory bowel disease - Crohn's disease and ulcerative colitis - affects 3 million Americans. IBD causes chronic intestinal inflammation leading to diarrhea, bleeding, pain, and malnutrition. Diagnosis takes an average of 2+ years because symptoms overlap with IBS. Blood biomarkers - CRP, CBC, iron studies, and albumin - screen for the inflammation and nutrient deficiencies that distinguish IBD from functional bowel disorders.</p>",
        "why-test": "<p>Blood biomarkers help distinguish IBD from IBS and other conditions. Elevated CRP signals active inflammation (IBS has normal CRP). Anemia and low ferritin suggest chronic blood loss. Low albumin indicates intestinal protein loss. Together, these findings build a strong case for colonoscopy referral - potentially shortening the average 2+ year diagnostic delay significantly.</p>",
        "what-is-included": "<p>Your panel includes CRP, CBC with differential, ferritin, serum iron, TIBC, albumin, total protein, B12, folate, vitamin D, complete metabolic panel, and liver enzymes - 100+ biomarkers total.</p>",
        "next-steps": "<p>If biomarkers suggest IBD, our care team recommends gastroenterology referral for colonoscopy and definitive diagnosis. They also treat nutrient deficiencies (iron, B12, vitamin D) and provide ongoing monitoring for those with established IBD to track disease activity.</p>",
        "meta-title": "IBD Blood Test | Crohn's & Colitis Screening | Superpower",
        "meta-description": "Screen for IBD - CRP, CBC, iron, albumin. Distinguish Crohn's/colitis from IBS. 3M Americans affected. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "IBD Blood Test | Crohn's & Colitis Screening | Superpower",
        "og-description": "Is it IBD or IBS? CRP + CBC + iron + albumin + 100+ biomarkers tell the difference. ~10 day results.",
    },
    "prostate-cancer-biomarker-test": {
        "name": "Prostate Cancer Biomarker Test",
        "hero-headline": "Prostate Cancer Has Zero Symptoms in Early Stages. PSA Catches It When Treatment Works Best.",
        "hero-subheadline": "<p>PSA (prostate-specific antigen) is the only blood test that screens for prostate cancer before symptoms develop. Superpower includes PSA in the male biomarker panel. Early detection through PSA screening saves lives - but it's a screening tool, not a diagnosis. Elevated PSA warrants follow-up, not panic. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Get Your PSA Screened",
        "primary-keyword": "prostate cancer blood test",
        "secondary-keywords": "PSA blood test, prostate cancer screening, PSA test",
        "symptom-headline": "When prostate cancer screening is important",
        "symptom-1": "Over 50 - age is the strongest risk factor for prostate cancer",
        "symptom-2": "Family history of prostate cancer - especially father or brother",
        "symptom-3": "African American men - 2x higher incidence and earlier onset",
        "symptom-4": "Difficulty urinating, weak stream, or frequent nighttime urination",
        "symptom-5": "Never had a PSA test - most men haven't been screened",
        "symptom-cta": "Get your PSA level checked now ->",
        "stat-1-number": "1 in 8",
        "stat-1-text": "men will be diagnosed with prostate cancer - early detection via PSA screening improves 5-year survival to nearly 100%",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>No symptoms. Zero. PSA came back at 5.8 on my Superpower panel. Urologist did a biopsy - Gleason 6, early stage. Active surveillance now with PSA monitoring every 6 months. Caught it at the most treatable stage because a blood test flagged it. Every man over 50 should know his PSA.</p>",
        "featured-testimonial-name": "Paul J.",
        "featured-testimonial-result": "Early-stage prostate cancer detected via PSA - treatable",
        "membership-subheadline": "Track PSA and prostate health biomarkers over time",
        "membership-benefit-1": "PSA included in every male panel",
        "membership-benefit-2": "100+ biomarkers including testosterone and CRP",
        "membership-benefit-3": "AI tracks PSA velocity over time",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests PSA (prostate-specific antigen), testosterone, CBC, complete metabolic panel, CRP, vitamin D, lipid panel, and liver enzymes - plus 90+ other biomarkers. Superpower includes PSA in the male panel. $199/year.",
        "how-it-works-2-subheading": "PSA is a screening tool - not a diagnostic test. Elevated PSA (typically above 4.0 ng/mL) can indicate prostate cancer, but also benign prostatic hyperplasia (BPH) or prostatitis. PSA velocity (how fast it rises over time) is often more informative than a single value. Annual monitoring establishes your baseline and tracks changes.",
        "how-it-works-3-subheading": "Prostate cancer screening is most beneficial for men 50-70 (or 45+ for African American men and those with family history). We include PSA alongside testosterone, which can affect prostate growth, and metabolic markers that inform overall cancer risk. The decision to screen should be informed, not skipped.",
        "how-it-works-4-subheading": "If PSA is elevated, our clinical team explains what the number means in context - age, prostate size, and rate of change all matter. They recommend urology referral for further evaluation when appropriate. Results in about 10 days.",
        "condition-name": "Prostate Cancer PSA Screening",
        "condition-overview": "<p>Prostate cancer affects 1 in 8 men and is the second leading cancer killer of men in the US. In early stages, it produces zero symptoms. PSA (prostate-specific antigen) is the only blood screening test available, and early detection improves 5-year survival to nearly 100%. PSA is a screening tool - elevated levels require follow-up evaluation, not immediate alarm.</p>",
        "why-test": "<p>PSA screening catches prostate cancer when it's most treatable - before symptoms ever develop. Superpower includes PSA in the male biomarker panel. While PSA isn't perfect (it can be elevated from non-cancerous causes), tracking your PSA over time provides the most valuable screening data. PSA velocity - how quickly your level rises - is often more informative than any single reading.</p>",
        "what-is-included": "<p>Your panel includes PSA, total testosterone, free testosterone, CBC with differential, complete metabolic panel, CRP, vitamin D, lipid panel, liver enzymes, and kidney function - 100+ biomarkers total.</p>",
        "next-steps": "<p>If PSA is elevated or rising, our care team explains the finding in context and recommends urology referral for further evaluation (which may include repeat PSA, free PSA ratio, MRI, or biopsy). Annual PSA monitoring establishes your baseline for meaningful trend tracking.</p>",
        "meta-title": "Prostate Cancer Test | PSA Screening | Superpower",
        "meta-description": "PSA screening for prostate cancer - included in Superpower's male panel. 1 in 8 men affected. Early detection saves lives. 100+ biomarkers. $199/year.",
        "og-title": "Prostate Cancer Test | PSA Screening | Superpower",
        "og-description": "Prostate cancer has zero early symptoms. PSA catches it. Included in 100+ biomarker panel. ~10 day results.",
    },
    "chronic-infection-biomarker-test": {
        "name": "Chronic Infection Biomarker Test",
        "hero-headline": "Fatigue, Inflammation, and Feeling Off for Months? Your Blood May Show Why.",
        "hero-subheadline": "<p>Chronic infections - viral, bacterial, or parasitic - cause persistent inflammation, immune activation, and nutrient depletion that blood biomarkers can detect. CBC, CRP, and metabolic markers screen for the telltale signs of ongoing infection. These are screening markers - specific infection identification requires targeted testing. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen for Chronic Infection Markers",
        "primary-keyword": "chronic infection blood test",
        "secondary-keywords": "chronic infection biomarkers, infection screening blood test, persistent infection test",
        "symptom-headline": "Signs that chronic infection may be present",
        "symptom-1": "Fatigue and malaise that's lasted weeks or months",
        "symptom-2": "Low-grade fevers that come and go without explanation",
        "symptom-3": "Unexplained weight loss or poor appetite",
        "symptom-4": "Joint pain, rashes, or night sweats without clear cause",
        "symptom-5": "Elevated white blood cells or CRP on previous blood work",
        "symptom-cta": "Check if chronic infection is behind your symptoms ->",
        "stat-1-number": "Millions",
        "stat-1-text": "of Americans have undiagnosed chronic infections - from Lyme to EBV reactivation to dental infections - detectable through blood screening markers",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Exhausted for 8 months. Doctor couldn't find anything wrong. Superpower showed WBC elevated at 12,800, CRP at 6.2, ferritin spiked at 420, and ESR was high. Classic chronic infection pattern. Infectious disease specialist traced it to a dental abscess I didn't even know I had. Six weeks of antibiotics and I felt human again.</p>",
        "featured-testimonial-name": "Chris D.",
        "featured-testimonial-result": "Hidden dental infection found via blood screening markers",
        "membership-subheadline": "Screen for infection markers and track immune health",
        "membership-benefit-1": "CBC, CRP, and immune markers tested annually",
        "membership-benefit-2": "100+ biomarkers including iron and metabolic",
        "membership-benefit-3": "AI flags chronic infection patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests CBC with differential (white blood cell count and subtypes), CRP, ferritin, iron studies, albumin, total protein, complete metabolic panel, liver enzymes, and thyroid panel - the biomarkers chronic infections disrupt - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Chronic infections trigger specific blood biomarker patterns: elevated WBC or abnormal differential (neutrophilia suggests bacterial, lymphocytosis suggests viral), elevated CRP and ferritin from inflammation, low albumin from chronic immune activation, and anemia of chronic disease. These screening markers suggest ongoing infection even when the source isn't obvious.",
        "how-it-works-3-subheading": "Important: our panel provides screening markers - elevated CRP and WBC indicate inflammation and immune activation but don't identify the specific pathogen. If patterns suggest chronic infection, targeted testing (Lyme antibodies, EBV panel, blood cultures) identifies the cause. Our panel determines WHETHER you need that specialized testing.",
        "how-it-works-4-subheading": "Our clinical team identifies chronic infection patterns in your biomarkers and recommends infectious disease referral or targeted pathogen testing when indicated. They also address secondary effects like anemia and nutrient depletion. Results in about 10 days.",
        "condition-name": "Chronic Infection Biomarker Screening",
        "condition-overview": "<p>Chronic infections - including reactivated EBV, chronic Lyme, occult dental infections, and others - cause persistent immune activation, inflammation, and metabolic disruption. Blood biomarkers like CBC with differential, CRP, ferritin, and albumin screen for these patterns. These are screening markers that suggest ongoing infection and guide targeted pathogen-specific testing.</p>",
        "why-test": "<p>Chronic infections are notoriously difficult to diagnose because symptoms are vague - fatigue, malaise, joint pain, low-grade fevers. Blood biomarkers provide objective evidence of immune activation and inflammation. Elevated WBC, high CRP, spiked ferritin, and low albumin together create a pattern that points toward chronic infection and away from other causes of fatigue. This screening step determines whether pathogen-specific testing is warranted.</p>",
        "what-is-included": "<p>Your panel includes CBC with differential (WBC, neutrophils, lymphocytes, monocytes), CRP, ferritin, serum iron, TIBC, albumin, total protein, complete metabolic panel, liver enzymes, and thyroid panel - 100+ biomarkers total.</p>",
        "next-steps": "<p>If biomarkers suggest chronic infection, our care team recommends infectious disease referral or specific pathogen testing based on the biomarker pattern. They also address secondary effects - anemia, nutrient depletion, and metabolic disruption - while the infection source is investigated.</p>",
        "meta-title": "Chronic Infection Blood Test | CBC + CRP Screen | Superpower",
        "meta-description": "Screen for chronic infection - CBC, CRP, ferritin, albumin. Detect immune activation and inflammation. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Chronic Infection Blood Test | CBC + CRP Screen | Superpower",
        "og-description": "Fatigue for months? Screen for chronic infection markers. CBC + CRP + 100+ biomarkers. ~10 day results.",
    },
}


def fetch_all_pages():
    all_items = []
    offset = 0
    while True:
        url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items?limit=100&offset={offset}"
        resp = requests.get(url, headers=HEADERS)
        data = resp.json()
        items = data.get("items", [])
        all_items.extend(items)
        total = data.get("pagination", {}).get("total", 0)
        if offset + 100 >= total:
            break
        offset += 100
        time.sleep(0.3)
    return all_items


def main():
    print("=" * 70)
    print("BATCH 4: Rewrite 13 Tier 2 Biomarker-Test Pages")
    print("=" * 70)

    print("\nFetching all pages...")
    all_items = fetch_all_pages()
    slug_map = {}
    for item in all_items:
        slug = item.get("fieldData", {}).get("slug", "")
        if slug:
            slug_map[slug] = item

    results = []
    for slug, fields in REWRITES.items():
        if slug not in slug_map:
            print(f"\n  SKIP: {slug} not found")
            results.append({"slug": slug, "status": "NOT_FOUND"})
            continue

        item_id = slug_map[slug]["id"]
        print(f"\n  REWRITING: {slug}")

        url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items/{item_id}"
        resp = requests.patch(url, headers=HEADERS, json={"fieldData": fields})
        if resp.status_code == 200:
            print(f"    Updated: {fields['meta-title']}")
            results.append({"slug": slug, "item_id": item_id, "status": "UPDATED", "meta_title": fields["meta-title"]})
        else:
            print(f"    ERROR: {resp.status_code} {resp.text[:200]}")
            results.append({"slug": slug, "item_id": item_id, "status": "ERROR"})
        time.sleep(0.4)

    updated_ids = [r["item_id"] for r in results if r["status"] == "UPDATED"]
    if updated_ids:
        print(f"\nPublishing {len(updated_ids)} pages...")
        for i in range(0, len(updated_ids), 100):
            batch = updated_ids[i:i+100]
            url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items/publish"
            resp = requests.post(url, headers=HEADERS, json={"itemIds": batch})
            print(f"  Publish: {resp.status_code}")

    print(f"\n{'=' * 70}")
    print("SUMMARY")
    for r in results:
        print(f"  {r['slug']}: {r['status']}")

    with open("/Users/jeffy/superpower-sem-gap/app/data/biomarker_rewrite_batch4.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nSaved to biomarker_rewrite_batch4.json")


if __name__ == "__main__":
    main()
