#!/usr/bin/env python3
"""Batch 2: Rewrite 12 Tier 1 biomarker-test pages (with SEM overlap) - Part A.
Thyroid conditions, metabolic conditions, vitamin deficiencies."""
import requests
import time
import json

API_KEY = "87be5982f1938a9143a7368af984a9863971dd55314fd5a60f482cc02425a0c7"
LP_COLLECTION = "6981a714e199bac70776d880"
HEADERS = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}

REWRITES = {
    "hashimotos-biomarker-test": {
        "name": "Hashimoto's Biomarker Test",
        "hero-headline": "Your TSH Is Normal. Your Antibodies Are 500+. That's Hashimoto's.",
        "hero-subheadline": "<p>Hashimoto's thyroiditis attacks your thyroid for years before TSH goes abnormal. The only way to catch it early is testing thyroid antibodies - TPO and thyroglobulin. Most doctors don't order them. We do. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test for Hashimoto's Antibodies",
        "primary-keyword": "hashimoto's blood test",
        "secondary-keywords": "hashimoto's biomarkers, thyroid antibody test, hashimoto's thyroiditis test",
        "symptom-headline": "When Hashimoto's hides behind 'normal' thyroid tests",
        "symptom-1": "Fatigue, weight gain, and brain fog with a normal TSH",
        "symptom-2": "Hair loss that started gradually and keeps getting worse",
        "symptom-3": "Family history of thyroid disease or autoimmune conditions",
        "symptom-4": "Feeling cold all the time even when others are comfortable",
        "symptom-5": "Thyroid symptoms that come and go unpredictably",
        "symptom-cta": "Find out if thyroid antibodies tell the real story ->",
        "stat-1-number": "14M",
        "stat-1-text": "Americans have Hashimoto's - most are undiagnosed because doctors only test TSH, not antibodies",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>TSH was 3.2 - 'perfectly normal.' But my TPO antibodies were 547. Hashimoto's was destroying my thyroid for years and nobody tested antibodies. Finally got treatment and the fatigue, weight gain, and hair loss started reversing within months.</p>",
        "featured-testimonial-name": "Karen H.",
        "featured-testimonial-result": "Hashimoto's caught via antibodies despite normal TSH",
        "membership-subheadline": "Catch Hashimoto's before your thyroid fails",
        "membership-benefit-1": "Thyroid antibodies plus full thyroid panel",
        "membership-benefit-2": "100+ biomarkers including iron and vitamin D",
        "membership-benefit-3": "AI tracks antibody trends over time",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests TPO antibodies, thyroglobulin antibodies, TSH, Free T4, T3, plus ferritin, vitamin D, B12, cortisol, and 90+ other biomarkers. Hashimoto's antibodies are the early warning that standard thyroid panels miss. $199/year.",
        "how-it-works-2-subheading": "Hashimoto's is autoimmune - your immune system attacks thyroid tissue over years. Antibodies rise first, then TSH slowly creeps up, and T4 eventually drops. By the time TSH is abnormal, significant thyroid damage has occurred. Antibody testing catches it at the earliest stage.",
        "how-it-works-3-subheading": "Iron, vitamin D, and selenium all affect Hashimoto's progression. Low ferritin impairs thyroid hormone conversion. Vitamin D deficiency worsens autoimmune activity. We test these alongside thyroid markers to address all contributing factors.",
        "how-it-works-4-subheading": "Our clinical team explains your thyroid and antibody results in context. If Hashimoto's is detected, they recommend endocrinologist referral and lifestyle interventions shown to reduce antibody levels. Results in about 10 days.",
        "condition-name": "Hashimoto's Thyroiditis Screening",
        "condition-overview": "<p>Hashimoto's thyroiditis is the most common autoimmune disease and the leading cause of hypothyroidism. The immune system produces antibodies (TPO and thyroglobulin) that gradually destroy thyroid tissue. This process can take years, during which TSH may remain normal while antibodies are highly elevated. Up to 14 million Americans have Hashimoto's.</p>",
        "why-test": "<p>Standard thyroid tests (TSH only) miss early Hashimoto's entirely. Thyroid antibodies can be elevated for 5-10 years before TSH becomes abnormal. By then, significant thyroid damage has occurred. Testing TPO and thyroglobulin antibodies is the only way to detect Hashimoto's at its earliest, most manageable stage.</p>",
        "what-is-included": "<p>Your panel includes TPO antibodies, thyroglobulin antibodies, TSH, Free T4, T3, ferritin, vitamin D, B12, CRP, cortisol, complete metabolic panel, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If thyroid antibodies are positive, our care team explains the significance and recommends next steps - endocrinologist referral, selenium supplementation, vitamin D optimization, and dietary considerations. Annual retesting tracks whether antibody levels are stable, rising, or improving with intervention.</p>",
        "meta-title": "Hashimoto's Blood Test | Thyroid Antibodies | Superpower",
        "meta-description": "Test for Hashimoto's with thyroid antibodies (TPO, thyroglobulin). Catches it years before TSH goes abnormal. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Hashimoto's Blood Test | Thyroid Antibodies | Superpower",
        "og-description": "Catch Hashimoto's before TSH goes abnormal. Thyroid antibodies + 100+ biomarkers. ~10 day results.",
    },
    "hypothyroidism-biomarker-test": {
        "name": "Hypothyroidism Biomarker Test",
        "hero-headline": "Your Doctor Tests TSH. That's 1 of 7 Thyroid Markers. We Test All 7.",
        "hero-subheadline": "<p>TSH alone misses subclinical hypothyroidism, Hashimoto's thyroiditis, and T4-to-T3 conversion problems. A complete thyroid panel - TSH, Free T4, T3, and antibodies - gives you the full picture of why you feel exhausted. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Get the Complete Thyroid Panel",
        "primary-keyword": "hypothyroidism blood test",
        "secondary-keywords": "hypothyroidism biomarkers, underactive thyroid test, thyroid panel blood test",
        "symptom-headline": "Hypothyroidism symptoms your doctor dismisses",
        "symptom-1": "Exhaustion that doesn't improve with more sleep",
        "symptom-2": "Unexplained weight gain of 10-20+ pounds",
        "symptom-3": "Feeling cold - wearing layers when no one else needs to",
        "symptom-4": "Brain fog and difficulty concentrating on simple tasks",
        "symptom-5": "Dry skin, brittle nails, and thinning hair",
        "symptom-cta": "Get the thyroid test that actually gives answers ->",
        "stat-1-number": "60%",
        "stat-1-text": "of people with thyroid disease don't know they have it - TSH alone misses the early stages",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>My TSH was 3.5 - 'normal.' But my Free T3 was rock bottom and my TPO antibodies were 420. I had Hashimoto's causing hypothyroid symptoms that a TSH-only test completely missed. Proper treatment changed my life.</p>",
        "featured-testimonial-name": "Amy S.",
        "featured-testimonial-result": "Hypothyroidism diagnosed despite 'normal' TSH",
        "membership-subheadline": "Track all thyroid markers - not just TSH",
        "membership-benefit-1": "Full thyroid panel with antibodies annually",
        "membership-benefit-2": "100+ biomarkers including iron and vitamin D",
        "membership-benefit-3": "AI catches subtle thyroid trends early",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests TSH, Free T4, T3, TPO antibodies, and thyroglobulin antibodies - your complete thyroid panel - plus ferritin, vitamin D, B12, cortisol, and 90+ other biomarkers. $199/year.",
        "how-it-works-2-subheading": "Hypothyroidism has multiple causes and TSH alone doesn't distinguish them. Hashimoto's (autoimmune), iodine deficiency, pituitary problems, and T4-to-T3 conversion issues all present differently. The full panel identifies which type you have so treatment can be targeted.",
        "how-it-works-3-subheading": "Low ferritin impairs thyroid hormone conversion. Vitamin D deficiency worsens autoimmune thyroid disease. High cortisol suppresses TSH. We test these cofactors alongside your thyroid panel because they directly affect thyroid function and symptoms.",
        "how-it-works-4-subheading": "Our clinical team explains all your thyroid markers in context - not just whether TSH is in range. If hypothyroidism is detected, they recommend next steps including endocrinologist referral. Results in about 10 days.",
        "condition-name": "Hypothyroidism Biomarker Screening",
        "condition-overview": "<p>Hypothyroidism (underactive thyroid) affects an estimated 20 million Americans. It occurs when the thyroid gland doesn't produce enough hormone, causing fatigue, weight gain, cold intolerance, and cognitive impairment. The most common cause is Hashimoto's autoimmune thyroiditis. Many cases are missed because doctors rely on TSH alone.</p>",
        "why-test": "<p>A TSH-only test misses early hypothyroidism, Hashimoto's with normal TSH, and T4-to-T3 conversion problems. The full panel - TSH, Free T4, T3, and thyroid antibodies - catches these. Adding ferritin, vitamin D, and cortisol reveals cofactors that worsen thyroid symptoms even when the thyroid itself is borderline.</p>",
        "what-is-included": "<p>Your panel includes TSH, Free T4, T3 uptake, TPO antibodies, thyroglobulin antibodies, ferritin, vitamin D, B12, cortisol, DHEA, CRP, complete metabolic panel, lipid panel, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If hypothyroidism biomarkers are abnormal, our care team explains the findings and recommends next steps - endocrinologist referral for medication, optimization of iron and vitamin D, and lifestyle changes. Annual retesting tracks treatment response and thyroid function over time.</p>",
        "meta-title": "Hypothyroidism Blood Test | Full Thyroid Panel | Superpower",
        "meta-description": "Complete hypothyroidism blood test - TSH, Free T4, T3, antibodies. Catches what TSH alone misses. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Hypothyroidism Blood Test | Full Thyroid Panel | Superpower",
        "og-description": "Test all 7 thyroid markers, not just TSH. Full panel + 100+ biomarkers. ~10 day results.",
    },
    "hyperthyroidism-biomarker-test": {
        "name": "Hyperthyroidism Biomarker Test",
        "hero-headline": "Heart Pounding, Losing Weight, Can't Sit Still? Check Your Thyroid Biomarkers.",
        "hero-subheadline": "<p>Hyperthyroidism speeds up everything - your heart, your metabolism, your anxiety. TSH, Free T4, T3, and thyroid antibodies identify whether your thyroid is in overdrive and why. One blood draw. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Thyroid Biomarkers",
        "primary-keyword": "hyperthyroidism blood test",
        "secondary-keywords": "hyperthyroidism biomarkers, overactive thyroid test, thyroid blood test",
        "symptom-headline": "Signs your thyroid may be overactive",
        "symptom-1": "Rapid heartbeat or palpitations - especially at rest",
        "symptom-2": "Unintentional weight loss despite eating normally",
        "symptom-3": "Trembling hands or shakiness you can't control",
        "symptom-4": "Anxiety, nervousness, or feeling 'wired' all the time",
        "symptom-5": "Excessive sweating and heat intolerance",
        "symptom-cta": "Find out if your thyroid is in overdrive ->",
        "stat-1-number": "1.2%",
        "stat-1-text": "of Americans have hyperthyroidism - often misdiagnosed as anxiety, heart conditions, or menopause",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>My doctor prescribed anxiety medication. Superpower found my TSH was 0.05 and T4 was elevated. Classic hyperthyroidism. An endocrinologist confirmed Graves' disease within a week. Right diagnosis, right treatment - instead of just masking symptoms.</p>",
        "featured-testimonial-name": "Tanya B.",
        "featured-testimonial-result": "Hyperthyroidism diagnosed after being treated for anxiety",
        "membership-subheadline": "Detect thyroid overactivity and track treatment",
        "membership-benefit-1": "Full thyroid panel with antibodies",
        "membership-benefit-2": "100+ biomarkers including heart and metabolic",
        "membership-benefit-3": "AI flags thyroid overactivity patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests TSH, Free T4, T3, thyroid antibodies (TPO, thyroglobulin), calcium, liver enzymes, and CBC - key hyperthyroidism markers - plus 90+ other biomarkers. $199/year.",
        "how-it-works-2-subheading": "In hyperthyroidism, TSH drops to near zero while T4 and/or T3 spike. Thyroid antibodies help determine the cause - Graves' disease (autoimmune) vs toxic nodules vs thyroiditis. The cause determines the treatment approach.",
        "how-it-works-3-subheading": "Untreated hyperthyroidism damages the heart (atrial fibrillation), weakens bones (osteoporosis), and stresses the liver. We test calcium, liver enzymes, and CBC alongside thyroid markers to assess the full impact on your body.",
        "how-it-works-4-subheading": "Our clinical team explains your thyroid results and recommends endocrinologist referral if hyperthyroidism is detected. Treatment depends on the cause and severity. Results in about 10 days.",
        "condition-name": "Hyperthyroidism Biomarker Screening",
        "condition-overview": "<p>Hyperthyroidism occurs when the thyroid produces too much hormone, accelerating metabolism and putting stress on the heart, bones, and nervous system. The most common cause is Graves' disease (autoimmune). It affects about 1.2% of Americans and is 5-10 times more common in women. Without treatment, it can cause serious cardiac complications.</p>",
        "why-test": "<p>Hyperthyroidism symptoms - anxiety, rapid heartbeat, weight loss, tremors - overlap with many other conditions. Blood testing definitively confirms or rules it out. TSH, Free T4, and T3 show thyroid function. Antibodies identify the autoimmune cause. Testing prevents months of misdiagnosis and inappropriate treatment.</p>",
        "what-is-included": "<p>Your panel includes TSH, Free T4, T3 uptake, thyroid antibodies, calcium, CBC, liver enzymes, complete metabolic panel, lipid panel, and CRP - 100+ biomarkers total.</p>",
        "next-steps": "<p>If hyperthyroidism markers are found (suppressed TSH, elevated T4/T3), our care team recommends urgent endocrinology referral. Treatment options depend on the cause and include antithyroid medication, radioactive iodine, or monitoring for mild cases.</p>",
        "meta-title": "Hyperthyroidism Blood Test | Thyroid Biomarkers | Superpower",
        "meta-description": "Test for hyperthyroidism - TSH, Free T4, T3, antibodies. Often misdiagnosed as anxiety. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Hyperthyroidism Blood Test | Thyroid Biomarkers | Superpower",
        "og-description": "Screen for overactive thyroid with full panel + 100+ biomarkers. ~10 day results.",
    },
    "pcos-biomarker-test": {
        "name": "PCOS Biomarker Test",
        "hero-headline": "The Blood Work Your Gynecologist Should Be Ordering for PCOS.",
        "hero-subheadline": "<p>PCOS diagnosis requires blood markers - not just an ultrasound. Testosterone, free testosterone, DHEA-S, fasting insulin, and thyroid antibodies reveal the hormonal and metabolic drivers behind your symptoms. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Get PCOS Biomarker Testing",
        "primary-keyword": "PCOS biomarker test",
        "secondary-keywords": "PCOS blood work, PCOS hormones, polycystic ovary syndrome biomarkers",
        "symptom-headline": "PCOS biomarkers your doctor may not be testing",
        "symptom-1": "Irregular periods with acne along the jawline",
        "symptom-2": "Weight gain concentrated around the midsection",
        "symptom-3": "Excess facial or body hair that wasn't there before",
        "symptom-4": "Hair thinning on top while growing elsewhere",
        "symptom-5": "Previous 'normal' ultrasound but symptoms persist",
        "symptom-cta": "Get the PCOS blood work that gives real answers ->",
        "stat-1-number": "70%",
        "stat-1-text": "of women with PCOS are undiagnosed - ultrasound alone misses up to 30% of cases",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Ultrasound showed normal ovaries. My gynecologist said I didn't have PCOS. Superpower found my free testosterone was 2x normal and fasting insulin was 21. Classic PCOS. Blood work caught what ultrasound missed.</p>",
        "featured-testimonial-name": "Priya S.",
        "featured-testimonial-result": "PCOS confirmed via biomarkers after normal ultrasound",
        "membership-subheadline": "Track PCOS biomarkers and metabolic health",
        "membership-benefit-1": "Testosterone, insulin, and DHEA annually",
        "membership-benefit-2": "Full hormone panel plus metabolic markers",
        "membership-benefit-3": "AI tracks hormonal and metabolic patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests total testosterone, free testosterone, DHEA-S, SHBG, fasting insulin, HbA1c, thyroid panel, and CRP - all key PCOS biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "PCOS is driven by two factors: excess androgens and insulin resistance. Elevated testosterone causes acne, hair growth, and hair loss. High insulin drives weight gain and worsens androgen levels. Blood biomarkers quantify both drivers so treatment can be targeted.",
        "how-it-works-3-subheading": "Thyroid dysfunction mimics PCOS symptoms perfectly. We test TSH, T4, and thyroid antibodies alongside hormones to ensure the right condition gets diagnosed and treated. Misdiagnosis means wrong treatment.",
        "how-it-works-4-subheading": "Our clinical team explains your PCOS biomarkers in context and recommends next steps - lifestyle changes, specialist referral, or targeted treatment. Results in about 10 days.",
        "condition-name": "PCOS Biomarker Screening",
        "condition-overview": "<p>Polycystic ovary syndrome (PCOS) affects 1 in 10 women of reproductive age. It's caused by excess androgens (male hormones) and typically accompanied by insulin resistance. Blood biomarkers - testosterone, DHEA-S, fasting insulin, and SHBG - are essential for diagnosis. Up to 30% of women with PCOS have normal ultrasounds, making blood work the definitive diagnostic tool.</p>",
        "why-test": "<p>PCOS cannot be reliably diagnosed by ultrasound alone. Blood biomarkers reveal the hormonal imbalance (elevated androgens) and metabolic dysfunction (insulin resistance) that drive the condition. Testing fasting insulin is especially important because insulin resistance is present in up to 80% of PCOS cases and is the most treatable aspect.</p>",
        "what-is-included": "<p>Your panel includes total testosterone, free testosterone, DHEA-S, SHBG, fasting insulin, HbA1c, complete thyroid panel with antibodies, CRP, CBC, lipid panel, liver enzymes, and metabolic panel - 100+ biomarkers total.</p>",
        "next-steps": "<p>If PCOS biomarkers are elevated, our care team explains the findings and recommends next steps - lifestyle modifications for insulin resistance, dermatology referral for skin/hair symptoms, or endocrinology/gynecology referral for hormonal management.</p>",
        "meta-title": "PCOS Biomarker Test | Hormones + Insulin | Superpower",
        "meta-description": "PCOS biomarker test - testosterone, DHEA, insulin, SHBG. Diagnoses PCOS when ultrasound misses it. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "PCOS Biomarker Test | Hormones + Insulin | Superpower",
        "og-description": "Get the PCOS biomarkers your doctor isn't testing. Full hormone + metabolic panel. ~10 day results.",
    },
    "insulin-resistance-biomarker-test": {
        "name": "Insulin Resistance Biomarker Test",
        "hero-headline": "Glucose Is Normal. Insulin Is 3x Too High. Nobody Tested It.",
        "hero-subheadline": "<p>Insulin resistance hides for 10-15 years because doctors only test glucose. By the time glucose rises, the damage is done. Fasting insulin, HbA1c, and triglyceride-to-HDL ratio catch it at the earliest stage. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Insulin Levels",
        "primary-keyword": "insulin resistance biomarker test",
        "secondary-keywords": "insulin resistance blood test, fasting insulin test, insulin resistance biomarkers",
        "symptom-headline": "Biomarkers that reveal hidden insulin resistance",
        "symptom-1": "Belly fat that won't budge no matter what you try",
        "symptom-2": "Energy crashes after carb-heavy meals",
        "symptom-3": "Sugar cravings that feel almost uncontrollable",
        "symptom-4": "Skin tags or dark patches on neck and armpits",
        "symptom-5": "Previous 'normal' glucose but metabolic symptoms persist",
        "symptom-cta": "Check if your insulin tells a different story ->",
        "stat-1-number": "88M",
        "stat-1-text": "Americans have insulin resistance - invisible on standard glucose tests but detectable with fasting insulin",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Fasting glucose was 92 - 'perfect.' Fasting insulin was 24 - three times what it should be. Insulin resistant for years while doctors said my blood sugar was fine. Diet changes brought insulin down to 7 in four months.</p>",
        "featured-testimonial-name": "Diane K.",
        "featured-testimonial-result": "Insulin dropped from 24 to 7 with targeted diet changes",
        "membership-subheadline": "Catch insulin resistance before diabetes develops",
        "membership-benefit-1": "Fasting insulin plus glucose and A1C annually",
        "membership-benefit-2": "100+ biomarkers including full metabolic panel",
        "membership-benefit-3": "AI calculates TG/HDL ratio and IR risk score",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests fasting insulin, fasting glucose, HbA1c, triglycerides, HDL, and calculates your TG/HDL ratio - the gold standard insulin resistance biomarkers - plus 100+ other markers. $199/year.",
        "how-it-works-2-subheading": "Insulin resistance means your cells stop responding to insulin, forcing the pancreas to produce more. Fasting insulin rises years before glucose does. A TG/HDL ratio above 2.0 is another strong indicator. These biomarkers detect the problem at its most reversible stage.",
        "how-it-works-3-subheading": "Insulin resistance drives weight gain, fatty liver, PCOS, inflammation, and cardiovascular disease. We test metabolic markers alongside liver enzymes, hormones, and CRP to assess the full downstream impact - not just the insulin number.",
        "how-it-works-4-subheading": "Our clinical team explains your insulin and metabolic biomarkers and provides specific dietary and lifestyle recommendations. Most people can reverse insulin resistance within 3-6 months. Results in about 10 days.",
        "condition-name": "Insulin Resistance Biomarker Screening",
        "condition-overview": "<p>Insulin resistance affects an estimated 88 million Americans. It occurs when cells become less responsive to insulin, forcing the pancreas to produce more to maintain normal blood sugar. This hidden state persists for 10-15 years before glucose finally rises. During that time, elevated insulin drives weight gain, fatty liver, inflammation, and cardiovascular damage.</p>",
        "why-test": "<p>Standard blood panels test fasting glucose, which stays normal until insulin resistance is advanced. Fasting insulin is the early warning that detects the problem years sooner. The triglyceride-to-HDL ratio provides additional confirmation. Together, these biomarkers catch insulin resistance at its most reversible stage - when diet and lifestyle changes can reverse it completely.</p>",
        "what-is-included": "<p>Your panel includes fasting insulin, fasting glucose, HbA1c, triglycerides, HDL, complete lipid panel, liver enzymes (ALT, GGT), CRP, uric acid, hormones, thyroid, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If insulin resistance biomarkers are elevated, our care team provides specific dietary recommendations (reducing refined carbohydrates, intermittent fasting considerations), exercise guidance, and monitoring schedule. Most members see significant improvement within 3-6 months.</p>",
        "meta-title": "Insulin Resistance Biomarkers | Fasting Insulin | Superpower",
        "meta-description": "Test insulin resistance biomarkers - fasting insulin, HbA1c, TG/HDL ratio. Catches IR 10 years before diabetes. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Insulin Resistance Biomarkers | Fasting Insulin | Superpower",
        "og-description": "Your glucose is normal but insulin may be 3x too high. Test the biomarkers that matter. ~10 day results.",
    },
    "prediabetes-biomarker-test": {
        "name": "Prediabetes Biomarker Test",
        "hero-headline": "84% of Prediabetics Don't Know It. These 3 Biomarkers Would Tell Them.",
        "hero-subheadline": "<p>HbA1c, fasting glucose, and fasting insulin - tested together - catch prediabetes at its earliest stage. Most doctors only test one of these. We test all three plus 100+ other biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen for Prediabetes",
        "primary-keyword": "prediabetes biomarker test",
        "secondary-keywords": "prediabetes blood test, prediabetes screening biomarkers, A1C test prediabetes",
        "symptom-headline": "Risk factors that make prediabetes screening critical",
        "symptom-1": "Family history of type 2 diabetes",
        "symptom-2": "Carrying extra weight - especially around the middle",
        "symptom-3": "Energy crashes after meals that leave you foggy",
        "symptom-4": "Age 35+ with a sedentary lifestyle",
        "symptom-5": "Previous borderline glucose result that was never followed up",
        "symptom-cta": "Find out where you stand with 3 key biomarkers ->",
        "stat-1-number": "84%",
        "stat-1-text": "of the 88 million Americans with prediabetes don't know they have it - blood biomarkers are the only way to find out",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Glucose was 99 - 'borderline.' Nobody tested HbA1c or insulin. Superpower found A1c was 5.9 and fasting insulin was 17. Solidly prediabetic. Six months of dietary changes reversed everything. Caught it just in time.</p>",
        "featured-testimonial-name": "Marcus J.",
        "featured-testimonial-result": "A1c dropped from 5.9 to 5.2 in 6 months",
        "membership-subheadline": "Monitor prediabetes biomarkers and track reversal",
        "membership-benefit-1": "HbA1c, glucose, and insulin tested annually",
        "membership-benefit-2": "100+ biomarkers including full metabolic panel",
        "membership-benefit-3": "AI tracks metabolic trends over time",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests HbA1c (3-month glucose average), fasting glucose, fasting insulin, triglycerides, and complete lipid panel - the definitive prediabetes biomarker panel - plus 100+ other markers. $199/year.",
        "how-it-works-2-subheading": "HbA1c between 5.7-6.4% is prediabetic. But glucose can be normal while insulin is already elevated - the earliest sign. Testing all three biomarkers together catches prediabetes at every stage, from the first insulin spike to established glucose elevation.",
        "how-it-works-3-subheading": "Prediabetes damages blood vessels and organs even before it becomes diabetes. Liver enzymes (fatty liver), triglycerides, and CRP often rise alongside. We test the full metabolic picture to assess total damage and guide treatment.",
        "how-it-works-4-subheading": "Our clinical team explains your prediabetes biomarkers and provides evidence-based reversal recommendations. 58% of prediabetes cases reverse with moderate weight loss and dietary changes. Results in about 10 days.",
        "condition-name": "Prediabetes Biomarker Screening",
        "condition-overview": "<p>Prediabetes affects 88 million Americans - about 1 in 3 adults. Blood sugar is elevated but not yet diabetic. Without intervention, 15-30% develop type 2 diabetes within 5 years. Three key biomarkers - HbA1c, fasting glucose, and fasting insulin - together provide the most complete prediabetes assessment.</p>",
        "why-test": "<p>Most prediabetes goes undetected because standard physicals only test fasting glucose. HbA1c adds the 3-month average, and fasting insulin detects the metabolic dysfunction that precedes glucose elevation by years. Testing all three biomarkers catches prediabetes at its earliest, most reversible stage.</p>",
        "what-is-included": "<p>Your panel includes HbA1c, fasting glucose, fasting insulin, complete lipid panel, liver enzymes (ALT, AST, GGT), kidney function (eGFR, creatinine), CRP, uric acid, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If prediabetes biomarkers are elevated, our care team provides evidence-based recommendations. Studies show that 5-7% weight loss and 150 minutes of weekly exercise reverse prediabetes in the majority of cases. Annual retesting confirms whether your interventions are working.</p>",
        "meta-title": "Prediabetes Biomarkers | A1C + Insulin Test | Superpower",
        "meta-description": "Test 3 prediabetes biomarkers - HbA1c, glucose, fasting insulin. 84% of prediabetics don't know it. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Prediabetes Biomarkers | A1C + Insulin Test | Superpower",
        "og-description": "Screen for prediabetes with 3 key biomarkers. 100+ total markers. ~10 day results.",
    },
    "diabetes-mellitus-type-2-biomarker-test": {
        "name": "Type 2 Diabetes Biomarker Test",
        "hero-headline": "1 in 3 Adults Is Prediabetic or Diabetic. Most Find Out Too Late.",
        "hero-subheadline": "<p>Type 2 diabetes causes damage years before diagnosis. HbA1c, fasting glucose, fasting insulin, and kidney markers detect it at every stage - from early insulin resistance to established disease. Monitor your metabolic health comprehensively. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Diabetes Biomarkers",
        "primary-keyword": "diabetes blood test",
        "secondary-keywords": "type 2 diabetes biomarkers, diabetes screening blood test, diabetes blood markers",
        "symptom-headline": "When diabetes biomarker testing is critical",
        "symptom-1": "Family history of type 2 diabetes in parents or siblings",
        "symptom-2": "Previous borderline glucose or A1c results",
        "symptom-3": "Increased thirst and frequent urination",
        "symptom-4": "Slow-healing wounds or frequent infections",
        "symptom-5": "Tingling or numbness in hands or feet",
        "symptom-cta": "Get comprehensive diabetes biomarker screening ->",
        "stat-1-number": "37M",
        "stat-1-text": "Americans have diabetes - 1 in 5 don't know it. Blood biomarkers are the only reliable screening method",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>My A1c was 6.8 - diabetic range. I had zero symptoms. Without testing I could have gone years causing organ damage without knowing. Diet and exercise brought it back to 5.6 in 8 months. Testing saved me from a diabetes diagnosis.</p>",
        "featured-testimonial-name": "Robert T.",
        "featured-testimonial-result": "A1c reversed from 6.8 (diabetic) to 5.6 in 8 months",
        "membership-subheadline": "Monitor diabetes biomarkers and track progress",
        "membership-benefit-1": "A1c, glucose, insulin, and kidney markers yearly",
        "membership-benefit-2": "100+ biomarkers including liver and lipids",
        "membership-benefit-3": "AI tracks metabolic trends and complications",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests HbA1c, fasting glucose, fasting insulin, eGFR, creatinine, lipid panel, liver enzymes, and uric acid - comprehensive diabetes biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Type 2 diabetes doesn't just affect blood sugar. It damages kidneys (eGFR), liver (fatty liver), blood vessels (lipids), and nerves. We test the full spectrum of diabetes-related biomarkers to assess both the disease and its complications.",
        "how-it-works-3-subheading": "Many people with type 2 diabetes also have undiagnosed thyroid disease, vitamin D deficiency, and iron imbalances. We test these alongside metabolic markers because they affect diabetes management and overall health outcomes.",
        "how-it-works-4-subheading": "Our clinical team explains your diabetes biomarkers comprehensively and recommends next steps - dietary changes, exercise, specialist referral, or monitoring schedule. Results in about 10 days.",
        "condition-name": "Type 2 Diabetes Biomarker Screening",
        "condition-overview": "<p>Type 2 diabetes affects 37 million Americans. It develops when the body becomes resistant to insulin or the pancreas can't produce enough. Uncontrolled diabetes damages kidneys, eyes, nerves, and blood vessels. Blood biomarkers - HbA1c, fasting glucose, and fasting insulin - are the definitive screening method.</p>",
        "why-test": "<p>1 in 5 people with diabetes don't know they have it. Early-stage type 2 diabetes often has no symptoms while silently causing organ damage. Comprehensive biomarker testing catches the disease at every stage and monitors for complications. Annual testing is essential for anyone with risk factors.</p>",
        "what-is-included": "<p>Your panel includes HbA1c, fasting glucose, fasting insulin, eGFR, creatinine, BUN, complete lipid panel, liver enzymes, uric acid, CRP, CBC, thyroid panel, and vitamin D - 100+ biomarkers total.</p>",
        "next-steps": "<p>If diabetes biomarkers are elevated, our care team provides staging (prediabetes vs diabetes), complication assessment, and specific recommendations. Early type 2 diabetes is often reversible with aggressive lifestyle changes. Annual retesting tracks progress and catches complications early.</p>",
        "meta-title": "Type 2 Diabetes Blood Test | Biomarker Screening | Superpower",
        "meta-description": "Comprehensive diabetes biomarker test - A1c, glucose, insulin, kidney, liver. 1 in 5 diabetics don't know it. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Type 2 Diabetes Blood Test | Biomarker Screening | Superpower",
        "og-description": "Screen for diabetes with A1c, insulin + 100+ biomarkers. Monitor disease and complications. ~10 day results.",
    },
    "metabolic-syndrome-biomarker-test": {
        "name": "Metabolic Syndrome Biomarker Test",
        "hero-headline": "Belly Fat + High Triglycerides + Low HDL = Metabolic Syndrome. Test the Biomarkers.",
        "hero-subheadline": "<p>Metabolic syndrome isn't one disease - it's a cluster of biomarkers that together predict heart attacks, strokes, and diabetes. Triglycerides, HDL, fasting glucose, fasting insulin, and CRP reveal whether your metabolism is heading toward a crisis. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen for Metabolic Syndrome",
        "primary-keyword": "metabolic syndrome blood test",
        "secondary-keywords": "metabolic syndrome biomarkers, metabolic panel blood test, metabolic syndrome screening",
        "symptom-headline": "Red flags for metabolic syndrome",
        "symptom-1": "Belly fat that accumulates despite effort to lose it",
        "symptom-2": "High triglycerides or low HDL on past blood work",
        "symptom-3": "Borderline high blood pressure readings",
        "symptom-4": "Fasting glucose above 100 but below diabetic range",
        "symptom-5": "Family history of heart disease or type 2 diabetes",
        "symptom-cta": "Find out if your biomarkers point to metabolic syndrome ->",
        "stat-1-number": "35%",
        "stat-1-text": "of American adults meet criteria for metabolic syndrome - it doubles heart attack risk and 5x diabetes risk",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Triglycerides were 280, HDL was 34, fasting glucose was 108, and insulin was 19. Four out of five metabolic syndrome criteria. Nobody had connected the dots until Superpower's panel showed the full picture. Six months of lifestyle changes improved every single marker.</p>",
        "featured-testimonial-name": "Frank D.",
        "featured-testimonial-result": "All 4 metabolic syndrome markers improved in 6 months",
        "membership-subheadline": "Track metabolic syndrome biomarkers over time",
        "membership-benefit-1": "Triglycerides, HDL, glucose, and insulin yearly",
        "membership-benefit-2": "100+ biomarkers including liver and inflammation",
        "membership-benefit-3": "AI connects metabolic biomarker patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests triglycerides, HDL, fasting glucose, fasting insulin, HbA1c, hsCRP, liver enzymes, and uric acid - the key metabolic syndrome biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Metabolic syndrome is diagnosed when 3+ of these are present: high triglycerides (150+), low HDL (<40 men, <50 women), high fasting glucose (100+), high blood pressure, and central obesity. Blood biomarkers identify 3 of the 5 criteria directly.",
        "how-it-works-3-subheading": "Fatty liver (elevated ALT/GGT), chronic inflammation (elevated CRP), and hyperuricemia (elevated uric acid) almost always accompany metabolic syndrome. We test these alongside the core biomarkers to assess the full metabolic picture.",
        "how-it-works-4-subheading": "Our clinical team identifies which metabolic biomarkers are abnormal and provides targeted recommendations. Metabolic syndrome is highly reversible with diet, exercise, and weight management. Results in about 10 days.",
        "condition-name": "Metabolic Syndrome Biomarker Screening",
        "condition-overview": "<p>Metabolic syndrome affects about 35% of American adults. It's defined by a cluster of conditions - central obesity, high triglycerides, low HDL, high blood pressure, and high fasting glucose - that together dramatically increase risk for heart disease, stroke, and type 2 diabetes. Blood biomarkers identify 3 of the 5 diagnostic criteria.</p>",
        "why-test": "<p>Individual biomarkers may be 'borderline' on their own, but together they signal metabolic syndrome - a condition that doubles heart attack risk and increases diabetes risk 5-fold. Comprehensive testing identifies the pattern that individual markers miss. It also reveals insulin resistance, fatty liver, and inflammation that drive the syndrome.</p>",
        "what-is-included": "<p>Your panel includes triglycerides, HDL, LDL, total cholesterol, fasting glucose, fasting insulin, HbA1c, hsCRP, uric acid, liver enzymes (ALT, AST, GGT), eGFR, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If metabolic syndrome biomarkers are present, our care team provides a comprehensive reversal plan - dietary changes, exercise recommendations, and monitoring schedule. Many people normalize all biomarkers within 6-12 months of targeted lifestyle changes.</p>",
        "meta-title": "Metabolic Syndrome Test | Biomarker Screening | Superpower",
        "meta-description": "Test for metabolic syndrome - triglycerides, HDL, glucose, insulin, CRP. 35% of adults affected. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Metabolic Syndrome Test | Biomarker Screening | Superpower",
        "og-description": "Screen for metabolic syndrome with comprehensive biomarkers. 100+ markers in one draw. ~10 day results.",
    },
    "nafld-biomarker-test": {
        "name": "NAFLD Biomarker Test",
        "hero-headline": "Your Liver Enzymes Are Elevated. Here's What Your Biomarkers Are Trying to Tell You.",
        "hero-subheadline": "<p>Non-alcoholic fatty liver disease affects 1 in 4 adults - and the first clue is elevated ALT and GGT on blood work. We test the complete liver biomarker panel alongside insulin, triglycerides, and inflammation to reveal why your liver is struggling. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Check Your Liver Biomarkers",
        "primary-keyword": "NAFLD biomarker test",
        "secondary-keywords": "fatty liver blood test, NAFLD blood markers, liver biomarkers",
        "symptom-headline": "Risk factors that put your liver biomarkers at risk",
        "symptom-1": "Previous blood work showing elevated ALT or GGT",
        "symptom-2": "Insulin resistance, prediabetes, or type 2 diabetes",
        "symptom-3": "Carrying extra weight - especially visceral belly fat",
        "symptom-4": "High triglycerides on past lipid panels",
        "symptom-5": "Fatigue that seems disproportionate to your lifestyle",
        "symptom-cta": "Test your liver biomarkers now ->",
        "stat-1-number": "25%",
        "stat-1-text": "of adults have NAFLD - most are unaware because the liver sends no pain signals until advanced stages",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>ALT was 72, GGT was 58. I don't drink at all. Superpower also showed my fasting insulin was 20 and triglycerides were 240. Insulin resistance was causing fatty liver. Diet changes normalized everything in 8 months.</p>",
        "featured-testimonial-name": "Linda M.",
        "featured-testimonial-result": "Liver biomarkers normalized in 8 months via diet",
        "membership-subheadline": "Track liver and metabolic biomarkers over time",
        "membership-benefit-1": "Liver enzymes plus insulin and lipids yearly",
        "membership-benefit-2": "100+ biomarkers including full metabolic panel",
        "membership-benefit-3": "AI connects liver and metabolic patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ALT, AST, GGT, ALP, bilirubin, albumin, fasting insulin, triglycerides, and HbA1c - the key NAFLD biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "NAFLD is almost always driven by insulin resistance. ALT and GGT are the first biomarkers to rise. But without testing insulin, triglycerides, and glucose alongside liver enzymes, you're seeing the symptom without understanding the cause.",
        "how-it-works-3-subheading": "NAFLD is reversible when caught early. But without monitoring, it can progress to NASH (inflammation), fibrosis, cirrhosis, and liver cancer. Annual biomarker tracking shows whether your liver is improving or worsening.",
        "how-it-works-4-subheading": "Our clinical team explains your liver biomarkers in context and provides targeted recommendations for reversing fatty liver. Most people see significant improvement with 7-10% weight loss and dietary changes. Results in about 10 days.",
        "condition-name": "NAFLD Biomarker Screening",
        "condition-overview": "<p>Non-alcoholic fatty liver disease (NAFLD) occurs when fat accumulates in liver cells without alcohol being the cause. It's the most common liver disease worldwide, affecting 25% of adults. NAFLD has no symptoms until advanced stages. Blood biomarkers - especially ALT, GGT, and metabolic markers - are the primary screening method.</p>",
        "why-test": "<p>The liver sends no pain signals. NAFLD is discovered through elevated liver biomarkers on blood work - usually incidentally. ALT is the most sensitive marker. GGT adds specificity. Testing these alongside insulin and triglycerides identifies both the disease and its metabolic driver. Early detection means the condition can be reversed with lifestyle changes.</p>",
        "what-is-included": "<p>Your panel includes ALT, AST, GGT, ALP, bilirubin, albumin, fasting insulin, fasting glucose, HbA1c, triglycerides, complete lipid panel, CRP, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If liver biomarkers are elevated, our care team explains the likely cause and recommends next steps - dietary changes, weight management, and potentially imaging or specialist referral. NAFLD is reversible in early stages with targeted lifestyle modifications.</p>",
        "meta-title": "NAFLD Biomarker Test | Liver + Metabolic Panel | Superpower",
        "meta-description": "Test NAFLD biomarkers - ALT, GGT, insulin, triglycerides. 1 in 4 adults has fatty liver. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "NAFLD Biomarker Test | Liver + Metabolic Panel | Superpower",
        "og-description": "Screen for fatty liver with liver enzymes + metabolic biomarkers. 100+ markers. ~10 day results.",
    },
    "iron-deficiency-anemia-biomarker-test": {
        "name": "Iron Deficiency Anemia Biomarker Test",
        "hero-headline": "Hemoglobin Is Normal. Ferritin Is 8. You've Been Iron Depleted for Years.",
        "hero-subheadline": "<p>Iron deficiency causes crushing fatigue, hair loss, and brain fog long before hemoglobin drops into the anemic range. Ferritin, iron, TIBC, and iron saturation - the complete iron biomarker panel - catch it at the earliest stage. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Iron Biomarkers",
        "primary-keyword": "iron deficiency blood test",
        "secondary-keywords": "iron deficiency biomarkers, ferritin test, iron panel blood test, anemia biomarkers",
        "symptom-headline": "Symptoms of iron depletion most doctors miss",
        "symptom-1": "Exhaustion that no amount of sleep can fix",
        "symptom-2": "Hair falling out more than normal",
        "symptom-3": "Dizziness or lightheadedness when standing up",
        "symptom-4": "Restless legs that keep you up at night",
        "symptom-5": "Normal CBC but symptoms that scream deficiency",
        "symptom-cta": "Check if your ferritin tells a different story ->",
        "stat-1-number": "25%",
        "stat-1-text": "of the global population has iron deficiency - symptoms appear at ferritin levels most doctors call 'normal'",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Hemoglobin was 12.2 - 'normal.' But ferritin was 8 and iron saturation was 12%. Iron depleted for years while every doctor said my blood work was fine. Got ferritin to 70 and the fatigue, hair loss, and brain fog all stopped.</p>",
        "featured-testimonial-name": "Rachel T.",
        "featured-testimonial-result": "Ferritin from 8 to 70 - all symptoms resolved",
        "membership-subheadline": "Track iron biomarkers and prevent deficiency",
        "membership-benefit-1": "Ferritin, iron, and TIBC tested annually",
        "membership-benefit-2": "Complete CBC plus iron panel included",
        "membership-benefit-3": "AI flags iron depletion before anemia",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ferritin, serum iron, TIBC, iron saturation, and complete CBC (hemoglobin, hematocrit, MCV, RDW) - your complete iron biomarker panel - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Iron depletion progresses in stages: ferritin drops first (storage depletion), then iron saturation falls, and hemoglobin drops last. Most doctors only test hemoglobin via CBC. That misses the first two stages entirely - the stages where symptoms are worst and treatment is simplest.",
        "how-it-works-3-subheading": "Anemia has multiple causes. MCV distinguishes iron deficiency (low MCV) from B12/folate deficiency (high MCV). CRP rules out anemia of chronic disease. We test the full picture to identify the root cause, not just confirm low iron.",
        "how-it-works-4-subheading": "Our clinical team explains your iron biomarkers in context and recommends specific supplementation - type, dose, and timing all matter for iron absorption. Results in about 10 days.",
        "condition-name": "Iron Deficiency Anemia Biomarker Screening",
        "condition-overview": "<p>Iron deficiency is the most common nutritional deficiency worldwide, affecting 25% of the population. It progresses through stages - storage depletion (low ferritin), transport depletion (low iron saturation), and finally anemia (low hemoglobin). Symptoms begin in the earliest stage when ferritin drops below 30-50 ng/mL, well above the 'normal' threshold of 12.</p>",
        "why-test": "<p>Standard blood work (CBC only) detects iron deficiency at its final stage - anemia. Ferritin drops years before hemoglobin does. Testing the complete iron biomarker panel catches depletion at its earliest stage when symptoms are already present but diagnosis is typically missed.</p>",
        "what-is-included": "<p>Your panel includes ferritin, serum iron, TIBC, iron saturation, CBC with differential (hemoglobin, hematocrit, MCV, MCH, MCHC, RDW), vitamin B12, folate, CRP, vitamin D, and thyroid panel - 100+ biomarkers total.</p>",
        "next-steps": "<p>If iron biomarkers are low, our care team recommends specific supplementation (iron bisglycinate vs ferrous sulfate, optimal dosing, and timing with vitamin C). They also investigate potential causes - heavy periods, GI absorption issues, or chronic disease.</p>",
        "meta-title": "Iron Deficiency Blood Test | Ferritin + Iron Panel | Superpower",
        "meta-description": "Iron deficiency biomarker test - ferritin, iron, TIBC, iron saturation. Catches depletion before anemia. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Iron Deficiency Blood Test | Ferritin + Iron Panel | Superpower",
        "og-description": "Your hemoglobin is normal but ferritin may be critically low. Test the full iron panel. ~10 day results.",
    },
    "vitamin-d-deficiency-biomarker-test": {
        "name": "Vitamin D Deficiency Biomarker Test",
        "hero-headline": "42% of Americans Are Vitamin D Deficient. Supplements Aren't Fixing It Without Testing.",
        "hero-subheadline": "<p>You can't dose vitamin D correctly without knowing your level. Too little doesn't help. Too much is toxic. One blood test shows exactly where you stand - and whether your current supplement is working. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Vitamin D Level",
        "primary-keyword": "vitamin D deficiency test",
        "secondary-keywords": "vitamin D blood test, 25-OH vitamin D test, vitamin D level test",
        "symptom-headline": "Signs of vitamin D deficiency",
        "symptom-1": "Fatigue and low energy that worsens in winter",
        "symptom-2": "Bone pain, muscle weakness, or frequent fractures",
        "symptom-3": "Depression or mood changes - especially seasonal",
        "symptom-4": "Getting sick frequently - poor immune function",
        "symptom-5": "Taking supplements but not sure if they're working",
        "symptom-cta": "Find out if your vitamin D level is actually optimal ->",
        "stat-1-number": "42%",
        "stat-1-text": "of Americans are vitamin D deficient - associated with bone loss, depression, immune dysfunction, and increased cancer risk",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>I was taking 2,000 IU of vitamin D daily and assumed I was fine. My level was 18 ng/mL - severely deficient. Increased to 5,000 IU with K2 and retested 3 months later at 52. Night and day difference in energy and mood. You can't dose without testing.</p>",
        "featured-testimonial-name": "Jennifer L.",
        "featured-testimonial-result": "Vitamin D went from 18 to 52 with proper dosing",
        "membership-subheadline": "Test and optimize your vitamin D level",
        "membership-benefit-1": "Vitamin D level tested with every panel",
        "membership-benefit-2": "100+ biomarkers including calcium and thyroid",
        "membership-benefit-3": "AI tracks vitamin D trends seasonally",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests 25-hydroxy vitamin D (the gold standard marker), calcium, phosphorus, ALP, PTH markers, and thyroid panel - all connected to vitamin D status - plus 90+ other biomarkers. $199/year.",
        "how-it-works-2-subheading": "Vitamin D affects far more than bones. Deficiency is linked to depression, autoimmune disease, cancer risk, cardiovascular disease, and immune dysfunction. Optimal levels (40-60 ng/mL) differ significantly from the 'normal' threshold of 30. Testing reveals whether you're truly optimal, not just adequate.",
        "how-it-works-3-subheading": "Vitamin D is fat-soluble - dosing varies enormously by individual. Factors like body weight, skin color, sun exposure, and genetics mean one person needs 2,000 IU and another needs 10,000 IU. Testing is the only way to determine YOUR correct dose.",
        "how-it-works-4-subheading": "Our clinical team recommends specific vitamin D supplementation based on your level - dose, form (D3 with K2), and retesting schedule. Results in about 10 days.",
        "condition-name": "Vitamin D Deficiency Screening",
        "condition-overview": "<p>Vitamin D deficiency affects 42% of American adults. It plays critical roles in bone health, immune function, mood regulation, and disease prevention. Deficiency (below 30 ng/mL) increases risk for osteoporosis, depression, autoimmune disease, and certain cancers. Most experts recommend levels between 40-60 ng/mL for optimal health.</p>",
        "why-test": "<p>Vitamin D supplementation without testing is guesswork. Absorption varies dramatically based on body weight, genetics, and lifestyle. Many people supplementing are still deficient, while others may be taking too much. Blood testing is the only way to determine your actual level and dose correctly.</p>",
        "what-is-included": "<p>Your panel includes 25-hydroxy vitamin D, calcium, phosphorus, ALP, complete metabolic panel, thyroid panel, CRP, CBC, and more - 100+ biomarkers total.</p>",
        "next-steps": "<p>If vitamin D is low, our care team recommends specific supplementation - D3 form, dose based on your level and body weight, taken with K2 for optimal calcium metabolism. Retesting in 3 months confirms the dose is working.</p>",
        "meta-title": "Vitamin D Deficiency Test | 25-OH Vitamin D | Superpower",
        "meta-description": "Test vitamin D levels - 42% of Americans are deficient. 25-OH vitamin D plus 100+ biomarkers. Know if your supplement is working. ~10 days. $199/year.",
        "og-title": "Vitamin D Deficiency Test | 25-OH Vitamin D | Superpower",
        "og-description": "Find out if you're truly vitamin D optimal. 25-OH vitamin D + 100+ biomarkers. ~10 day results.",
    },
}


def fetch_all_pages():
    all_items = []
    offset = 0
    while True:
        url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items?limit=100&offset={offset}"
        resp = requests.get(url, headers=HEADERS)
        data = resp.json()
        items = data.get("items", [])
        all_items.extend(items)
        total = data.get("pagination", {}).get("total", 0)
        if offset + 100 >= total:
            break
        offset += 100
        time.sleep(0.3)
    return all_items


def main():
    print("=" * 70)
    print("BATCH 2: Rewrite 12 Tier 1 Biomarker-Test Pages (Part A)")
    print("=" * 70)

    print("\nFetching all pages...")
    all_items = fetch_all_pages()
    slug_map = {}
    for item in all_items:
        slug = item.get("fieldData", {}).get("slug", "")
        if slug:
            slug_map[slug] = item

    results = []
    for slug, fields in REWRITES.items():
        if slug not in slug_map:
            print(f"\n  SKIP: {slug} not found")
            results.append({"slug": slug, "status": "NOT_FOUND"})
            continue

        item_id = slug_map[slug]["id"]
        print(f"\n  REWRITING: {slug} (ID: {item_id})")

        url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items/{item_id}"
        resp = requests.patch(url, headers=HEADERS, json={"fieldData": fields})
        if resp.status_code == 200:
            print(f"    Updated: {fields['meta-title']}")
            results.append({"slug": slug, "item_id": item_id, "status": "UPDATED", "meta_title": fields["meta-title"]})
        else:
            print(f"    ERROR: {resp.status_code} {resp.text[:200]}")
            results.append({"slug": slug, "item_id": item_id, "status": "ERROR"})
        time.sleep(0.4)

    # Publish all
    updated_ids = [r["item_id"] for r in results if r["status"] == "UPDATED"]
    if updated_ids:
        print(f"\nPublishing {len(updated_ids)} pages...")
        for i in range(0, len(updated_ids), 100):
            batch = updated_ids[i:i+100]
            url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items/publish"
            resp = requests.post(url, headers=HEADERS, json={"itemIds": batch})
            print(f"  Publish: {resp.status_code}")

    print(f"\n{'=' * 70}")
    print("SUMMARY")
    for r in results:
        print(f"  {r['slug']}: {r['status']}")

    with open("/Users/jeffy/superpower-sem-gap/app/data/biomarker_rewrite_batch2.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nSaved to biomarker_rewrite_batch2.json")


if __name__ == "__main__":
    main()
