#!/usr/bin/env python3
"""Batch 3: Rewrite remaining 13 Tier 1 biomarker-test pages (Part B).
B12, folate, osteoporosis, gout, hyperuricemia, celiac, lupus,
dyslipidemia, coronary artery disease, hypertension, menopause,
male hypogonadism, female hypogonadism."""
import requests
import time
import json

API_KEY = "87be5982f1938a9143a7368af984a9863971dd55314fd5a60f482cc02425a0c7"
LP_COLLECTION = "6981a714e199bac70776d880"
HEADERS = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}

REWRITES = {
    "vitamin-b12-deficiency-biomarker-test": {
        "name": "Vitamin B12 Deficiency Biomarker Test",
        "hero-headline": "Tired, Foggy, Forgetful? Your B12 Level Has the Answer.",
        "hero-subheadline": "<p>Vitamin B12 deficiency causes fatigue, brain fog, memory problems, and nerve damage - often misdiagnosed as depression or aging. A simple blood test reveals your actual level. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your B12 Level",
        "primary-keyword": "vitamin B12 deficiency test",
        "secondary-keywords": "B12 blood test, vitamin B12 level test, B12 deficiency biomarkers",
        "symptom-headline": "Signs of B12 deficiency most people dismiss",
        "symptom-1": "Brain fog and difficulty concentrating that's getting worse",
        "symptom-2": "Fatigue that sleep doesn't fix",
        "symptom-3": "Tingling or numbness in hands or feet",
        "symptom-4": "Memory problems you're attributing to stress or aging",
        "symptom-5": "Vegetarian, vegan, or over 50 - groups at highest risk",
        "symptom-cta": "Find out if B12 deficiency is behind your symptoms ->",
        "stat-1-number": "40%",
        "stat-1-text": "of adults have suboptimal B12 levels - standard ranges miss functional deficiency that causes symptoms",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>My B12 was 280 - 'normal' according to the lab range. But I had brain fog, tingling hands, and couldn't remember simple things. Started B12 injections and within a month everything improved. The 'normal' range is misleadingly wide.</p>",
        "featured-testimonial-name": "Patricia K.",
        "featured-testimonial-result": "Brain fog and tingling resolved with B12 treatment",
        "membership-subheadline": "Monitor B12 and neurological health markers",
        "membership-benefit-1": "B12 plus folate and CBC tested annually",
        "membership-benefit-2": "100+ biomarkers including iron and thyroid",
        "membership-benefit-3": "AI flags suboptimal B12 before nerve damage",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests vitamin B12, folate, CBC with differential (MCV reveals B12-related anemia), homocysteine, iron studies, and thyroid panel - plus 90+ other biomarkers. $199/year.",
        "how-it-works-2-subheading": "B12 deficiency causes neurological damage that can become permanent if not caught. Standard lab ranges (200-900 pg/mL) are misleadingly wide - symptoms often begin below 400. We flag suboptimal levels, not just deficient ones.",
        "how-it-works-3-subheading": "MCV on your CBC helps distinguish B12 deficiency (high MCV) from iron deficiency (low MCV). Folate and homocysteine add context. We analyze the full picture to pinpoint which deficiency is causing your symptoms.",
        "how-it-works-4-subheading": "Our clinical team recommends specific B12 supplementation based on your level and absorption capacity - sublingual vs injection, methylcobalamin vs cyanocobalamin. Results in about 10 days.",
        "condition-name": "Vitamin B12 Deficiency Screening",
        "condition-overview": "<p>Vitamin B12 deficiency affects up to 40% of adults when suboptimal levels are included. It's especially common in vegetarians/vegans, adults over 50, and people taking metformin or PPIs. B12 is essential for nerve function, red blood cell production, and brain health. Deficiency causes fatigue, brain fog, memory problems, and irreversible nerve damage if untreated.</p>",
        "why-test": "<p>B12 deficiency develops gradually and symptoms are often attributed to stress, aging, or depression. Standard lab ranges are wide enough to miss functional deficiency. Testing reveals your actual level so treatment can begin before neurological damage becomes permanent.</p>",
        "what-is-included": "<p>Your panel includes vitamin B12, folate, CBC with differential (MCV, MCH), iron studies, ferritin, CRP, complete metabolic panel, thyroid panel, and more - 100+ biomarkers total.</p>",
        "next-steps": "<p>If B12 is suboptimal, our care team recommends supplementation type and dose based on your level, diet, and medication history. For severe deficiency, they may recommend injections and specialist follow-up.</p>",
        "meta-title": "B12 Deficiency Blood Test | Vitamin B12 Level | Superpower",
        "meta-description": "Test for vitamin B12 deficiency. 40% of adults have suboptimal levels. B12 + folate + CBC + 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "B12 Deficiency Blood Test | Vitamin B12 Level | Superpower",
        "og-description": "Tired, foggy, forgetful? Test your B12 level + 100+ biomarkers. ~10 day results.",
    },
    "folate-deficiency-biomarker-test": {
        "name": "Folate Deficiency Biomarker Test",
        "hero-headline": "Low Energy, Mood Swings, Mouth Sores? It Could Be Folate.",
        "hero-subheadline": "<p>Folate deficiency causes fatigue, depression, mouth sores, and a specific type of anemia that standard CBC often misses until it's advanced. A blood test confirms your level in days. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Folate Level",
        "primary-keyword": "folate deficiency test",
        "secondary-keywords": "folate blood test, folic acid test, folate level test",
        "symptom-headline": "Signs your folate may be too low",
        "symptom-1": "Fatigue and weakness that doesn't improve with rest",
        "symptom-2": "Mouth sores or a swollen, sore tongue",
        "symptom-3": "Irritability, forgetfulness, or mood changes",
        "symptom-4": "Shortness of breath with mild exertion",
        "symptom-5": "Planning pregnancy - folate is critical for neural development",
        "symptom-cta": "Check your folate level now ->",
        "stat-1-number": "20%",
        "stat-1-text": "of adults have insufficient folate - critical for cell division, DNA repair, and preventing birth defects",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Constant mouth sores and fatigue for months. Doctor said it was stress. Superpower found my folate was 3.2 - below optimal. B12 was also borderline. Supplementation cleared the mouth sores in two weeks and energy came back within a month.</p>",
        "featured-testimonial-name": "Sarah M.",
        "featured-testimonial-result": "Mouth sores and fatigue resolved with folate supplementation",
        "membership-subheadline": "Monitor folate and related nutrient levels",
        "membership-benefit-1": "Folate plus B12 and CBC tested annually",
        "membership-benefit-2": "100+ biomarkers including iron and thyroid",
        "membership-benefit-3": "AI connects folate to related deficiencies",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests serum folate, vitamin B12, CBC with differential (MCV detects folate-related anemia), iron studies, and complete metabolic panel - plus 90+ other biomarkers. $199/year.",
        "how-it-works-2-subheading": "Folate and B12 deficiency cause similar symptoms and the same type of anemia (megaloblastic - high MCV). Testing both together is essential because treating one without the other can mask the deficiency and allow nerve damage to progress.",
        "how-it-works-3-subheading": "MTHFR gene variants affect folate metabolism in up to 40% of the population. If you're taking folic acid and your levels remain low, you may need methylfolate instead. Blood testing confirms whether your supplementation is actually working.",
        "how-it-works-4-subheading": "Our clinical team recommends folate supplementation based on your level - active methylfolate for those with MTHFR variants, optimal dosing for pregnancy planning. Results in about 10 days.",
        "condition-name": "Folate Deficiency Screening",
        "condition-overview": "<p>Folate (vitamin B9) is essential for DNA synthesis, cell division, and red blood cell production. Deficiency causes megaloblastic anemia, fatigue, mouth sores, and mood changes. It's especially critical during pregnancy - deficiency causes neural tube defects. About 20% of adults have insufficient folate levels.</p>",
        "why-test": "<p>Folate deficiency develops gradually and symptoms overlap with many other conditions. A blood test definitively confirms your level. This is especially important for women planning pregnancy, people on certain medications (methotrexate, anticonvulsants), and those with MTHFR variants who can't process standard folic acid efficiently.</p>",
        "what-is-included": "<p>Your panel includes serum folate, vitamin B12, CBC with differential, iron studies, ferritin, complete metabolic panel, thyroid panel, and CRP - 100+ biomarkers total.</p>",
        "next-steps": "<p>If folate is low, our care team recommends supplementation - methylfolate for better absorption, appropriate dosing, and dietary guidance. For pregnancy planning, they recommend optimal levels and timing.</p>",
        "meta-title": "Folate Deficiency Test | Blood Folate Level | Superpower",
        "meta-description": "Test for folate deficiency - fatigue, mouth sores, mood changes. Folate + B12 + CBC + 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Folate Deficiency Test | Blood Folate Level | Superpower",
        "og-description": "Check your folate level. Critical for energy, mood, and pregnancy. 100+ biomarkers. ~10 day results.",
    },
    "osteoporosis-biomarker-test": {
        "name": "Osteoporosis Biomarker Test",
        "hero-headline": "A DEXA Shows Bone Loss After It Happens. Biomarkers Show Why.",
        "hero-subheadline": "<p>Vitamin D deficiency, thyroid dysfunction, and chronic inflammation drive bone loss - and blood biomarkers catch them before your DEXA score drops. Test the treatable causes, not just the result. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen Bone Health Biomarkers",
        "primary-keyword": "osteoporosis blood test",
        "secondary-keywords": "osteoporosis biomarkers, bone health blood test, bone density biomarkers",
        "symptom-headline": "When bone health biomarker testing is critical",
        "symptom-1": "Post-menopausal with family history of osteoporosis",
        "symptom-2": "Previous DEXA showing osteopenia but no investigation into why",
        "symptom-3": "Long-term corticosteroid use for any condition",
        "symptom-4": "Low vitamin D on previous blood work",
        "symptom-5": "Small frame, low body weight, or history of eating disorder",
        "symptom-cta": "Identify what's driving your bone loss ->",
        "stat-1-number": "54M",
        "stat-1-text": "Americans have low bone density - blood biomarkers reveal the treatable causes that DEXA alone can't explain",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>DEXA showed osteopenia but my doctor just said 'take calcium.' Superpower found my vitamin D was 16, thyroid was borderline overactive, and CRP was elevated. Three treatable drivers of bone loss that nobody investigated. Fixing them improved my next DEXA.</p>",
        "featured-testimonial-name": "Catherine L.",
        "featured-testimonial-result": "3 treatable causes of bone loss identified and addressed",
        "membership-subheadline": "Track bone health biomarkers over time",
        "membership-benefit-1": "Vitamin D, calcium, thyroid, and CRP annually",
        "membership-benefit-2": "100+ biomarkers including hormones",
        "membership-benefit-3": "AI connects bone health risk factors",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests vitamin D, calcium, ALP (bone turnover marker), complete thyroid panel, CRP, hormones (estradiol, testosterone), and metabolic markers - the key bone health biomarkers - plus 90+ others. $199/year.",
        "how-it-works-2-subheading": "Bone loss has multiple treatable causes: vitamin D deficiency impairs calcium absorption, hyperthyroidism accelerates bone turnover, chronic inflammation weakens structure, and low estrogen post-menopause speeds loss. Blood biomarkers identify which factors are driving YOUR bone density decline.",
        "how-it-works-3-subheading": "Blood testing complements DEXA scans - it doesn't replace them. DEXA measures bone density now. Biomarkers explain why it's changing and what you can do about it. Together they provide the complete bone health picture.",
        "how-it-works-4-subheading": "Our clinical team explains your bone health biomarkers and recommends specific interventions - vitamin D dosing, thyroid treatment, anti-inflammatory strategies, or specialist referral. Results in about 10 days.",
        "condition-name": "Osteoporosis Biomarker Screening",
        "condition-overview": "<p>Osteoporosis causes bones to become weak and fracture-prone. 54 million Americans have low bone density. While DEXA scans measure density directly, blood biomarkers identify the treatable conditions causing bone loss - vitamin D deficiency, thyroid dysfunction, chronic inflammation, hormonal decline, and calcium metabolism disorders.</p>",
        "why-test": "<p>Knowing your bone density is declining (via DEXA) isn't enough - you need to know WHY. Blood biomarkers identify the treatable drivers. Vitamin D deficiency (42% of Americans), undiagnosed thyroid disease, chronic inflammation, and hormonal changes all cause bone loss but respond to different treatments. Testing guides targeted intervention.</p>",
        "what-is-included": "<p>Your panel includes vitamin D, calcium, ALP, complete thyroid panel with antibodies, CRP, estradiol, testosterone, complete metabolic panel, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If bone health biomarkers are abnormal, our care team recommends targeted interventions - vitamin D supplementation, thyroid treatment, anti-inflammatory strategies, or DEXA scan referral if you haven't had one. Annual monitoring tracks improvement.</p>",
        "meta-title": "Osteoporosis Blood Test | Bone Biomarkers | Superpower",
        "meta-description": "Test bone health biomarkers - vitamin D, calcium, thyroid, CRP. Find treatable causes of bone loss. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Osteoporosis Blood Test | Bone Biomarkers | Superpower",
        "og-description": "Find out WHY bones are weakening. Vitamin D, calcium, thyroid + 100+ biomarkers. ~10 day results.",
    },
    "gout-biomarker-test": {
        "name": "Gout Biomarker Test",
        "hero-headline": "That Excruciating Joint Pain? Your Uric Acid Level Has the Answer.",
        "hero-subheadline": "<p>Gout is caused by elevated uric acid crystallizing in your joints. A blood test confirms the diagnosis and tracks treatment effectiveness. We test uric acid alongside kidney function, inflammation, and metabolic markers. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Uric Acid Level",
        "primary-keyword": "gout blood test",
        "secondary-keywords": "gout biomarkers, uric acid blood test, gout diagnosis blood test",
        "symptom-headline": "Signs that point to gout",
        "symptom-1": "Sudden, severe joint pain - often in the big toe",
        "symptom-2": "Joint that's red, hot, and swollen overnight",
        "symptom-3": "Pain that peaks within hours and is excruciating",
        "symptom-4": "Recurring attacks that seem triggered by food or alcohol",
        "symptom-5": "Family history of gout or kidney stones",
        "symptom-cta": "Check your uric acid level now ->",
        "stat-1-number": "9.2M",
        "stat-1-text": "Americans have gout - elevated uric acid is detectable on blood work before the first attack",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Woke up with my toe feeling like it was on fire. Uric acid was 9.8 mg/dL. Also found my kidney function was declining and triglycerides were elevated - all connected. Diet changes and medication brought uric acid to 5.2 and I haven't had a flare in a year.</p>",
        "featured-testimonial-name": "James W.",
        "featured-testimonial-result": "Uric acid from 9.8 to 5.2 - no flares for 1 year",
        "membership-subheadline": "Track uric acid and prevent gout flares",
        "membership-benefit-1": "Uric acid plus kidney markers annually",
        "membership-benefit-2": "100+ biomarkers including metabolic panel",
        "membership-benefit-3": "AI tracks uric acid trends and flare risk",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests uric acid, eGFR, creatinine, BUN, CRP, complete metabolic panel, lipid panel, and liver enzymes - the full gout biomarker panel - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Gout doesn't exist in isolation. Elevated uric acid is linked to kidney disease, metabolic syndrome, hypertension, and cardiovascular risk. We test uric acid alongside kidney function, lipids, and inflammation to assess the complete metabolic picture.",
        "how-it-works-3-subheading": "Uric acid above 6.8 mg/dL can crystallize in joints. But many people have elevated levels for years before the first attack. Testing catches hyperuricemia before gout develops, allowing preventive treatment.",
        "how-it-works-4-subheading": "Our clinical team explains your uric acid level in context and recommends dietary changes, hydration strategies, and when to discuss medication with your doctor. Results in about 10 days.",
        "condition-name": "Gout Biomarker Screening",
        "condition-overview": "<p>Gout is a form of inflammatory arthritis caused by uric acid crystals depositing in joints. It affects 9.2 million Americans and is becoming more common. Uric acid levels above 6.8 mg/dL increase crystallization risk. Gout is closely linked to metabolic syndrome, kidney disease, and cardiovascular risk.</p>",
        "why-test": "<p>Uric acid blood testing confirms gout diagnosis, tracks treatment effectiveness, and detects hyperuricemia before the first attack. Testing alongside kidney function and metabolic markers reveals the underlying metabolic dysfunction that drives uric acid elevation.</p>",
        "what-is-included": "<p>Your panel includes uric acid, eGFR, creatinine, BUN, CRP, complete lipid panel, liver enzymes, fasting glucose, insulin, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If uric acid is elevated, our care team recommends dietary modifications (reduce purines, limit alcohol and fructose), hydration strategies, and discusses when urate-lowering therapy may be warranted. Annual monitoring tracks effectiveness.</p>",
        "meta-title": "Gout Blood Test | Uric Acid Biomarkers | Superpower",
        "meta-description": "Test for gout - uric acid + kidney function + metabolic markers. 9.2M Americans affected. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Gout Blood Test | Uric Acid Biomarkers | Superpower",
        "og-description": "Check your uric acid level and kidney function. 100+ biomarkers in one draw. ~10 day results.",
    },
    "hyperuricemia-biomarker-test": {
        "name": "Hyperuricemia Biomarker Test",
        "hero-headline": "High Uric Acid Damages Kidneys and Joints for Years Before Symptoms Appear.",
        "hero-subheadline": "<p>Hyperuricemia - elevated uric acid - increases risk for gout, kidney stones, kidney disease, and cardiovascular events. Most people have no symptoms until damage is done. A blood test catches it early. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Uric Acid Level",
        "primary-keyword": "hyperuricemia blood test",
        "secondary-keywords": "high uric acid test, uric acid level blood test, elevated uric acid screening",
        "symptom-headline": "Risk factors for high uric acid",
        "symptom-1": "Previous blood work showing elevated uric acid",
        "symptom-2": "Diet high in red meat, shellfish, or beer",
        "symptom-3": "Family history of gout or kidney stones",
        "symptom-4": "Taking diuretics or other medications that raise uric acid",
        "symptom-5": "Metabolic syndrome, obesity, or kidney disease",
        "symptom-cta": "Check if your uric acid is silently elevated ->",
        "stat-1-number": "21%",
        "stat-1-text": "of adults have hyperuricemia - most are asymptomatic but at increased risk for gout, kidney stones, and heart disease",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Uric acid was 8.4 on routine blood work. No gout symptoms yet but my doctor said kidney function was starting to decline. Dietary changes and more water brought it to 5.8. Glad I caught it before the first gout attack or kidney stone.</p>",
        "featured-testimonial-name": "Michael R.",
        "featured-testimonial-result": "Uric acid reduced from 8.4 to 5.8 before symptoms appeared",
        "membership-subheadline": "Monitor uric acid before complications develop",
        "membership-benefit-1": "Uric acid plus kidney markers tested annually",
        "membership-benefit-2": "100+ biomarkers including metabolic panel",
        "membership-benefit-3": "AI flags rising uric acid trends early",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests uric acid, eGFR, creatinine, BUN, CRP, complete lipid panel, fasting glucose, insulin, and liver enzymes - all connected to hyperuricemia - plus 90+ other biomarkers. $199/year.",
        "how-it-works-2-subheading": "Hyperuricemia is asymptomatic until it causes gout attacks or kidney stones. But elevated uric acid also independently increases cardiovascular risk and accelerates kidney damage. Testing catches it during the silent phase when dietary changes can prevent complications.",
        "how-it-works-3-subheading": "Uric acid elevation often accompanies metabolic syndrome - insulin resistance, high triglycerides, and hypertension. We test the full metabolic panel alongside uric acid to identify all connected risk factors.",
        "how-it-works-4-subheading": "Our clinical team explains your uric acid level and metabolic context, then recommends dietary modifications and hydration strategies. For persistent elevation, they discuss when medication may be appropriate. Results in about 10 days.",
        "condition-name": "Hyperuricemia Screening",
        "condition-overview": "<p>Hyperuricemia (elevated uric acid above 6.8 mg/dL) affects about 21% of adults. While most people remain asymptomatic, elevated uric acid increases risk for gout, kidney stones, chronic kidney disease, and cardiovascular events. It's closely associated with metabolic syndrome and insulin resistance.</p>",
        "why-test": "<p>Hyperuricemia is a silent condition - most people don't know their uric acid is elevated until a painful gout attack or kidney stone. Blood testing identifies it during the asymptomatic phase when dietary changes and hydration can prevent complications entirely.</p>",
        "what-is-included": "<p>Your panel includes uric acid, eGFR, creatinine, BUN, CRP, fasting glucose, fasting insulin, triglycerides, complete lipid panel, and liver enzymes - 100+ biomarkers total.</p>",
        "next-steps": "<p>If uric acid is elevated, our care team recommends dietary strategies (reduce purines, limit fructose and alcohol, increase hydration), identifies contributing medications, and monitors kidney function. Annual retesting tracks your progress.</p>",
        "meta-title": "High Uric Acid Test | Hyperuricemia Screening | Superpower",
        "meta-description": "Test for hyperuricemia - uric acid + kidney + metabolic markers. 21% of adults affected. Prevent gout and kidney damage. 100+ biomarkers. $199/year.",
        "og-title": "High Uric Acid Test | Hyperuricemia Screening | Superpower",
        "og-description": "Catch high uric acid before gout or kidney stones develop. 100+ biomarkers. ~10 day results.",
    },
    "celiac-disease-biomarker-test": {
        "name": "Celiac Disease Biomarker Test",
        "hero-headline": "Bloating, Fatigue, and Brain Fog After Eating? Your Celiac Biomarkers Have Answers.",
        "hero-subheadline": "<p>Celiac disease causes an immune reaction to gluten that damages your intestines and blocks nutrient absorption. The tTG-IgA antibody test screens for it with high accuracy. Most people with celiac disease are undiagnosed. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen for Celiac Biomarkers",
        "primary-keyword": "celiac disease blood test",
        "secondary-keywords": "celiac biomarkers, tTG-IgA test, celiac screening blood test",
        "symptom-headline": "Signs that could point to celiac disease",
        "symptom-1": "Bloating and digestive issues that worsen after bread or pasta",
        "symptom-2": "Fatigue that doesn't improve regardless of sleep",
        "symptom-3": "Unexplained iron deficiency or anemia",
        "symptom-4": "Brain fog, headaches, or joint pain after eating",
        "symptom-5": "Family history of celiac disease or autoimmune conditions",
        "symptom-cta": "Find out if celiac disease is behind your symptoms ->",
        "stat-1-number": "83%",
        "stat-1-text": "of people with celiac disease are undiagnosed - a simple blood test screens for it accurately",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Years of bloating, fatigue, and iron deficiency. Gastroenterologist said IBS. Superpower found my tTG-IgA was 89 (normal is under 20). Celiac confirmed with biopsy. Gluten-free diet resolved everything within months. One blood test changed my life.</p>",
        "featured-testimonial-name": "David L.",
        "featured-testimonial-result": "Celiac diagnosed after years of IBS misdiagnosis",
        "membership-subheadline": "Screen for celiac and monitor nutrient absorption",
        "membership-benefit-1": "Celiac antibodies plus nutrient markers",
        "membership-benefit-2": "100+ biomarkers including iron, B12, folate",
        "membership-benefit-3": "AI flags celiac-related nutrient deficiencies",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests tTG-IgA (tissue transglutaminase antibody), ANA, ferritin, iron, B12, folate, vitamin D, CBC, and metabolic panel - key celiac biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Celiac disease causes malabsorption - so iron deficiency, B12 deficiency, folate deficiency, and vitamin D deficiency often accompany it. We test these nutritional biomarkers alongside celiac antibodies to reveal both the disease and its downstream effects.",
        "how-it-works-3-subheading": "Important: You must be eating gluten for celiac antibodies to be detectable. If you've already gone gluten-free, antibodies may be falsely negative. Our care team can advise on testing timing.",
        "how-it-works-4-subheading": "If celiac antibodies are elevated, our care team recommends gastroenterology referral for confirmatory biopsy. If negative but symptoms persist, they investigate other causes of your digestive issues. Results in about 10 days.",
        "condition-name": "Celiac Disease Biomarker Screening",
        "condition-overview": "<p>Celiac disease is an autoimmune condition where gluten triggers an immune response that damages the small intestine lining. It affects about 1% of the population, but 83% remain undiagnosed. Blood biomarkers - especially tTG-IgA antibodies - screen with over 95% sensitivity and specificity.</p>",
        "why-test": "<p>Celiac disease is vastly underdiagnosed because symptoms overlap with IBS, food sensitivities, and other conditions. A simple blood test (tTG-IgA) screens with high accuracy. Testing also reveals nutrient deficiencies caused by malabsorption - iron, B12, folate, and vitamin D are commonly depleted in undiagnosed celiac.</p>",
        "what-is-included": "<p>Your panel includes tTG-IgA, ANA, ferritin, iron, TIBC, vitamin B12, folate, vitamin D, CBC with differential, CRP, complete metabolic panel, and liver enzymes - 100+ biomarkers total.</p>",
        "next-steps": "<p>If celiac antibodies are elevated, gastroenterology referral for confirmatory endoscopy/biopsy is recommended. Our care team also addresses any nutrient deficiencies identified on the panel and provides guidance on the gluten-free diet transition.</p>",
        "meta-title": "Celiac Disease Blood Test | tTG-IgA Screening | Superpower",
        "meta-description": "Screen for celiac disease - tTG-IgA antibodies + nutrient markers. 83% of celiac cases undiagnosed. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Celiac Disease Blood Test | tTG-IgA Screening | Superpower",
        "og-description": "Screen for celiac with tTG-IgA + iron, B12, folate, vitamin D. 100+ biomarkers. ~10 day results.",
    },
    "systemic-lupus-erythematosus-biomarker-test": {
        "name": "Lupus (SLE) Biomarker Test",
        "hero-headline": "Lupus Takes an Average of 6 Years to Diagnose. ANA Testing Speeds That Up.",
        "hero-subheadline": "<p>Systemic lupus erythematosus (SLE) is notoriously difficult to diagnose because symptoms mimic dozens of other conditions. ANA, CBC, CRP, and kidney markers provide critical screening data. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen for Lupus Biomarkers",
        "primary-keyword": "lupus blood test",
        "secondary-keywords": "lupus biomarkers, ANA test lupus, SLE blood test",
        "symptom-headline": "Signs that warrant lupus biomarker screening",
        "symptom-1": "Joint pain and fatigue that come and go unpredictably",
        "symptom-2": "Butterfly-shaped rash across the nose and cheeks",
        "symptom-3": "Sensitivity to sunlight causing rashes or fatigue",
        "symptom-4": "Unexplained fevers, hair loss, or mouth sores",
        "symptom-5": "Multiple autoimmune symptoms that don't fit one diagnosis",
        "symptom-cta": "Get the lupus screening blood work ->",
        "stat-1-number": "1.5M",
        "stat-1-text": "Americans have lupus - average diagnosis takes 6 years and 4 doctors because symptoms mimic so many conditions",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Joint pain, fatigue, and random fevers for 3 years. Told it was fibromyalgia. Superpower found my ANA was strongly positive, CRP was 6.8, and my white blood cells were low. Rheumatologist confirmed lupus within 2 weeks. Three years of misdiagnosis ended.</p>",
        "featured-testimonial-name": "Maria G.",
        "featured-testimonial-result": "Lupus diagnosed after 3 years of fibromyalgia misdiagnosis",
        "membership-subheadline": "Screen for lupus and track autoimmune markers",
        "membership-benefit-1": "ANA, CRP, and CBC - key lupus screening markers",
        "membership-benefit-2": "100+ biomarkers including kidney and liver",
        "membership-benefit-3": "AI flags autoimmune patterns across markers",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ANA (antinuclear antibodies), CRP, CBC with differential, eGFR, creatinine, and metabolic panel - the initial lupus screening biomarkers - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Lupus affects multiple organ systems. ANA screens for autoimmune activity. CBC often shows low white blood cells or platelets. CRP measures inflammation. Kidney markers (eGFR, creatinine) check for lupus nephritis. Testing these together creates the clinical picture that leads to diagnosis.",
        "how-it-works-3-subheading": "Note: ANA is a screening test - a positive ANA doesn't confirm lupus (it occurs in 15% of healthy people). But combined with clinical symptoms and other biomarkers, it's an essential first step. Our panel provides the initial data; a rheumatologist orders definitive tests (anti-dsDNA, anti-Smith).",
        "how-it-works-4-subheading": "Our clinical team explains your autoimmune biomarkers in context. If screening markers suggest lupus, they recommend rheumatology referral for definitive testing. Results in about 10 days.",
        "condition-name": "Lupus (SLE) Biomarker Screening",
        "condition-overview": "<p>Systemic lupus erythematosus (SLE) is a chronic autoimmune disease affecting 1.5 million Americans. The immune system attacks healthy tissue in the joints, skin, kidneys, brain, and other organs. It's notoriously difficult to diagnose - averaging 6 years and 4 doctors - because symptoms mimic many other conditions.</p>",
        "why-test": "<p>Blood biomarkers accelerate lupus diagnosis. ANA is positive in 97% of lupus cases. Low white blood cells, low platelets, elevated CRP, and abnormal kidney markers add specificity. While definitive diagnosis requires specialist testing, screening biomarkers determine whether a rheumatology referral is warranted - potentially saving years of misdiagnosis.</p>",
        "what-is-included": "<p>Your panel includes ANA, CRP, CBC with differential, eGFR, creatinine, BUN, liver enzymes, complete metabolic panel, thyroid panel, and vitamin D - 100+ biomarkers total. Note: Anti-dsDNA and anti-Smith (definitive lupus markers) require specialist ordering.</p>",
        "next-steps": "<p>If ANA is positive with supporting biomarkers and clinical symptoms, our care team recommends rheumatology referral for definitive lupus testing. Early diagnosis and treatment significantly improve outcomes and prevent organ damage.</p>",
        "meta-title": "Lupus Blood Test | ANA + Autoimmune Screening | Superpower",
        "meta-description": "Screen for lupus (SLE) - ANA, CRP, CBC, kidney markers. Lupus takes 6 years to diagnose on average. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Lupus Blood Test | ANA + Autoimmune Screening | Superpower",
        "og-description": "Screen for lupus with ANA + CRP + CBC + 100+ biomarkers. Speed up diagnosis. ~10 day results.",
    },
    "dyslipidemia-biomarker-test": {
        "name": "Dyslipidemia Biomarker Test",
        "hero-headline": "Your Cholesterol Is 'Normal.' But Your ApoB Says Otherwise.",
        "hero-subheadline": "<p>Standard cholesterol panels miss the markers that actually predict heart attacks. ApoB, Lp(a), triglyceride-to-HDL ratio, and hsCRP reveal your true cardiovascular risk. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Get Advanced Lipid Biomarkers",
        "primary-keyword": "dyslipidemia blood test",
        "secondary-keywords": "lipid panel biomarkers, advanced cholesterol test, dyslipidemia screening",
        "symptom-headline": "When advanced lipid testing matters",
        "symptom-1": "Family history of heart attacks - especially before 60",
        "symptom-2": "Previous cholesterol results that were 'borderline'",
        "symptom-3": "High cholesterol that hasn't responded to diet or statins",
        "symptom-4": "Metabolic syndrome, diabetes, or insulin resistance",
        "symptom-5": "Family history of high cholesterol across generations",
        "symptom-cta": "Get the lipid biomarkers cardiologists actually want ->",
        "stat-1-number": "50%",
        "stat-1-text": "of heart attack victims had normal LDL cholesterol - advanced biomarkers like ApoB catch what standard panels miss",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Total cholesterol was 195, LDL was 118 - both 'normal.' But ApoB was 135 (high risk) and Lp(a) was 210 nmol/L. Genetic risk nobody ever tested for. Cardiologist said this finding likely prevented a heart attack in my 50s.</p>",
        "featured-testimonial-name": "Tom R.",
        "featured-testimonial-result": "Hidden genetic cardiovascular risk caught by advanced biomarkers",
        "membership-subheadline": "Know your true cardiovascular biomarker profile",
        "membership-benefit-1": "ApoB, Lp(a), and advanced lipids annually",
        "membership-benefit-2": "100+ biomarkers including inflammation markers",
        "membership-benefit-3": "AI calculates true cardiovascular risk score",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ApoB, Lp(a), total cholesterol, LDL, HDL, triglycerides, VLDL, non-HDL cholesterol, hsCRP, and homocysteine - the advanced lipid biomarker panel - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "ApoB counts the actual number of artery-damaging particles - more predictive than LDL concentration. Lp(a) is a genetic risk factor carried by 20% of people that diet and exercise can't change. hsCRP measures the vascular inflammation that accelerates plaque buildup. Standard panels test none of these.",
        "how-it-works-3-subheading": "We analyze lipid biomarkers alongside insulin, liver enzymes, and thyroid - because metabolic dysfunction, fatty liver, and hypothyroidism all worsen lipid profiles. Treating the underlying cause is more effective than just prescribing statins.",
        "how-it-works-4-subheading": "Our clinical team explains your complete cardiovascular biomarker profile and recommends next steps - dietary changes, exercise, statin consideration, or cardiology referral. Results in about 10 days.",
        "condition-name": "Dyslipidemia Biomarker Screening",
        "condition-overview": "<p>Dyslipidemia - abnormal cholesterol and lipid levels - is a major risk factor for heart disease and stroke. Standard lipid panels (total cholesterol, LDL, HDL, triglycerides) miss critical biomarkers. ApoB, Lp(a), and inflammatory markers provide a far more accurate cardiovascular risk assessment.</p>",
        "why-test": "<p>Half of all heart attacks occur in people with 'normal' LDL cholesterol. Advanced lipid biomarkers - ApoB, Lp(a), and hsCRP - catch the risk that standard panels miss. Lp(a) only needs to be tested once (it's genetic). ApoB and hsCRP should be monitored annually for anyone with cardiovascular risk factors.</p>",
        "what-is-included": "<p>Your panel includes ApoB, Lp(a), total cholesterol, LDL, HDL, triglycerides, VLDL, non-HDL cholesterol, hsCRP, homocysteine, fasting insulin, liver enzymes, and thyroid - 100+ biomarkers total.</p>",
        "next-steps": "<p>If advanced lipid biomarkers are elevated, our care team explains your true cardiovascular risk and recommends targeted interventions - dietary changes, exercise, statin discussion, or cardiology referral for calcium scoring.</p>",
        "meta-title": "Dyslipidemia Blood Test | ApoB + Advanced Lipids | Superpower",
        "meta-description": "Advanced lipid biomarker test - ApoB, Lp(a), hsCRP, full lipid panel. Catches heart risk standard tests miss. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Dyslipidemia Blood Test | ApoB + Advanced Lipids | Superpower",
        "og-description": "Your LDL is normal but ApoB may tell a different story. Advanced lipid biomarkers + 100+ markers. ~10 day results.",
    },
    "coronary-artery-disease-biomarker-test": {
        "name": "Coronary Artery Disease Biomarker Test",
        "hero-headline": "Heart Disease Builds Silently for Decades. These Biomarkers Catch It.",
        "hero-subheadline": "<p>Coronary artery disease is the #1 killer worldwide - and blood biomarkers detect the risk factors decades before a heart attack. ApoB, Lp(a), hsCRP, lipids, and metabolic markers together predict cardiovascular events far better than cholesterol alone. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen for Heart Disease Biomarkers",
        "primary-keyword": "coronary artery disease blood test",
        "secondary-keywords": "heart disease biomarkers, cardiac risk blood test, CAD screening biomarkers",
        "symptom-headline": "When cardiac biomarker screening is critical",
        "symptom-1": "Family history of heart attacks or coronary artery disease",
        "symptom-2": "High cholesterol that hasn't responded to treatment",
        "symptom-3": "Diabetes, metabolic syndrome, or insulin resistance",
        "symptom-4": "High blood pressure or history of smoking",
        "symptom-5": "Chest tightness or shortness of breath with exertion",
        "symptom-cta": "Get the cardiac biomarkers cardiologists recommend ->",
        "stat-1-number": "#1",
        "stat-1-text": "cause of death worldwide - heart disease kills more than all cancers combined, but blood biomarkers catch risk factors decades early",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Dad had a heart attack at 54. My cholesterol was 'normal.' Superpower found my Lp(a) was 195 nmol/L - high genetic risk - and ApoB was 128. Cardiologist started aggressive prevention. Blood biomarkers caught what runs in my family before it caught me.</p>",
        "featured-testimonial-name": "Daniel P.",
        "featured-testimonial-result": "Genetic heart risk identified 20+ years before potential event",
        "membership-subheadline": "Monitor cardiac biomarkers and prevent heart disease",
        "membership-benefit-1": "ApoB, Lp(a), hsCRP, and lipids annually",
        "membership-benefit-2": "100+ biomarkers including metabolic markers",
        "membership-benefit-3": "AI tracks cardiovascular risk over time",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ApoB, Lp(a), LDL, HDL, triglycerides, hsCRP, homocysteine, fasting insulin, HbA1c, and liver enzymes - the biomarkers that predict coronary artery disease - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Coronary artery disease develops over decades as plaque builds in arteries. ApoB measures atherogenic particles. Lp(a) reveals inherited risk. hsCRP detects vascular inflammation. Insulin resistance and metabolic markers show metabolic drivers. Together they predict events far better than LDL alone.",
        "how-it-works-3-subheading": "We analyze cardiac biomarkers alongside metabolic health because insulin resistance, diabetes, and fatty liver all accelerate coronary artery disease. Treating the metabolic root cause - not just prescribing statins - provides better long-term protection.",
        "how-it-works-4-subheading": "Our clinical team provides a comprehensive cardiovascular risk assessment and recommends next steps - lifestyle changes, medication discussion, or cardiology referral for imaging (coronary calcium scoring). Results in about 10 days.",
        "condition-name": "Coronary Artery Disease Biomarker Screening",
        "condition-overview": "<p>Coronary artery disease (CAD) occurs when plaque builds up in the coronary arteries, restricting blood flow to the heart. It's the leading cause of death worldwide. CAD develops silently over decades - blood biomarkers detect the risk factors that drive plaque formation long before symptoms or events occur.</p>",
        "why-test": "<p>Standard cholesterol panels miss half the risk. ApoB, Lp(a), and hsCRP predict coronary events far more accurately than LDL alone. Lp(a) is genetic and immutable - but knowing you have it allows aggressive prevention. Annual monitoring of ApoB, lipids, and metabolic markers tracks whether your prevention strategy is working.</p>",
        "what-is-included": "<p>Your panel includes ApoB, Lp(a), complete lipid panel, hsCRP, homocysteine, fasting insulin, HbA1c, fasting glucose, liver enzymes, kidney function, thyroid, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If cardiac biomarkers indicate elevated risk, our care team recommends lifestyle modifications, discusses statin and other medication options, and refers to cardiology for imaging or advanced evaluation when appropriate.</p>",
        "meta-title": "Heart Disease Biomarkers | ApoB, Lp(a), CRP | Superpower",
        "meta-description": "Screen for coronary artery disease - ApoB, Lp(a), hsCRP, lipids, metabolic markers. #1 cause of death. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Heart Disease Biomarkers | ApoB, Lp(a), CRP | Superpower",
        "og-description": "Catch heart disease risk decades early. ApoB, Lp(a) + 100+ biomarkers. ~10 day results.",
    },
    "hypertension-biomarker-test": {
        "name": "Hypertension Biomarker Test",
        "hero-headline": "High Blood Pressure Has Root Causes. Your Biomarkers Can Find Them.",
        "hero-subheadline": "<p>Hypertension isn't just a number on a cuff - it's driven by kidney dysfunction, insulin resistance, electrolyte imbalances, and thyroid problems. Blood biomarkers identify the treatable causes behind your elevated pressure. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Hypertension Biomarkers",
        "primary-keyword": "hypertension blood test",
        "secondary-keywords": "high blood pressure blood test, hypertension biomarkers, blood pressure causes blood test",
        "symptom-headline": "When blood work should accompany blood pressure treatment",
        "symptom-1": "Blood pressure elevated despite medication",
        "symptom-2": "New hypertension diagnosis without root cause investigation",
        "symptom-3": "Family history of high blood pressure and kidney disease",
        "symptom-4": "Metabolic syndrome, diabetes, or obesity alongside hypertension",
        "symptom-5": "Young onset hypertension (before age 40)",
        "symptom-cta": "Find the root cause driving your blood pressure ->",
        "stat-1-number": "47%",
        "stat-1-text": "of American adults have hypertension - blood biomarkers reveal treatable root causes that medication alone doesn't address",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>On 2 blood pressure medications and still running 140/90. Superpower found my fasting insulin was 22, kidney function was declining, and thyroid was borderline. Addressing the insulin resistance and thyroid brought my BP to 125/80 and I dropped one medication.</p>",
        "featured-testimonial-name": "Steve H.",
        "featured-testimonial-result": "Dropped 1 BP medication after treating root causes",
        "membership-subheadline": "Find and track the causes behind high blood pressure",
        "membership-benefit-1": "Kidney, metabolic, and thyroid markers yearly",
        "membership-benefit-2": "100+ biomarkers including electrolytes",
        "membership-benefit-3": "AI identifies root cause patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests eGFR, creatinine, sodium, potassium, fasting insulin, HbA1c, thyroid panel, lipid panel, uric acid, and CRP - biomarkers connected to hypertension - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Hypertension has multiple causes: kidney disease (eGFR decline), insulin resistance (hyperinsulinemia increases sodium retention), thyroid dysfunction, and electrolyte imbalances. Treating the underlying cause is more effective than adding more blood pressure medications.",
        "how-it-works-3-subheading": "Hypertension is a major risk factor for heart attack, stroke, and kidney failure. We test cardiac biomarkers (lipids, hsCRP) and kidney markers alongside blood pressure-related biomarkers to assess your total cardiovascular risk.",
        "how-it-works-4-subheading": "Our clinical team identifies which biomarkers may be driving your hypertension and recommends targeted interventions beyond just medication - addressing insulin resistance, optimizing thyroid, and improving kidney health. Results in about 10 days.",
        "condition-name": "Hypertension Biomarker Screening",
        "condition-overview": "<p>Hypertension (high blood pressure) affects 47% of American adults and is a leading risk factor for heart attack, stroke, and kidney failure. While medication controls the number, blood biomarkers reveal the underlying causes - kidney dysfunction, insulin resistance, thyroid disorders, and electrolyte imbalances - that targeted treatment can address.</p>",
        "why-test": "<p>Blood pressure medications control the symptom but don't always address the cause. Kidney function (eGFR) should be monitored in all hypertension patients. Fasting insulin reveals insulin resistance - a major driver of hypertension. Thyroid dysfunction and electrolyte imbalances are treatable causes often missed. Biomarker testing transforms hypertension treatment from guesswork to targeted care.</p>",
        "what-is-included": "<p>Your panel includes eGFR, creatinine, BUN, sodium, potassium, fasting insulin, HbA1c, complete lipid panel, thyroid panel, uric acid, CRP, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>If hypertension-driving biomarkers are identified, our care team recommends targeted interventions - addressing insulin resistance, thyroid optimization, kidney protection strategies, or specialist referral for resistant hypertension.</p>",
        "meta-title": "Hypertension Blood Test | Root Cause Biomarkers | Superpower",
        "meta-description": "Find the root cause of high blood pressure - kidney, insulin, thyroid, electrolyte biomarkers. 47% of adults affected. 100+ biomarkers. $199/year.",
        "og-title": "Hypertension Blood Test | Root Cause Biomarkers | Superpower",
        "og-description": "Blood pressure elevated? Find the root cause with biomarker testing. 100+ markers. ~10 day results.",
    },
    "menopause-biomarker-test": {
        "name": "Menopause Biomarker Test",
        "hero-headline": "Is It Menopause, Your Thyroid, or Both? Your Biomarkers Know.",
        "hero-subheadline": "<p>Hot flashes, mood swings, weight gain, and fatigue overlap between menopause and thyroid disease. FSH, estradiol, and a full thyroid panel tell you which is driving your symptoms - because the treatment is completely different. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Menopause Biomarkers",
        "primary-keyword": "menopause blood test",
        "secondary-keywords": "menopause biomarkers, FSH test menopause, hormone levels menopause",
        "symptom-headline": "Symptoms that need biomarker clarity",
        "symptom-1": "Hot flashes, night sweats, and sleep disruption",
        "symptom-2": "Weight gain concentrated around the midsection",
        "symptom-3": "Mood changes, anxiety, or depression that started recently",
        "symptom-4": "Brain fog and memory issues that feel new",
        "symptom-5": "Irregular periods transitioning to no periods",
        "symptom-cta": "Find out what's really driving your symptoms ->",
        "stat-1-number": "1.3M",
        "stat-1-text": "women enter menopause each year in the US - thyroid disease mimics the symptoms in 1 out of 8 women over 50",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Assumed it was menopause - hot flashes, weight gain, fatigue. Superpower showed FSH was elevated (yes, perimenopause) but my thyroid antibodies were also 280 and vitamin D was 19. Three things going on at once. Treating all three made a bigger difference than just accepting 'it's menopause.'</p>",
        "featured-testimonial-name": "Susan T.",
        "featured-testimonial-result": "Menopause + Hashimoto's + vitamin D deficiency - all identified",
        "membership-subheadline": "Track hormones through the menopause transition",
        "membership-benefit-1": "FSH, estradiol, and thyroid tested annually",
        "membership-benefit-2": "100+ biomarkers including bone and heart markers",
        "membership-benefit-3": "AI tracks hormonal transition patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests FSH, estradiol, testosterone, DHEA, complete thyroid panel with antibodies, vitamin D, calcium, lipid panel, and insulin - the complete menopause biomarker panel - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Menopause and thyroid disease share nearly identical symptoms. FSH and estradiol confirm menopausal status. Thyroid markers rule out (or confirm) coexisting thyroid disease. Testing both prevents years of attributing thyroid symptoms to 'just menopause.'",
        "how-it-works-3-subheading": "Menopause increases risk for osteoporosis, heart disease, and metabolic changes. We test vitamin D, calcium, lipids, and insulin to assess these emerging risks during the transition. Prevention is far easier than treatment.",
        "how-it-works-4-subheading": "Our clinical team explains your hormonal status and associated risk factors. They discuss HRT considerations, bone health protection, cardiovascular prevention, and thyroid management if needed. Results in about 10 days.",
        "condition-name": "Menopause Biomarker Screening",
        "condition-overview": "<p>Menopause marks the end of reproductive years, typically occurring between ages 45-55. Declining estrogen causes hot flashes, mood changes, sleep disruption, and increased risk for osteoporosis and heart disease. Blood biomarkers confirm menopausal status and assess related health risks. Importantly, thyroid disease - which affects 1 in 8 women over 50 - mimics menopause symptoms almost exactly.</p>",
        "why-test": "<p>Menopause symptoms overlap extensively with thyroid disease, vitamin D deficiency, and iron depletion. Biomarker testing distinguishes between these conditions so each gets proper treatment. It also establishes baseline cardiovascular and bone health markers during the transition, when risk profiles change significantly.</p>",
        "what-is-included": "<p>Your panel includes FSH, estradiol, testosterone, DHEA, complete thyroid panel with antibodies, vitamin D, calcium, complete lipid panel, fasting insulin, CRP, and CBC - 100+ biomarkers total.</p>",
        "next-steps": "<p>Our care team explains your hormonal status and risk profile, discusses HRT options if appropriate, and recommends preventive strategies for bone and heart health. Annual monitoring tracks the transition and catches emerging risks early.</p>",
        "meta-title": "Menopause Blood Test | FSH + Hormones + Thyroid | Superpower",
        "meta-description": "Menopause biomarker test - FSH, estradiol, thyroid, vitamin D. Is it menopause, thyroid, or both? 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Menopause Blood Test | FSH + Hormones + Thyroid | Superpower",
        "og-description": "Menopause or thyroid? Biomarkers tell the difference. FSH + hormones + 100+ markers. ~10 day results.",
    },
    "male-hypogonadism-biomarker-test": {
        "name": "Male Hypogonadism (Low T) Biomarker Test",
        "hero-headline": "Your Doctor Tests Total T. That Misses Half the Picture.",
        "hero-subheadline": "<p>Male hypogonadism (low testosterone) requires more than just a total T test. Free testosterone, SHBG, LH, and FSH distinguish between true deficiency and other causes of your symptoms. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Get Complete Testosterone Biomarkers",
        "primary-keyword": "low testosterone blood test",
        "secondary-keywords": "male hypogonadism test, testosterone biomarkers, low T blood test",
        "symptom-headline": "Symptoms of low testosterone in men",
        "symptom-1": "Low energy and motivation that won't improve",
        "symptom-2": "Decreased sex drive and erectile difficulties",
        "symptom-3": "Loss of muscle mass and increased body fat",
        "symptom-4": "Brain fog, irritability, or depressed mood",
        "symptom-5": "Previous total T test was 'normal' but symptoms persist",
        "symptom-cta": "Get the full testosterone biomarker panel ->",
        "stat-1-number": "40%",
        "stat-1-text": "of men over 45 have low testosterone - but testing only total T misses those with normal total T but low free T",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Total testosterone was 480 - 'normal.' But my free testosterone was 5.2 pg/mL - bottom of the range. SHBG was sky high, binding up all my testosterone. Once that was addressed, energy, libido, and brain fog all improved dramatically.</p>",
        "featured-testimonial-name": "Mark D.",
        "featured-testimonial-result": "Low free T identified despite normal total T",
        "membership-subheadline": "Track testosterone and hormone biomarkers over time",
        "membership-benefit-1": "Total T, free T, SHBG, and LH annually",
        "membership-benefit-2": "100+ biomarkers including thyroid and metabolic",
        "membership-benefit-3": "AI tracks testosterone trends by age",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests total testosterone, free testosterone, SHBG, LH, FSH, estradiol, DHEA, thyroid panel, and cortisol - the complete male hormone biomarker panel - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Total testosterone doesn't tell you how much is biologically active. SHBG binds testosterone, making it unavailable. LH and FSH distinguish primary (testicular) from secondary (pituitary) hypogonadism. Estradiol elevation can suppress testosterone. The full panel identifies the mechanism.",
        "how-it-works-3-subheading": "Thyroid dysfunction, iron deficiency, and sleep disorders all lower testosterone. We test these cofactors alongside hormones because treating the underlying cause is often more effective than just prescribing TRT.",
        "how-it-works-4-subheading": "Our clinical team explains your testosterone biomarkers in context - not just whether total T is in range. They recommend next steps including lifestyle optimization, addressing cofactors, or urology/endocrinology referral. Results in about 10 days.",
        "condition-name": "Male Hypogonadism Biomarker Screening",
        "condition-overview": "<p>Male hypogonadism (low testosterone) affects up to 40% of men over 45. It causes fatigue, low libido, muscle loss, mood changes, and cognitive decline. Diagnosis requires comprehensive hormone biomarker testing - total testosterone alone is insufficient because SHBG, free testosterone, and gonadotropins provide essential diagnostic context.</p>",
        "why-test": "<p>A total testosterone test misses men with normal total T but low free T (high SHBG binding). It also doesn't distinguish between primary hypogonadism (testicular) and secondary (pituitary) - which determines treatment approach. LH, FSH, SHBG, and free testosterone are essential for accurate diagnosis and treatment planning.</p>",
        "what-is-included": "<p>Your panel includes total testosterone, free testosterone, SHBG, LH, FSH, estradiol, DHEA, prolactin, thyroid panel, cortisol, CBC, lipid panel, and metabolic panel - 100+ biomarkers total.</p>",
        "next-steps": "<p>If testosterone biomarkers indicate hypogonadism, our care team explains the type (primary vs secondary), discusses treatment options (lifestyle optimization, clomiphene, or TRT), and recommends urology or endocrinology referral when appropriate.</p>",
        "meta-title": "Low Testosterone Test | Male Hormone Biomarkers | Superpower",
        "meta-description": "Complete low T biomarker test - total T, free T, SHBG, LH, FSH. Total T alone misses half the picture. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Low Testosterone Test | Male Hormone Biomarkers | Superpower",
        "og-description": "Total T is 'normal' but symptoms persist? Free T and SHBG tell the real story. 100+ biomarkers. ~10 day results.",
    },
    "female-hypogonadism-biomarker-test": {
        "name": "Female Hormone Deficiency Biomarker Test",
        "hero-headline": "Fatigue, Low Libido, and Mood Swings Aren't 'Just Stress.' Test Your Hormones.",
        "hero-subheadline": "<p>Female hormone deficiency affects energy, mood, sex drive, and bone health - yet many women are told their symptoms are stress or aging. Estradiol, FSH, testosterone, DHEA, and thyroid biomarkers reveal the full hormonal picture. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Hormone Biomarkers",
        "primary-keyword": "female hormone blood test",
        "secondary-keywords": "female hypogonadism test, women's hormone panel, estrogen test",
        "symptom-headline": "Signs of hormonal imbalance in women",
        "symptom-1": "Fatigue and low energy that doesn't match your lifestyle",
        "symptom-2": "Decreased sex drive that's affecting your relationship",
        "symptom-3": "Mood swings, anxiety, or depression that feel hormonal",
        "symptom-4": "Irregular or absent periods outside of menopause age",
        "symptom-5": "Bone density concerns or early osteopenia",
        "symptom-cta": "Find out if hormones are driving your symptoms ->",
        "stat-1-number": "1 in 4",
        "stat-1-text": "women experience significant hormonal deficiency symptoms - most are attributed to stress, aging, or depression instead of being tested",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Exhausted, no sex drive, crying at nothing. Doctor said 'it's stress.' Superpower found my estradiol was rock bottom, testosterone was undetectable, and DHEA was low. Hormones were tanked across the board. Treatment brought me back to myself within 6 weeks.</p>",
        "featured-testimonial-name": "Amanda C.",
        "featured-testimonial-result": "3 hormone deficiencies identified - symptoms resolved in 6 weeks",
        "membership-subheadline": "Track your complete hormone profile over time",
        "membership-benefit-1": "Estradiol, testosterone, DHEA, and FSH annually",
        "membership-benefit-2": "100+ biomarkers including thyroid and vitamins",
        "membership-benefit-3": "AI tracks hormone trends across cycles",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests estradiol, FSH, LH, total testosterone, free testosterone, DHEA-S, SHBG, progesterone, prolactin, and complete thyroid panel - the full female hormone biomarker panel - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Women's hormonal health involves more than just estrogen. Testosterone and DHEA affect energy, libido, and mood. Thyroid dysfunction mimics hormonal deficiency perfectly. We test the complete picture so the right condition gets treated.",
        "how-it-works-3-subheading": "Iron deficiency, vitamin D deficiency, and B12 deficiency all worsen hormonal symptoms. We test nutritional biomarkers alongside hormones because addressing deficiencies often improves symptoms even before hormonal treatment.",
        "how-it-works-4-subheading": "Our clinical team explains your complete hormonal profile and recommends next steps - lifestyle optimization, supplementation, hormone therapy discussion, or specialist referral. Results in about 10 days.",
        "condition-name": "Female Hormone Deficiency Screening",
        "condition-overview": "<p>Female hypogonadism encompasses conditions where the ovaries produce insufficient hormones - estrogen, progesterone, and testosterone. It can result from premature ovarian insufficiency, hypothalamic dysfunction, or natural menopause. Symptoms include fatigue, low libido, mood changes, irregular periods, and increased bone loss risk.</p>",
        "why-test": "<p>Hormonal symptoms in women are frequently dismissed as stress, depression, or normal aging. Blood biomarkers definitively measure hormone levels and distinguish between ovarian failure (high FSH), pituitary dysfunction (low FSH), thyroid disease, and nutritional deficiencies - all of which cause similar symptoms but require different treatments.</p>",
        "what-is-included": "<p>Your panel includes estradiol, FSH, LH, total testosterone, free testosterone, DHEA-S, SHBG, prolactin, complete thyroid panel with antibodies, vitamin D, ferritin, B12, and CRP - 100+ biomarkers total.</p>",
        "next-steps": "<p>If hormone biomarkers reveal deficiency, our care team explains the type (ovarian vs pituitary vs nutritional) and recommends next steps - hormone therapy discussion, addressing nutritional cofactors, or gynecology/endocrinology referral.</p>",
        "meta-title": "Female Hormone Test | Estradiol, FSH, Testosterone | Superpower",
        "meta-description": "Female hormone biomarker test - estradiol, FSH, testosterone, DHEA, thyroid. Not just stress. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Female Hormone Test | Estradiol, FSH, Testosterone | Superpower",
        "og-description": "Test your complete hormone profile. Estradiol, testosterone, thyroid + 100+ biomarkers. ~10 day results.",
    },
}


def fetch_all_pages():
    all_items = []
    offset = 0
    while True:
        url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items?limit=100&offset={offset}"
        resp = requests.get(url, headers=HEADERS)
        data = resp.json()
        items = data.get("items", [])
        all_items.extend(items)
        total = data.get("pagination", {}).get("total", 0)
        if offset + 100 >= total:
            break
        offset += 100
        time.sleep(0.3)
    return all_items


def main():
    print("=" * 70)
    print("BATCH 3: Rewrite 13 Tier 1 Biomarker-Test Pages (Part B)")
    print("=" * 70)

    print("\nFetching all pages...")
    all_items = fetch_all_pages()
    slug_map = {}
    for item in all_items:
        slug = item.get("fieldData", {}).get("slug", "")
        if slug:
            slug_map[slug] = item

    results = []
    for slug, fields in REWRITES.items():
        if slug not in slug_map:
            print(f"\n  SKIP: {slug} not found")
            results.append({"slug": slug, "status": "NOT_FOUND"})
            continue

        item_id = slug_map[slug]["id"]
        print(f"\n  REWRITING: {slug}")

        url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items/{item_id}"
        resp = requests.patch(url, headers=HEADERS, json={"fieldData": fields})
        if resp.status_code == 200:
            print(f"    Updated: {fields['meta-title']}")
            results.append({"slug": slug, "item_id": item_id, "status": "UPDATED", "meta_title": fields["meta-title"]})
        else:
            print(f"    ERROR: {resp.status_code} {resp.text[:200]}")
            results.append({"slug": slug, "item_id": item_id, "status": "ERROR"})
        time.sleep(0.4)

    updated_ids = [r["item_id"] for r in results if r["status"] == "UPDATED"]
    if updated_ids:
        print(f"\nPublishing {len(updated_ids)} pages...")
        for i in range(0, len(updated_ids), 100):
            batch = updated_ids[i:i+100]
            url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items/publish"
            resp = requests.post(url, headers=HEADERS, json={"itemIds": batch})
            print(f"  Publish: {resp.status_code}")

    print(f"\n{'=' * 70}")
    print("SUMMARY")
    for r in results:
        print(f"  {r['slug']}: {r['status']}")

    with open("/Users/jeffy/superpower-sem-gap/app/data/biomarker_rewrite_batch3.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nSaved to biomarker_rewrite_batch3.json")


if __name__ == "__main__":
    main()
