#!/usr/bin/env python3
"""Batch 5: Rewrite 12 Tier 2 biomarker-test pages.
Alcoholic liver disease, cholestasis, CFS/ME, hyperprolactinemia,
female infertility, male infertility, pancreatitis, BPH,
Cushing's syndrome, Addison's disease, subclinical hyperthyroidism, osteomalacia."""
import requests
import time
import json

API_KEY = "87be5982f1938a9143a7368af984a9863971dd55314fd5a60f482cc02425a0c7"
LP_COLLECTION = "6981a714e199bac70776d880"
HEADERS = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}

REWRITES = {
    "alcoholic-liver-disease-biomarker-test": {
        "name": "Alcoholic Liver Disease Biomarker Test",
        "hero-headline": "Your Liver Keeps Score. GGT and AST/ALT Tell You the Damage.",
        "hero-subheadline": "<p>Alcohol damages the liver silently for years before symptoms appear. GGT, AST, ALT, and their ratios reveal how much damage has already occurred - and whether it's reversible. No judgment, just data. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Check Your Liver Biomarkers",
        "primary-keyword": "alcoholic liver disease blood test",
        "secondary-keywords": "GGT test alcohol, liver damage blood test, AST ALT ratio alcohol, liver enzyme test",
        "symptom-headline": "Signs alcohol may be affecting your liver",
        "symptom-1": "Fatigue that's getting worse over the past year",
        "symptom-2": "Abdominal discomfort or bloating after drinking",
        "symptom-3": "Drinking regularly and wondering what it's doing to your body",
        "symptom-4": "Yellowing of skin or eyes - even slightly",
        "symptom-5": "Unexplained nausea or loss of appetite",
        "symptom-cta": "Find out if alcohol is damaging your liver ->",
        "stat-1-number": "1 in 3",
        "stat-1-text": "heavy drinkers develop liver disease - but elevated liver enzymes are detectable long before symptoms appear",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Drank socially for 20 years - never thought twice about it. GGT was 187 (normal is under 55) and AST/ALT ratio was 2.3. Doctor said my liver was inflamed and showing early fibrosis signs. Six months sober and GGT dropped to 42. Caught it before permanent damage.</p>",
        "featured-testimonial-name": "Greg T.",
        "featured-testimonial-result": "GGT from 187 to 42 after six months of sobriety",
        "membership-subheadline": "Track liver recovery and long-term health",
        "membership-benefit-1": "GGT, AST, ALT, and bilirubin tested annually",
        "membership-benefit-2": "100+ biomarkers including metabolic panel",
        "membership-benefit-3": "AI tracks liver enzyme trends over time",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests GGT, AST, ALT, ALP, bilirubin (direct and total), albumin, total protein, complete metabolic panel, CBC, and lipid panel - the biomarkers that reveal alcohol-related liver damage - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "GGT is the most sensitive marker for alcohol-related liver damage - it rises before other enzymes. The AST/ALT ratio above 2.0 is a strong indicator of alcoholic hepatitis. Albumin and bilirubin show whether liver function is compromised. We analyze all of these together for the complete picture.",
        "how-it-works-3-subheading": "Alcohol also damages the metabolic system. We test fasting glucose, triglycerides, and inflammatory markers alongside liver enzymes because alcohol-related liver disease rarely exists in isolation - it affects blood sugar regulation, lipid metabolism, and systemic inflammation.",
        "how-it-works-4-subheading": "Our clinical team explains your liver biomarkers honestly and clearly. If enzymes are elevated, they recommend next steps - imaging referral, specialist consultation, and monitoring strategies to track liver recovery. Results in about 10 days.",
        "condition-name": "Alcoholic Liver Disease Screening",
        "condition-overview": "<p>Alcoholic liver disease progresses from fatty liver to alcoholic hepatitis to cirrhosis. About 1 in 3 heavy drinkers develop some form of liver disease. Blood biomarkers - especially GGT, AST/ALT ratio, and bilirubin - detect damage during the reversible stages, before symptoms like jaundice, ascites, or liver failure appear.</p>",
        "why-test": "<p>Liver damage from alcohol is silent for years. By the time you feel symptoms, significant damage has often occurred. GGT rises early and is highly sensitive to alcohol. The AST/ALT ratio distinguishes alcohol-related damage from other causes. Testing gives you honest data so you can make informed decisions about your health.</p>",
        "what-is-included": "<p>Your panel includes GGT, AST, ALT, ALP, bilirubin (direct and total), albumin, total protein, complete metabolic panel, CBC with differential, lipid panel, and CRP - 100+ biomarkers total.</p>",
        "next-steps": "<p>If liver enzymes are elevated, our care team explains the severity honestly and recommends next steps - hepatology referral, imaging, and a monitoring plan. For those reducing alcohol intake, serial testing tracks liver recovery over time.</p>",
        "meta-title": "Alcoholic Liver Disease Blood Test | GGT, AST/ALT | Superpower",
        "meta-description": "Test for alcohol-related liver damage - GGT, AST, ALT, bilirubin. Catch damage before symptoms appear. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Alcoholic Liver Disease Blood Test | GGT, AST/ALT | Superpower",
        "og-description": "How much is alcohol affecting your liver? GGT + liver enzymes + 100+ biomarkers. ~10 day results.",
    },
    "cholestasis-biomarker-test": {
        "name": "Cholestasis Biomarker Test",
        "hero-headline": "Itching, Dark Urine, Pale Stools? Your Bile Flow May Be Blocked.",
        "hero-subheadline": "<p>Cholestasis occurs when bile flow from the liver is obstructed. ALP, GGT, and bilirubin levels rise before imaging catches structural problems. Blood biomarkers are often the first clue that something is wrong with bile drainage. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Bile Flow Biomarkers",
        "primary-keyword": "cholestasis blood test",
        "secondary-keywords": "cholestasis biomarkers, ALP bilirubin test, bile flow blood test, cholestatic liver disease test",
        "symptom-headline": "Signs that may indicate bile flow obstruction",
        "symptom-1": "Intense itching - especially palms and soles - with no rash",
        "symptom-2": "Dark urine that looks like tea or cola",
        "symptom-3": "Pale or clay-colored stools",
        "symptom-4": "Yellowing of skin or the whites of your eyes",
        "symptom-5": "Upper right abdominal discomfort after fatty meals",
        "symptom-cta": "Check if bile flow biomarkers are elevated ->",
        "stat-1-number": "ALP + GGT",
        "stat-1-text": "together are the most reliable blood markers for bile flow obstruction - elevated levels warrant imaging and specialist referral",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Unbearable itching for months - dermatologist had no answers. Superpower found my ALP was 340 (normal under 120), GGT was 210, and direct bilirubin was elevated. Ultrasound found a bile duct obstruction. One blood test explained months of mystery symptoms.</p>",
        "featured-testimonial-name": "Linda K.",
        "featured-testimonial-result": "Bile duct obstruction identified after months of unexplained itching",
        "membership-subheadline": "Screen bile flow and liver function markers",
        "membership-benefit-1": "ALP, GGT, and bilirubin tested annually",
        "membership-benefit-2": "100+ biomarkers including liver and metabolic",
        "membership-benefit-3": "AI flags cholestatic patterns early",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests ALP, GGT, bilirubin (direct and total), AST, ALT, albumin, total protein, complete metabolic panel, and CBC - biomarkers that screen for cholestasis - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Cholestasis causes a specific biomarker pattern: ALP and GGT rise together while AST and ALT may remain normal or only mildly elevated. Direct bilirubin becomes the dominant fraction. Recognizing this pattern distinguishes bile flow problems from other liver conditions and guides the right imaging workup.",
        "how-it-works-3-subheading": "Cholestasis has many causes - gallstones, tumors, primary biliary cholangitis, medication reactions, and pregnancy-related changes. Blood biomarkers identify the cholestatic pattern. Imaging and specialist evaluation then determine the specific cause.",
        "how-it-works-4-subheading": "Our clinical team explains the cholestatic biomarker pattern and recommends next steps - typically hepatology referral and imaging (ultrasound or MRCP) to identify the source of obstruction. Results in about 10 days.",
        "condition-name": "Cholestasis Biomarker Screening",
        "condition-overview": "<p>Cholestasis is impaired bile flow from the liver to the intestine. It can result from obstruction (gallstones, tumors), liver disease (primary biliary cholangitis), medications, or pregnancy. Blood biomarkers - ALP, GGT, and direct bilirubin - rise in a characteristic pattern that signals bile flow problems and guides further evaluation.</p>",
        "why-test": "<p>Cholestasis often presents with vague symptoms like itching or fatigue that get attributed to other conditions. Elevated ALP and GGT with raised direct bilirubin form a specific pattern that points directly to bile flow obstruction. Blood biomarkers are the standard first step - results determine whether imaging and specialist referral are needed.</p>",
        "what-is-included": "<p>Your panel includes ALP, GGT, bilirubin (direct and total), AST, ALT, albumin, total protein, complete metabolic panel, CBC with differential, and CRP - 100+ biomarkers total.</p>",
        "next-steps": "<p>If a cholestatic biomarker pattern is identified, our care team recommends hepatology or gastroenterology referral for imaging (ultrasound, MRCP) and definitive diagnosis. Early identification prevents complications like infection and progressive liver damage.</p>",
        "meta-title": "Cholestasis Blood Test | ALP, GGT, Bilirubin | Superpower",
        "meta-description": "Screen for cholestasis - ALP, GGT, bilirubin in one blood draw. Detect bile flow obstruction early. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Cholestasis Blood Test | ALP, GGT, Bilirubin | Superpower",
        "og-description": "Itching with no rash? ALP, GGT, and bilirubin screen for bile flow problems. 100+ biomarkers. ~10 day results.",
    },
    "cfs-me-biomarker-test": {
        "name": "CFS/ME Biomarker Test",
        "hero-headline": "There's No Blood Test for CFS. But There Are Blood Tests for Everything It Mimics.",
        "hero-subheadline": "<p>Chronic fatigue syndrome has no definitive biomarker - but thyroid disease, iron deficiency, B12 deficiency, cortisol dysfunction, and autoimmune conditions cause identical symptoms and ARE detectable on blood work. Ruling them out is the most important step in a CFS/ME diagnosis. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Rule Out Treatable Causes of Fatigue",
        "primary-keyword": "chronic fatigue syndrome blood test",
        "secondary-keywords": "CFS blood test, ME/CFS biomarkers, chronic fatigue test, myalgic encephalomyelitis test",
        "symptom-headline": "When fatigue becomes something more",
        "symptom-1": "Exhaustion that lasts months and sleep doesn't fix",
        "symptom-2": "Exercise makes you worse for days - not better",
        "symptom-3": "Brain fog so bad you can't concentrate or find words",
        "symptom-4": "Unrefreshing sleep no matter how many hours you get",
        "symptom-5": "Muscle and joint pain with no clear cause",
        "symptom-cta": "Find out if something treatable is causing your fatigue ->",
        "stat-1-number": "836K-2.5M",
        "stat-1-text": "Americans have ME/CFS - but up to 90% are undiagnosed, and many have treatable conditions causing or worsening their symptoms",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Told I had CFS for 4 years. Superpower found my ferritin was 8 (functionally deficient), TSH was 4.9 (borderline), and vitamin D was 14. Three treatable problems hiding behind a CFS label. Iron infusion and thyroid medication gave me 60% of my energy back. Still managing CFS but now without three other conditions making it worse.</p>",
        "featured-testimonial-name": "Karen W.",
        "featured-testimonial-result": "3 treatable conditions found underneath CFS diagnosis",
        "membership-subheadline": "Rule out treatable causes and track fatigue markers",
        "membership-benefit-1": "Thyroid, iron, B12, and cortisol tested annually",
        "membership-benefit-2": "100+ biomarkers including ANA and inflammation",
        "membership-benefit-3": "AI identifies treatable fatigue patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests complete thyroid panel, ferritin, iron, B12, folate, vitamin D, cortisol, ANA, CRP, CBC with differential, fasting glucose, and metabolic panel - every treatable cause of chronic fatigue - plus 90+ other biomarkers. $199/year.",
        "how-it-works-2-subheading": "Honest truth: there is no definitive blood test for CFS/ME. But thyroid disease, iron deficiency, B12 deficiency, vitamin D deficiency, cortisol dysfunction, autoimmune conditions, and diabetes all cause fatigue symptoms identical to CFS - and every one of them is treatable. Ruling them out is clinically essential.",
        "how-it-works-3-subheading": "Many people diagnosed with CFS/ME actually have one or more treatable conditions contributing to their fatigue. Even those with confirmed CFS/ME often have coexisting deficiencies that make symptoms worse. Comprehensive blood work identifies what can be fixed - even if the underlying CFS/ME remains.",
        "how-it-works-4-subheading": "Our clinical team reviews your full biomarker panel and identifies any treatable conditions. They recommend targeted interventions for each finding and support your broader CFS/ME management with data. Results in about 10 days.",
        "condition-name": "CFS/ME Biomarker Screening",
        "condition-overview": "<p>Chronic fatigue syndrome (CFS), also called myalgic encephalomyelitis (ME), causes debilitating fatigue, post-exertional malaise, unrefreshing sleep, and cognitive dysfunction. There is no definitive blood biomarker for CFS/ME. However, comprehensive blood testing is critical because thyroid disease, iron deficiency, B12 deficiency, autoimmune conditions, and cortisol dysfunction cause identical symptoms and are treatable.</p>",
        "why-test": "<p>CFS/ME is a diagnosis of exclusion - treatable conditions must be ruled out first. Many patients carry a CFS label while harboring undiagnosed thyroid disease, severe iron deficiency, or autoimmune conditions. Even with confirmed CFS/ME, identifying and treating coexisting deficiencies meaningfully improves quality of life.</p>",
        "what-is-included": "<p>Your panel includes complete thyroid panel with antibodies, ferritin, iron, TIBC, vitamin B12, folate, vitamin D, cortisol, DHEA, ANA, CRP, CBC with differential, fasting glucose, insulin, and metabolic panel - 100+ biomarkers total.</p>",
        "next-steps": "<p>If treatable conditions are identified, our care team recommends targeted treatment - iron supplementation, thyroid medication, B12 therapy, or specialist referral. For confirmed CFS/ME, annual monitoring ensures no new treatable conditions develop alongside the condition.</p>",
        "meta-title": "CFS/ME Blood Test | Rule Out Treatable Causes | Superpower",
        "meta-description": "Chronic fatigue blood test - thyroid, iron, B12, cortisol, ANA. Rule out treatable causes of CFS/ME. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "CFS/ME Blood Test | Rule Out Treatable Causes | Superpower",
        "og-description": "No blood test for CFS - but there are tests for everything it mimics. 100+ biomarkers. ~10 day results.",
    },
    "hyperprolactinemia-biomarker-test": {
        "name": "Hyperprolactinemia Biomarker Test",
        "hero-headline": "Missed Periods, Low Libido, Milky Discharge? Check Your Prolactin.",
        "hero-subheadline": "<p>Elevated prolactin causes menstrual irregularities, infertility, low sex drive, and even unexpected breast discharge. A simple blood test measures your prolactin level and thyroid function - because hypothyroidism is a common hidden cause. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Prolactin Level",
        "primary-keyword": "prolactin blood test",
        "secondary-keywords": "hyperprolactinemia test, high prolactin test, prolactin level blood test, prolactin hormone test",
        "symptom-headline": "Signs your prolactin may be elevated",
        "symptom-1": "Irregular or absent menstrual periods",
        "symptom-2": "Difficulty getting pregnant despite trying",
        "symptom-3": "Decreased sex drive in men or women",
        "symptom-4": "Milky breast discharge when not pregnant or nursing",
        "symptom-5": "Headaches or vision changes (can indicate pituitary adenoma)",
        "symptom-cta": "Check your prolactin level now ->",
        "stat-1-number": "10%",
        "stat-1-text": "of infertility cases involve elevated prolactin - it's easily treatable once identified but rarely tested in routine blood work",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Periods stopped and sex drive vanished. Doctor said stress. Superpower found my prolactin was 68 ng/mL (normal under 25) and TSH was 6.2. Hypothyroidism was driving the high prolactin. Thyroid medication brought both back to normal. Periods returned in 2 months.</p>",
        "featured-testimonial-name": "Jessica R.",
        "featured-testimonial-result": "High prolactin caused by undiagnosed hypothyroidism - both resolved",
        "membership-subheadline": "Monitor prolactin and related hormones",
        "membership-benefit-1": "Prolactin plus thyroid panel tested annually",
        "membership-benefit-2": "100+ biomarkers including reproductive hormones",
        "membership-benefit-3": "AI connects prolactin to thyroid and hormones",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests prolactin, complete thyroid panel (TSH, Free T4, Free T3, antibodies), FSH, LH, estradiol, testosterone, and cortisol - the biomarkers connected to hyperprolactinemia - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Elevated prolactin suppresses GnRH, which lowers FSH and LH, which stops ovulation and reduces testosterone. That one hormone disrupts the entire reproductive axis. Testing the full hormonal cascade reveals how much prolactin is affecting your fertility, libido, and menstrual cycles.",
        "how-it-works-3-subheading": "Hypothyroidism is one of the most common - and most treatable - causes of elevated prolactin. Medications like antipsychotics, antidepressants, and PPIs also raise prolactin. Our panel identifies thyroid dysfunction and your care team reviews medication interactions.",
        "how-it-works-4-subheading": "If prolactin is elevated, our clinical team recommends endocrinology referral. Very high levels may warrant pituitary MRI to rule out prolactinoma. Most cases are highly treatable with medication. Results in about 10 days.",
        "condition-name": "Hyperprolactinemia Screening",
        "condition-overview": "<p>Hyperprolactinemia is elevated prolactin hormone, affecting about 0.4% of the general population but up to 10% of people with infertility. It causes menstrual irregularities, infertility, low libido, galactorrhea, and bone loss. Common causes include pituitary adenomas, hypothyroidism, and medications. It's highly treatable once diagnosed.</p>",
        "why-test": "<p>Prolactin is not included in routine blood work, so hyperprolactinemia is frequently missed. Symptoms like irregular periods and low libido are often attributed to stress or aging. A single blood test identifies elevated prolactin - and testing alongside thyroid markers reveals whether hypothyroidism is the hidden cause.</p>",
        "what-is-included": "<p>Your panel includes prolactin, complete thyroid panel with antibodies, FSH, LH, estradiol, testosterone, DHEA, cortisol, CBC, metabolic panel, and vitamin D - 100+ biomarkers total.</p>",
        "next-steps": "<p>If prolactin is elevated, our care team recommends endocrinology referral. If hypothyroidism is the cause, thyroid treatment often normalizes prolactin without additional medication. For pituitary causes, MRI and dopamine agonist therapy are typically recommended.</p>",
        "meta-title": "Prolactin Blood Test | Hyperprolactinemia | Superpower",
        "meta-description": "Test prolactin levels - missed periods, low libido, infertility. Plus thyroid and 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Prolactin Blood Test | Hyperprolactinemia | Superpower",
        "og-description": "Missed periods or low libido? Prolactin + thyroid + 100+ biomarkers. ~10 day results.",
    },
    "female-infertility-biomarker-test": {
        "name": "Female Infertility Biomarker Test",
        "hero-headline": "Fertility Is Complex. Blood Biomarkers Are the Essential First Step.",
        "hero-subheadline": "<p>FSH, LH, estradiol, thyroid, insulin, and prolactin reveal whether hormonal imbalances are affecting your ability to conceive. Blood biomarkers can't tell the whole story - but they identify the most common and treatable hormonal causes of female infertility. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Fertility Biomarkers",
        "primary-keyword": "female infertility blood test",
        "secondary-keywords": "fertility blood test women, FSH fertility test, hormone test for fertility, fertility biomarkers",
        "symptom-headline": "When fertility blood work should be a priority",
        "symptom-1": "Trying to conceive for 6+ months without success",
        "symptom-2": "Irregular or absent menstrual cycles",
        "symptom-3": "History of PCOS, endometriosis, or thyroid disease",
        "symptom-4": "Over 35 and wanting to understand your fertility window",
        "symptom-5": "Previous miscarriage and wanting answers about hormonal causes",
        "symptom-cta": "Get your fertility biomarkers tested ->",
        "stat-1-number": "1 in 5",
        "stat-1-text": "women of reproductive age have difficulty getting pregnant - hormonal blood biomarkers identify treatable causes in up to 40% of cases",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>18 months trying to conceive. OB said keep trying. Superpower found my TSH was 5.1 (too high for conception), insulin was 18 (insulin resistant), and prolactin was mildly elevated. Three treatable hormonal issues. Six months of treatment later - pregnant naturally.</p>",
        "featured-testimonial-name": "Rachel N.",
        "featured-testimonial-result": "3 hormonal issues found - conceived naturally after treatment",
        "membership-subheadline": "Comprehensive fertility hormone monitoring",
        "membership-benefit-1": "FSH, LH, estradiol, and thyroid tested annually",
        "membership-benefit-2": "100+ biomarkers including insulin and prolactin",
        "membership-benefit-3": "AI identifies hormonal fertility patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests FSH, LH, estradiol, progesterone, prolactin, complete thyroid panel with antibodies, fasting insulin, testosterone, DHEA, vitamin D, and ferritin - the hormonal biomarkers that impact female fertility - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Fertility depends on a precisely coordinated hormonal cascade. FSH and LH drive ovulation. Thyroid dysfunction disrupts the cycle and increases miscarriage risk. Insulin resistance (PCOS) impairs ovulation. Elevated prolactin suppresses the entire reproductive axis. Blood biomarkers identify which hormonal link is broken.",
        "how-it-works-3-subheading": "Honest context: blood biomarkers assess the hormonal side of fertility. Structural factors (tubal patency, uterine anatomy) and ovarian reserve (AMH, antral follicle count) require specialist testing. But hormonal causes are the most common and most treatable - and blood work is the right place to start.",
        "how-it-works-4-subheading": "Our clinical team explains your fertility biomarkers and recommends next steps - thyroid optimization, insulin management, prolactin treatment, or reproductive endocrinology referral for comprehensive evaluation. Results in about 10 days.",
        "condition-name": "Female Infertility Biomarker Screening",
        "condition-overview": "<p>Female infertility affects about 1 in 5 women of reproductive age. Hormonal causes - thyroid dysfunction, PCOS (insulin resistance), elevated prolactin, and FSH/LH imbalances - account for a significant portion of cases and are identifiable through blood biomarkers. Fertility is complex and multifactorial, but hormonal blood testing is the essential first diagnostic step.</p>",
        "why-test": "<p>Hormonal blood biomarkers identify the most common treatable causes of female infertility. Subclinical hypothyroidism alone affects fertility and increases miscarriage risk. Insulin resistance impairs ovulation. Elevated prolactin suppresses the reproductive axis. Testing these before expensive fertility treatments ensures treatable causes aren't missed.</p>",
        "what-is-included": "<p>Your panel includes FSH, LH, estradiol, progesterone, prolactin, complete thyroid panel with antibodies, fasting insulin, fasting glucose, testosterone, DHEA, vitamin D, ferritin, and CRP - 100+ biomarkers total. Note: AMH (ovarian reserve) requires specialist ordering.</p>",
        "next-steps": "<p>If hormonal imbalances are identified, our care team recommends targeted treatment - thyroid optimization, insulin sensitization, prolactin management - and refers to reproductive endocrinology when comprehensive fertility evaluation is warranted.</p>",
        "meta-title": "Female Infertility Blood Test | Fertility Hormones | Superpower",
        "meta-description": "Fertility blood test - FSH, LH, estradiol, thyroid, insulin, prolactin. Identify hormonal causes of infertility. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Female Infertility Blood Test | Fertility Hormones | Superpower",
        "og-description": "Trying to conceive? Test FSH, thyroid, insulin + 100+ biomarkers. ~10 day results.",
    },
    "male-infertility-biomarker-test": {
        "name": "Male Infertility Biomarker Test",
        "hero-headline": "Male Factor Is Half of All Infertility Cases. Blood Tests Are the First Step.",
        "hero-subheadline": "<p>Testosterone, FSH, LH, prolactin, and thyroid biomarkers reveal hormonal causes of male infertility. Blood work assesses the hormonal side - but be aware that semen analysis is also needed for a complete picture. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Reproductive Hormones",
        "primary-keyword": "male infertility blood test",
        "secondary-keywords": "male fertility blood test, testosterone fertility test, FSH LH male fertility, male hormone fertility panel",
        "symptom-headline": "Signs that warrant male fertility blood work",
        "symptom-1": "Partner has been unable to conceive after 6+ months",
        "symptom-2": "Low sex drive or erectile difficulties",
        "symptom-3": "Decreased energy, muscle loss, or weight gain",
        "symptom-4": "History of testicular injury, varicocele, or undescended testes",
        "symptom-5": "Previous testosterone result that was low or borderline",
        "symptom-cta": "Get your male fertility biomarkers tested ->",
        "stat-1-number": "50%",
        "stat-1-text": "of infertility cases have a male factor - yet men are often tested last, delaying diagnosis and treatment by months or years",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Wife and I tried for 2 years. All her tests were normal. Finally got my hormones tested - FSH was 18 mIU/mL (elevated), testosterone was 240, and prolactin was high at 32. The elevated FSH pointed to a testicular problem. Urologist confirmed varicocele. Surgery and hormone optimization - now expecting our first.</p>",
        "featured-testimonial-name": "Brian S.",
        "featured-testimonial-result": "Varicocele and hormonal issues found after 2 years of unexplained infertility",
        "membership-subheadline": "Assess and monitor male reproductive hormones",
        "membership-benefit-1": "Testosterone, FSH, LH, and prolactin annually",
        "membership-benefit-2": "100+ biomarkers including thyroid and metabolic",
        "membership-benefit-3": "AI flags hormonal fertility red flags",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests total testosterone, free testosterone, FSH, LH, prolactin, estradiol, SHBG, complete thyroid panel, cortisol, and DHEA - the male reproductive hormone panel - plus 90+ other biomarkers. $199/year.",
        "how-it-works-2-subheading": "FSH is the key fertility biomarker in men - elevated FSH indicates the testes aren't producing sperm adequately. Low testosterone with low LH suggests pituitary dysfunction. Elevated prolactin suppresses the entire reproductive axis. Blood biomarkers identify which hormonal mechanism is impaired.",
        "how-it-works-3-subheading": "Important context: blood tests assess hormonal causes of male infertility. Semen analysis - which measures sperm count, motility, and morphology - is also essential for a complete fertility evaluation. Our care team can advise on getting both types of testing done.",
        "how-it-works-4-subheading": "Our clinical team explains your reproductive hormone results and recommends next steps - semen analysis if not done, urology referral for elevated FSH, or endocrinology referral for hormonal treatment. Results in about 10 days.",
        "condition-name": "Male Infertility Biomarker Screening",
        "condition-overview": "<p>Male factor contributes to approximately 50% of all infertility cases. Hormonal causes - low testosterone, elevated FSH, high prolactin, thyroid dysfunction - are identifiable through blood biomarkers. However, male fertility evaluation also requires semen analysis to assess sperm production directly. Blood biomarkers identify the hormonal picture; semen analysis completes it.</p>",
        "why-test": "<p>Men are often tested last in fertility workups, wasting months or years. Blood biomarkers quickly reveal hormonal causes of male infertility - low testosterone, elevated FSH (indicating testicular dysfunction), high prolactin, and thyroid problems. These are treatable once identified. Blood work is the essential first step alongside semen analysis.</p>",
        "what-is-included": "<p>Your panel includes total testosterone, free testosterone, FSH, LH, prolactin, estradiol, SHBG, DHEA, complete thyroid panel, cortisol, fasting insulin, CBC, and metabolic panel - 100+ biomarkers total. Note: semen analysis is a separate test that we recommend discussing with your doctor.</p>",
        "next-steps": "<p>If hormonal abnormalities are found, our care team recommends urology or reproductive endocrinology referral. They advise on semen analysis coordination and lifestyle modifications that improve both hormone levels and sperm parameters.</p>",
        "meta-title": "Male Infertility Blood Test | Testosterone, FSH | Superpower",
        "meta-description": "Male fertility blood test - testosterone, FSH, LH, prolactin, thyroid. Male factor is 50% of infertility. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Male Infertility Blood Test | Testosterone, FSH | Superpower",
        "og-description": "Male factor is half of all infertility. Test testosterone, FSH, LH + 100+ biomarkers. ~10 day results.",
    },
    "pancreatitis-biomarker-test": {
        "name": "Pancreatitis Biomarker Test",
        "hero-headline": "Severe Abdominal Pain After Eating? Your Pancreas May Need Attention.",
        "hero-subheadline": "<p>Lipase and amylase - the definitive pancreatitis markers - may not be included in standard blood panels. But triglycerides, liver enzymes, calcium, and metabolic markers assess the risk factors and complications that drive pancreatic disease. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Assess Pancreatic Risk Factors",
        "primary-keyword": "pancreatitis blood test",
        "secondary-keywords": "pancreatitis biomarkers, pancreas blood test, pancreatic enzymes blood test, lipase amylase test",
        "symptom-headline": "Warning signs that point to the pancreas",
        "symptom-1": "Severe upper abdominal pain that radiates to the back",
        "symptom-2": "Pain that worsens after eating - especially fatty foods",
        "symptom-3": "Nausea, vomiting, and abdominal tenderness",
        "symptom-4": "History of gallstones or heavy alcohol use",
        "symptom-5": "Very high triglycerides on previous blood work",
        "symptom-cta": "Screen your pancreatic risk factors ->",
        "stat-1-number": "275K",
        "stat-1-text": "hospitalizations for pancreatitis each year in the US - gallstones and alcohol account for 80% of cases, and both have detectable blood biomarkers",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Had two episodes of severe upper abdominal pain. Superpower showed my triglycerides were 580 mg/dL (severely elevated), liver enzymes were high suggesting possible gallstone issues, and fasting glucose was 118. My pancreas was under assault from multiple directions. Treatment brought triglycerides to 160 and no more attacks.</p>",
        "featured-testimonial-name": "Tony M.",
        "featured-testimonial-result": "Triglycerides from 580 to 160 - pancreatitis episodes stopped",
        "membership-subheadline": "Monitor pancreatic risk factors and metabolic health",
        "membership-benefit-1": "Triglycerides, liver enzymes, and glucose annually",
        "membership-benefit-2": "100+ biomarkers including calcium and metabolic",
        "membership-benefit-3": "AI flags pancreatitis risk factor patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests triglycerides, complete lipid panel, liver enzymes (ALT, AST, ALP, GGT, bilirubin), calcium, fasting glucose, HbA1c, and CRP - the metabolic biomarkers connected to pancreatitis risk - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Honest context: lipase and amylase are the definitive pancreatitis diagnostic markers, but they are typically ordered in acute settings and may not be part of the standard panel. Our test focuses on the risk factors and metabolic complications - very high triglycerides (above 500 mg/dL), liver abnormalities suggesting gallstones, and glucose dysregulation indicating pancreatic damage.",
        "how-it-works-3-subheading": "Pancreatitis damages the insulin-producing cells of the pancreas. We test fasting glucose and HbA1c to assess whether pancreatic function is already affecting blood sugar regulation. Elevated liver enzymes may indicate gallstone-related obstruction - the most common cause of acute pancreatitis.",
        "how-it-works-4-subheading": "Our clinical team explains your pancreatic risk biomarkers and recommends next steps - triglyceride management, gastroenterology referral for gallstone evaluation, or urgent care if acute symptoms are present. Results in about 10 days.",
        "condition-name": "Pancreatitis Risk Biomarker Screening",
        "condition-overview": "<p>Pancreatitis is inflammation of the pancreas, causing about 275,000 hospitalizations annually in the US. Gallstones and alcohol account for 80% of cases. Blood biomarkers assess the major risk factors - very high triglycerides, liver enzyme patterns suggesting gallstones, and metabolic markers showing pancreatic damage. Note: definitive diagnosis of acute pancreatitis requires lipase/amylase testing, which is typically ordered in acute care settings.</p>",
        "why-test": "<p>Pancreatitis risk factors are detectable on blood work before an attack occurs. Triglycerides above 500 mg/dL significantly increase pancreatitis risk. Liver enzyme patterns suggest gallstone-related obstruction. Glucose dysregulation indicates pancreatic damage already affecting insulin production. Identifying and treating these risk factors can prevent pancreatitis episodes.</p>",
        "what-is-included": "<p>Your panel includes triglycerides, complete lipid panel, ALT, AST, ALP, GGT, bilirubin, calcium, fasting glucose, HbA1c, fasting insulin, CRP, and CBC - 100+ biomarkers total. Note: lipase and amylase are acute diagnostic markers typically ordered separately in clinical settings.</p>",
        "next-steps": "<p>If pancreatitis risk factors are elevated, our care team recommends triglyceride reduction strategies, gastroenterology referral for gallstone evaluation if liver enzymes suggest obstruction, and glucose monitoring if pancreatic function may be compromised.</p>",
        "meta-title": "Pancreatitis Risk Blood Test | Triglycerides + Liver | Superpower",
        "meta-description": "Screen pancreatitis risk factors - triglycerides, liver enzymes, glucose, calcium. 275K hospitalizations/year. 100+ biomarkers. ~10 days. $199/year.",
        "og-title": "Pancreatitis Risk Blood Test | Triglycerides + Liver | Superpower",
        "og-description": "Assess your pancreatitis risk - triglycerides, liver enzymes + 100+ biomarkers. ~10 day results.",
    },
    "bph-biomarker-test": {
        "name": "BPH (Enlarged Prostate) Biomarker Test",
        "hero-headline": "Getting Up 3 Times a Night to Urinate? Your PSA Has Answers.",
        "hero-subheadline": "<p>Benign prostatic hyperplasia (BPH) affects most men over 50. PSA testing screens for prostate enlargement and helps distinguish BPH from prostate cancer. One blood draw gives you PSA alongside kidney function, hormones, and metabolic markers. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Check Your PSA Level",
        "primary-keyword": "BPH blood test",
        "secondary-keywords": "PSA test BPH, enlarged prostate blood test, prostate biomarkers, benign prostatic hyperplasia test",
        "symptom-headline": "Signs your prostate may be enlarged",
        "symptom-1": "Waking up multiple times at night to urinate",
        "symptom-2": "Weak urine stream or difficulty starting urination",
        "symptom-3": "Feeling like your bladder isn't fully empty",
        "symptom-4": "Urgency - suddenly needing to urinate right now",
        "symptom-5": "Over 50 and never had a PSA test",
        "symptom-cta": "Get your PSA and prostate health biomarkers ->",
        "stat-1-number": "50%",
        "stat-1-text": "of men over 50 develop BPH - PSA testing screens for enlargement and helps rule out prostate cancer at the same time",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Up 4 times a night, weak stream, always feeling the urge. PSA was 5.8 ng/mL. Urologist confirmed BPH with no cancer on biopsy. Started medication and within 6 weeks I was sleeping through the night. Should have tested years ago instead of suffering in silence.</p>",
        "featured-testimonial-name": "Robert J.",
        "featured-testimonial-result": "BPH confirmed and treated - sleeping through the night again",
        "membership-subheadline": "Monitor PSA and prostate health annually",
        "membership-benefit-1": "PSA plus testosterone tested every year",
        "membership-benefit-2": "100+ biomarkers including kidney function",
        "membership-benefit-3": "AI tracks PSA trends and velocity",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests PSA, total testosterone, free testosterone, SHBG, eGFR, creatinine, BUN, complete metabolic panel, and CBC - the prostate health biomarker panel - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "PSA is produced by the prostate gland and rises with enlargement, infection, or cancer. A mildly elevated PSA (4-10 ng/mL) is common in BPH. PSA velocity (how fast it rises over time) is often more informative than a single value. Annual monitoring builds the trend data that urologists need.",
        "how-it-works-3-subheading": "Testosterone and DHT drive prostate growth. We test testosterone, free testosterone, and SHBG because hormonal status affects BPH progression and treatment choices. Kidney function markers (eGFR, creatinine) assess whether urinary obstruction from BPH is affecting the kidneys.",
        "how-it-works-4-subheading": "Our clinical team explains your PSA level in context - not just whether it's elevated, but what the level suggests. They recommend urology referral when appropriate and help you understand the difference between BPH and cancer risk. Results in about 10 days.",
        "condition-name": "BPH Prostate Biomarker Screening",
        "condition-overview": "<p>Benign prostatic hyperplasia (BPH) is non-cancerous enlargement of the prostate that affects about 50% of men over 50 and 90% of men over 80. It causes urinary frequency, weak stream, nocturia, and incomplete emptying. PSA blood testing screens for prostate enlargement and helps differentiate BPH from prostate cancer. Annual PSA monitoring tracks progression.</p>",
        "why-test": "<p>PSA testing serves dual purposes for BPH - it monitors prostate enlargement severity and screens for prostate cancer. Many men suffer with urinary symptoms for years without getting tested. A single blood draw provides PSA, kidney function (to check for obstruction damage), and hormonal markers that guide treatment decisions.</p>",
        "what-is-included": "<p>Your panel includes PSA, total testosterone, free testosterone, SHBG, eGFR, creatinine, BUN, complete metabolic panel, CBC with differential, lipid panel, and CRP - 100+ biomarkers total.</p>",
        "next-steps": "<p>If PSA is elevated or urinary symptoms suggest BPH, our care team recommends urology referral for digital rectal exam, possible imaging, and treatment discussion. For confirmed BPH, annual PSA monitoring tracks progression and medication effectiveness.</p>",
        "meta-title": "BPH Blood Test | PSA + Prostate Biomarkers | Superpower",
        "meta-description": "PSA test for BPH and prostate health. 50% of men over 50 are affected. PSA + hormones + kidney + 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "BPH Blood Test | PSA + Prostate Biomarkers | Superpower",
        "og-description": "Frequent urination? Check your PSA and prostate biomarkers. 100+ biomarkers in one draw. ~10 day results.",
    },
    "cushings-syndrome-biomarker-test": {
        "name": "Cushing's Syndrome Biomarker Test",
        "hero-headline": "Unexplained Weight Gain, Moon Face, and Bruising? Cortisol May Be the Cause.",
        "hero-subheadline": "<p>Cushing's syndrome is caused by prolonged cortisol excess. A single random cortisol blood test is not diagnostic - but a clearly elevated cortisol alongside DHEA, glucose, and metabolic markers provides strong evidence that warrants definitive testing. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen Your Cortisol Level",
        "primary-keyword": "Cushing's syndrome blood test",
        "secondary-keywords": "cortisol blood test Cushings, Cushing syndrome biomarkers, high cortisol test, cortisol excess test",
        "symptom-headline": "Signs that may point to cortisol excess",
        "symptom-1": "Rapid weight gain - especially face, neck, and abdomen",
        "symptom-2": "Round 'moon face' and fat pad on upper back",
        "symptom-3": "Easy bruising and thin skin that tears easily",
        "symptom-4": "Purple stretch marks on abdomen, thighs, or arms",
        "symptom-5": "High blood sugar, high blood pressure, and muscle weakness together",
        "symptom-cta": "Check if cortisol excess is behind your symptoms ->",
        "stat-1-number": "10-15",
        "stat-1-text": "per million people per year are diagnosed with Cushing's - but subclinical cases are far more common and often missed for years",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Gained 40 pounds in 6 months - all in my face and trunk. Doctor said diet and exercise. Superpower showed cortisol was 28 mcg/dL (upper limit is 20), DHEA was suppressed, glucose was 142, and potassium was low. Endocrinologist confirmed Cushing's with 24-hour urine test. Finally had an answer for the weight that nothing could fix.</p>",
        "featured-testimonial-name": "Christine M.",
        "featured-testimonial-result": "Cushing's syndrome confirmed after months of unexplained weight gain",
        "membership-subheadline": "Screen cortisol and metabolic markers annually",
        "membership-benefit-1": "Cortisol, DHEA, and glucose tested annually",
        "membership-benefit-2": "100+ biomarkers including electrolytes",
        "membership-benefit-3": "AI flags cortisol-metabolic patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests cortisol, DHEA, fasting glucose, HbA1c, fasting insulin, electrolytes (sodium, potassium), CBC with differential, complete metabolic panel, and lipid panel - biomarkers connected to cortisol excess - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Honest context: a single random morning cortisol is not sufficient to diagnose Cushing's syndrome. Definitive diagnosis requires 24-hour urinary free cortisol, late-night salivary cortisol, or dexamethasone suppression testing. However, a clearly elevated morning cortisol - especially with suppressed DHEA, high glucose, and low potassium - strongly suggests cortisol excess and warrants specialist referral.",
        "how-it-works-3-subheading": "Cortisol excess causes a recognizable metabolic pattern: hyperglycemia, hypokalemia, elevated white blood cells, and dyslipidemia. We test all of these alongside cortisol. If the pattern fits, it significantly strengthens the case for endocrinology evaluation.",
        "how-it-works-4-subheading": "Our clinical team evaluates your cortisol and metabolic markers together. If results suggest cortisol excess, they recommend endocrinology referral for definitive Cushing's testing (24-hour urine, salivary cortisol, or suppression test). Results in about 10 days.",
        "condition-name": "Cushing's Syndrome Biomarker Screening",
        "condition-overview": "<p>Cushing's syndrome results from prolonged exposure to excess cortisol - either from endogenous overproduction (pituitary or adrenal tumors) or exogenous corticosteroid medications. It causes central obesity, moon face, easy bruising, hyperglycemia, hypertension, and muscle wasting. While rare in its classic form, subclinical cortisol excess is more common and often missed.</p>",
        "why-test": "<p>A random morning cortisol blood test alone cannot confirm Cushing's syndrome - but it can raise the red flag. When elevated cortisol appears alongside suppressed DHEA, high glucose, low potassium, and elevated white blood cells, the pattern strongly suggests cortisol excess. This screening data gives your endocrinologist the rationale to order definitive testing.</p>",
        "what-is-included": "<p>Your panel includes cortisol, DHEA, fasting glucose, HbA1c, fasting insulin, sodium, potassium, CBC with differential, complete metabolic panel, lipid panel, and CRP - 100+ biomarkers total. Note: definitive Cushing's diagnosis requires 24-hour urine cortisol, late-night salivary cortisol, or dexamethasone suppression test ordered by an endocrinologist.</p>",
        "next-steps": "<p>If cortisol and metabolic biomarkers suggest excess cortisol, our care team recommends endocrinology referral for definitive Cushing's testing. Early diagnosis prevents complications including osteoporosis, diabetes, and cardiovascular disease.</p>",
        "meta-title": "Cushing's Syndrome Blood Test | Cortisol Screening | Superpower",
        "meta-description": "Screen for Cushing's syndrome - cortisol, DHEA, glucose, electrolytes. Unexplained weight gain? 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Cushing's Syndrome Blood Test | Cortisol Screening | Superpower",
        "og-description": "Moon face, weight gain, bruising? Screen cortisol + 100+ biomarkers. ~10 day results.",
    },
    "addisons-disease-biomarker-test": {
        "name": "Addison's Disease Biomarker Test",
        "hero-headline": "Fatigue, Salt Cravings, and Darkening Skin? Your Cortisol May Be Too Low.",
        "hero-subheadline": "<p>Addison's disease occurs when the adrenal glands don't produce enough cortisol. A low morning cortisol with abnormal sodium and potassium is suggestive - though not definitive. Blood biomarkers identify the pattern that warrants urgent specialist evaluation. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Screen Your Cortisol and Electrolytes",
        "primary-keyword": "Addison's disease blood test",
        "secondary-keywords": "adrenal insufficiency blood test, low cortisol test, Addison's biomarkers, cortisol deficiency test",
        "symptom-headline": "Signs that may indicate adrenal insufficiency",
        "symptom-1": "Profound fatigue that worsens over weeks and months",
        "symptom-2": "Intense salt cravings you can't explain",
        "symptom-3": "Darkening of skin - especially in creases, scars, and gums",
        "symptom-4": "Lightheadedness when standing up, low blood pressure",
        "symptom-5": "Unintentional weight loss with nausea and loss of appetite",
        "symptom-cta": "Check if low cortisol is behind your symptoms ->",
        "stat-1-number": "1 in 10K",
        "stat-1-text": "people have Addison's disease - but it's frequently missed because symptoms develop slowly and mimic burnout, depression, or eating disorders",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Lost 15 pounds without trying, craving salt constantly, skin getting darker. Thought I was depressed. Morning cortisol was 2.8 mcg/dL (critically low), sodium was 131 (low), potassium was 5.4 (high). Classic Addison's pattern. Endocrinologist confirmed with ACTH stimulation test. Hydrocortisone replacement literally saved my life.</p>",
        "featured-testimonial-name": "Amy L.",
        "featured-testimonial-result": "Addison's disease identified from classic biomarker pattern",
        "membership-subheadline": "Screen cortisol and electrolytes for adrenal health",
        "membership-benefit-1": "Cortisol, DHEA, and electrolytes annually",
        "membership-benefit-2": "100+ biomarkers including thyroid and glucose",
        "membership-benefit-3": "AI flags adrenal insufficiency patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests morning cortisol, DHEA, sodium, potassium, chloride, bicarbonate, glucose, CBC with differential, complete metabolic panel, thyroid panel, and ANA - biomarkers connected to adrenal insufficiency - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Honest context: a single morning cortisol blood test is suggestive but not definitive for Addison's disease. Definitive diagnosis requires an ACTH stimulation test performed by an endocrinologist. However, low morning cortisol (below 5 mcg/dL) combined with low sodium, high potassium, and low glucose creates a pattern that strongly warrants urgent specialist referral.",
        "how-it-works-3-subheading": "Addison's is autoimmune in 80% of cases and often coexists with other autoimmune conditions - thyroid disease, type 1 diabetes, and vitiligo. We test thyroid markers and ANA alongside cortisol to screen for these associated conditions. Eosinophilia on CBC can also be an early clue.",
        "how-it-works-4-subheading": "Our clinical team evaluates your cortisol and electrolytes together. If the pattern suggests adrenal insufficiency, they recommend urgent endocrinology referral for ACTH stimulation testing - this is a condition where timely diagnosis is critical. Results in about 10 days.",
        "condition-name": "Addison's Disease Biomarker Screening",
        "condition-overview": "<p>Addison's disease (primary adrenal insufficiency) occurs when the adrenal glands fail to produce adequate cortisol and aldosterone. It affects about 1 in 10,000 people and develops gradually - often misdiagnosed as depression, chronic fatigue, or eating disorders. Untreated, it can lead to life-threatening adrenal crisis. Blood biomarkers identify the suggestive pattern that prompts diagnosis.</p>",
        "why-test": "<p>Addison's disease is frequently missed because symptoms develop slowly and overlap with common conditions. A low morning cortisol with low sodium and high potassium is strongly suggestive. Blood biomarkers provide the screening data that triggers definitive ACTH stimulation testing. In a condition where delayed diagnosis can be fatal, early screening matters enormously.</p>",
        "what-is-included": "<p>Your panel includes morning cortisol, DHEA, sodium, potassium, chloride, bicarbonate, fasting glucose, CBC with differential (eosinophils), ANA, complete thyroid panel, and CRP - 100+ biomarkers total. Note: definitive Addison's diagnosis requires an ACTH stimulation test ordered by an endocrinologist.</p>",
        "next-steps": "<p>If cortisol is low with suggestive electrolyte changes, our care team recommends urgent endocrinology referral for ACTH stimulation testing. Once diagnosed, cortisol replacement therapy is lifelong but highly effective. Annual monitoring ensures adequate replacement.</p>",
        "meta-title": "Addison's Disease Blood Test | Cortisol Screening | Superpower",
        "meta-description": "Screen for Addison's disease - cortisol, sodium, potassium. Often missed for years. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Addison's Disease Blood Test | Cortisol Screening | Superpower",
        "og-description": "Fatigue, salt cravings, dark skin? Screen cortisol and electrolytes. 100+ biomarkers. ~10 day results.",
    },
    "subclinical-hyperthyroidism-biomarker-test": {
        "name": "Subclinical Hyperthyroidism Biomarker Test",
        "hero-headline": "Your TSH Is Low but Your Doctor Says You're Fine. You Might Not Be.",
        "hero-subheadline": "<p>Subclinical hyperthyroidism means your TSH is suppressed but Free T4 and Free T3 are still in range. Most doctors dismiss it. But it increases your risk of atrial fibrillation, osteoporosis, and anxiety. TSH and Free T4 together detect it precisely. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Get Your Complete Thyroid Panel",
        "primary-keyword": "subclinical hyperthyroidism blood test",
        "secondary-keywords": "low TSH test, subclinical hyperthyroid screening, TSH Free T4 test, thyroid overactive test",
        "symptom-headline": "Signs of subclinical hyperthyroidism most doctors overlook",
        "symptom-1": "Heart palpitations or racing heart - especially at rest",
        "symptom-2": "Anxiety or nervousness that feels physical, not mental",
        "symptom-3": "Unexplained weight loss or inability to gain weight",
        "symptom-4": "Tremor in hands, increased sweating, heat intolerance",
        "symptom-5": "Previous blood work showing TSH at the low end of 'normal'",
        "symptom-cta": "Find out if your thyroid is running too fast ->",
        "stat-1-number": "2%",
        "stat-1-text": "of the population has subclinical hyperthyroidism - most are undiagnosed because standard TSH-only testing doesn't trigger investigation",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Heart palpitations and anxiety for a year. Cardiologist said my heart was fine. Superpower found TSH was 0.15 (suppressed - normal is 0.4-4.0) with Free T4 at the high end of normal at 1.7. Subclinical hyperthyroidism - missed because my T4 wasn't technically flagged. Endocrinologist started monitoring and the palpitations finally had an explanation.</p>",
        "featured-testimonial-name": "Diane F.",
        "featured-testimonial-result": "Subclinical hyperthyroidism found after a year of unexplained palpitations",
        "membership-subheadline": "Monitor thyroid function with precision",
        "membership-benefit-1": "TSH, Free T4, and Free T3 tested annually",
        "membership-benefit-2": "100+ biomarkers including bone and heart markers",
        "membership-benefit-3": "AI catches subtle TSH suppression patterns",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests TSH, Free T4, Free T3, thyroid antibodies (TPO, thyroglobulin), calcium, ALP, complete metabolic panel, lipid panel, and CBC - the biomarkers needed to detect and assess subclinical hyperthyroidism - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Subclinical hyperthyroidism is defined by a suppressed TSH (below 0.4) with Free T4 and Free T3 still within normal range. It's called 'subclinical' but it's not without consequences - it increases atrial fibrillation risk 3-fold in older adults and accelerates bone loss. TSH alone detects it, but the full thyroid panel reveals severity.",
        "how-it-works-3-subheading": "Thyroid antibodies help determine the cause - Graves' disease (stimulating antibodies) vs toxic nodular goiter vs transient thyroiditis. Calcium and ALP assess bone impact. We test the complete picture because the cause determines whether treatment, monitoring, or watchful waiting is appropriate.",
        "how-it-works-4-subheading": "Our clinical team explains your TSH suppression in context - how low it is, whether antibodies suggest Graves' disease, and what your bone and cardiac risk looks like. They recommend endocrinology referral when treatment decisions are needed. Results in about 10 days.",
        "condition-name": "Subclinical Hyperthyroidism Screening",
        "condition-overview": "<p>Subclinical hyperthyroidism affects about 2% of the population. TSH is suppressed below normal while Free T4 and Free T3 remain within range. Despite the name 'subclinical,' it carries real health risks - 3-fold increase in atrial fibrillation, accelerated osteoporosis, and anxiety. It can progress to overt hyperthyroidism or resolve on its own, making monitoring essential.</p>",
        "why-test": "<p>TSH and Free T4 together detect subclinical hyperthyroidism with precision. Many doctors only order TSH - and if Free T4 is normal, they dismiss a low TSH. But a suppressed TSH below 0.4 warrants investigation regardless of Free T4 status. Annual monitoring determines whether the condition is progressing, stable, or resolving.</p>",
        "what-is-included": "<p>Your panel includes TSH, Free T4, Free T3, TPO antibodies, thyroglobulin antibodies, calcium, ALP, complete metabolic panel, lipid panel, CBC with differential, and CRP - 100+ biomarkers total.</p>",
        "next-steps": "<p>If TSH is suppressed, our care team recommends endocrinology referral for cause determination (Graves' vs nodular vs transient). Treatment depends on the cause, severity, age, and cardiovascular risk. Serial monitoring tracks progression or resolution.</p>",
        "meta-title": "Subclinical Hyperthyroidism Test | TSH + T4 | Superpower",
        "meta-description": "Detect subclinical hyperthyroidism - TSH, Free T4, Free T3, antibodies. 2% of adults affected. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Subclinical Hyperthyroidism Test | TSH + T4 | Superpower",
        "og-description": "Low TSH but told you're fine? Get the full thyroid panel. 100+ biomarkers. ~10 day results.",
    },
    "osteomalacia-biomarker-test": {
        "name": "Osteomalacia Biomarker Test",
        "hero-headline": "Bone Pain, Muscle Weakness, and Severe Vitamin D Deficiency? That's Osteomalacia.",
        "hero-subheadline": "<p>Osteomalacia is bone softening caused by severe vitamin D deficiency - the adult version of rickets. Vitamin D, calcium, ALP, and phosphorus blood tests detect it before fractures occur. When vitamin D drops low enough, bones literally can't mineralize properly. 100+ biomarkers. Results in about 10 days.</p>",
        "hero-cta-text": "Test Your Vitamin D and Bone Markers",
        "primary-keyword": "osteomalacia blood test",
        "secondary-keywords": "osteomalacia biomarkers, bone softening blood test, vitamin D deficiency bone test, ALP calcium test",
        "symptom-headline": "Signs that may indicate bone softening",
        "symptom-1": "Diffuse bone pain - especially hips, legs, and lower back",
        "symptom-2": "Muscle weakness making it hard to climb stairs or stand up",
        "symptom-3": "Waddling gait or difficulty walking normally",
        "symptom-4": "Known severe vitamin D deficiency that hasn't been treated",
        "symptom-5": "Malabsorption conditions like celiac, Crohn's, or gastric bypass",
        "symptom-cta": "Check your vitamin D and bone mineralization markers ->",
        "stat-1-number": "42%",
        "stat-1-text": "of US adults are vitamin D deficient - severe deficiency below 10 ng/mL causes osteomalacia with real bone damage and fracture risk",
        "stat-2-number": "100+",
        "stat-2-text": "biomarkers tested in one blood draw",
        "stat-3-number": "10 days",
        "stat-3-text": "to get your results",
        "featured-testimonial-quote": "<p>Hip and leg pain for over a year. Doctors said arthritis. Superpower found my vitamin D was 7 ng/mL (severely deficient - normal is 30+), ALP was 180 (elevated - bones were turning over abnormally), and calcium was borderline low. Osteomalacia. High-dose vitamin D for 3 months - the bone pain that 'arthritis' couldn't explain is 80% better.</p>",
        "featured-testimonial-name": "Margaret B.",
        "featured-testimonial-result": "Osteomalacia diagnosed - bone pain 80% improved with vitamin D treatment",
        "membership-subheadline": "Monitor vitamin D and bone health markers",
        "membership-benefit-1": "Vitamin D, calcium, and ALP tested annually",
        "membership-benefit-2": "100+ biomarkers including metabolic and thyroid",
        "membership-benefit-3": "AI flags severe vitamin D deficiency early",
        "membership-benefit-4": "24/7 care team access",
        "how-it-works-1-subheading": "One blood draw tests vitamin D (25-OH), calcium, ALP, phosphorus, complete metabolic panel, PTH-related markers, thyroid panel, and CBC - the biomarkers that detect osteomalacia - plus 90+ other markers. $199/year.",
        "how-it-works-2-subheading": "Osteomalacia creates a specific biomarker pattern: severely low vitamin D (typically below 10 ng/mL), elevated ALP (from increased bone turnover as the body tries to compensate), and low-normal or low calcium. Recognizing this pattern distinguishes osteomalacia from osteoporosis and other bone conditions.",
        "how-it-works-3-subheading": "Osteomalacia is often caused by malabsorption (celiac disease, Crohn's, gastric bypass), kidney disease, or simply severe dietary deficiency with limited sun exposure. We test calcium, phosphorus, and metabolic markers alongside vitamin D to identify the underlying cause - not just the deficiency itself.",
        "how-it-works-4-subheading": "Our clinical team explains your bone health biomarkers and recommends vitamin D supplementation with appropriate dosing for severity. For very low levels, they may recommend high-dose prescription vitamin D and specialist referral. Results in about 10 days.",
        "condition-name": "Osteomalacia Biomarker Screening",
        "condition-overview": "<p>Osteomalacia is softening of the bones due to impaired mineralization, most commonly caused by severe vitamin D deficiency. Unlike osteoporosis (which is loss of bone mass), osteomalacia means bones can't harden properly. It causes diffuse bone pain, muscle weakness, and increased fracture risk. With 42% of US adults vitamin D deficient, severe cases leading to osteomalacia are more common than many realize.</p>",
        "why-test": "<p>Vitamin D, calcium, and ALP blood tests detect osteomalacia before fractures occur. Severely low vitamin D (below 10 ng/mL) with elevated ALP is the hallmark pattern. Testing also identifies the cause - malabsorption, kidney disease, or dietary deficiency - which determines the right treatment approach and dosing strategy.</p>",
        "what-is-included": "<p>Your panel includes vitamin D (25-OH), calcium, ALP, phosphorus, complete metabolic panel, eGFR, creatinine, thyroid panel, CBC with differential, and CRP - 100+ biomarkers total.</p>",
        "next-steps": "<p>If vitamin D is severely low with elevated ALP, our care team recommends appropriate vitamin D replacement (high-dose for severe deficiency), calcium supplementation if needed, investigation of underlying causes (celiac screening, kidney function), and follow-up testing to confirm levels are normalizing.</p>",
        "meta-title": "Osteomalacia Blood Test | Vitamin D + Bone Markers | Superpower",
        "meta-description": "Test for osteomalacia - vitamin D, calcium, ALP, phosphorus. Bone softening from severe D deficiency. 100+ biomarkers. ~10 day results. $199/year.",
        "og-title": "Osteomalacia Blood Test | Vitamin D + Bone Markers | Superpower",
        "og-description": "Bone pain and muscle weakness? Vitamin D + calcium + ALP screen for osteomalacia. 100+ biomarkers. ~10 day results.",
    },
}


def fetch_all_pages():
    all_items = []
    offset = 0
    while True:
        url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items?limit=100&offset={offset}"
        resp = requests.get(url, headers=HEADERS)
        data = resp.json()
        items = data.get("items", [])
        all_items.extend(items)
        total = data.get("pagination", {}).get("total", 0)
        if offset + 100 >= total:
            break
        offset += 100
        time.sleep(0.3)
    return all_items


def main():
    print("=" * 70)
    print("BATCH 5: Rewrite 12 Tier 2 Biomarker-Test Pages")
    print("=" * 70)

    print("\nFetching all pages...")
    all_items = fetch_all_pages()
    slug_map = {}
    for item in all_items:
        slug = item.get("fieldData", {}).get("slug", "")
        if slug:
            slug_map[slug] = item

    results = []
    for slug, fields in REWRITES.items():
        if slug not in slug_map:
            print(f"\n  SKIP: {slug} not found")
            results.append({"slug": slug, "status": "NOT_FOUND"})
            continue

        item_id = slug_map[slug]["id"]
        print(f"\n  REWRITING: {slug}")

        url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items/{item_id}"
        resp = requests.patch(url, headers=HEADERS, json={"fieldData": fields})
        if resp.status_code == 200:
            print(f"    Updated: {fields['meta-title']}")
            results.append({"slug": slug, "item_id": item_id, "status": "UPDATED", "meta_title": fields["meta-title"]})
        else:
            print(f"    ERROR: {resp.status_code} {resp.text[:200]}")
            results.append({"slug": slug, "item_id": item_id, "status": "ERROR"})
        time.sleep(0.4)

    updated_ids = [r["item_id"] for r in results if r["status"] == "UPDATED"]
    if updated_ids:
        print(f"\nPublishing {len(updated_ids)} pages...")
        for i in range(0, len(updated_ids), 100):
            batch = updated_ids[i:i+100]
            url = f"https://api.webflow.com/v2/collections/{LP_COLLECTION}/items/publish"
            resp = requests.post(url, headers=HEADERS, json={"itemIds": batch})
            print(f"  Publish: {resp.status_code}")

    print(f"\n{'=' * 70}")
    print("SUMMARY")
    for r in results:
        print(f"  {r['slug']}: {r['status']}")

    with open("/Users/jeffy/superpower-sem-gap/app/data/biomarker_rewrite_batch5.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nSaved to biomarker_rewrite_batch5.json")


if __name__ == "__main__":
    main()
